viamrobotics/docs

- docs/installation/prepare/jetson-agx-orin-setup.md
* two tickets 
* add communication protocol table from 418, consulted with pete 
* revise from alan's comments on hardware setup & troubleshooting from 262
> DOCS 262 and 418: jetson orin updates

- docs/tutorials/configure/build-a-mock-robot.md
- docs/tutorials/configure/scuttlebot.md
- docs/tutorials/control/scuttle-gamepad.md
- docs/tutorials/control/yahboom-rover.md
- docs/tutorials/custom/custom-base-dog.md
- docs/tutorials/get-started/make-an-led-blink-with-a-raspberry-pi-and-sdk.md
- docs/tutorials/get-started/make-an-led-blink-with-the-viam-app.md
- docs/tutorials/get-started/try-viam-sdk.md
- docs/tutorials/projects/build-an-outdoor-rover.md
- docs/tutorials/projects/foam-dart-launcher.md
* thought this might be helpful to assist in tutorials page improvement before video launch
* can be iterated upon greatly as many tutorial refactoring tickets are up for upcoming months
> DOCS-614: standardize tutorial descriptions

- docs/tutorials/projects/make-a-plant-watering-robot.md
* changes from "box" to clear up @JessamyT confusion
* standardizes capitalization 
* removes extra sbc name drop from description
> DOCS-600: change container description and standardize capitalization on pi plant watering tutorial

- docs/tutorials/services/data-management-tutorial.md
> Capitalize Data Management

- .github/PULL_REQUEST_TEMPLATE.md
> DOCS-633: Add PR template

- static/js/index.js
> Check for toc existance

- docs/tutorials/projects/foam-dart-launcher.md
> Remove link to prepare page

- docs/appendix/glossary/board.md
- docs/appendix/glossary/rdk.md
- docs/appendix/glossary/resource.md
> Fix some glossary entries

- docs/appendix/glossary/location.md
- docs/appendix/glossary/organization.md
- docs/appendix/glossary/part.md
- docs/manage/parts-and-remotes.md
Depends on https://github.com/viamrobotics/docs/pull/975
> DOCS-190: Add parts, orgs, locations to glossary

- assets/scss/_sidebar-tree.scss
> Remove space between navbar and footer

- docs/components/base/_index.md
- docs/components/base/agilex-limo.md
- docs/components/base/boat.md
- docs/components/base/fake.md
- docs/components/base/wheeled.md
* fixing issue with images on base extending further than tab
> DOCS-648: change base images to markdown image format

- docs/installation/prepare/rpi-setup.md
* remove first of duplicate next steps sections on RPI setup docs
> DOCS 655: remove extra next steps on RPI setup

- assets/scss/_styles_project.scss
- layouts/shortcodes/card.html
> Reduce install card width to fit two on small screens

- docs/appendix/glossary/location.md
- docs/appendix/glossary/organization.md
- docs/appendix/glossary/part.md
- docs/manage/CLI.md
- docs/manage/configuration.md
- docs/manage/fleet/_index.md
- docs/manage/fleet/locations.md
- docs/manage/fleet/robots.md
> Add various fixes

- docs/manage/ml/train-model.md
- docs/manage/ml/upload-model.md
- Add aliases for ML content
- Fix aliases for ML content
> Add aliases for ML content

- docs/components/sensor/_index.md
> Fix sensor image

- docs/services/slam/run-slam-cartographer.md
- docs/try-viam/rover-resources/rover-tutorial.md
> DOCS-675: Add lidar mounting to cartographer tutorial

- layouts/docs/content.html
> Add draft alert

- docs/components/base/fake.md
- docs/components/sensor/fake.md
json-viam snuck back in here. Taking it out.
> Remove json-viam

- docs/tutorials/services/plan-motion-with-arm-gripper.md
API changes have resulted in the need for some updates on Motion tutorial sample code. All else ran successfully as of the 2023-04-17 QA plan execution.
> Remove slam Named argument from Motion Move calls

- docs/installation/_index.md
Found this one in an old tutorial google doc
> Add installation alias

- docs/components/sensor/_index.md
ooopsy!
* change "assumes" to "assume" on sensor page
(did this inline from website hence the odd branch)
> fix sensor "assumes" typo

- docs/tutorials/projects/integrating-viam-with-openai.md
> Agnosticize servo signal wire color in AI tutorial

- docs/components/movement-sensor/gps/gps-rtk.md
> Clarify name attribute on gps-rtk

- docs/appendix/release-notes.md
> DOCS-640: Change to mlmodel

- docs/tutorials/configure/build-a-mock-robot.md
- docs/tutorials/control/scuttle-gamepad.md
- docs/tutorials/control/yahboom-rover.md
- docs/tutorials/custom/custom-base-dog.md
- docs/tutorials/get-started/make-an-led-blink-with-a-raspberry-pi-and-sdk.md
- docs/tutorials/get-started/make-an-led-blink-with-the-viam-app.md
> Fix alias links

- docs/tutorials/control/yahboom-rover.md
> Remove broken link from yahboom tutorial

- layouts/partials/feedback.html
> Change docs events

- layouts/partials/feedback.html
> Change values

- docs/program/extend/modular-resources/_index.md
> fix extend typo

- docs/components/board/_index.md
Simpified is not exactly what I meant to say here
> fix typo on board

- docs/components/arm/fake.md
- docs/components/board/_index.md
- docs/program/extend/SDK-as-server.md
- docs/program/extend/modular-resources/_index.md
- docs/services/frame-system/_index.md
- docs/tutorials/projects/build-an-outdoor-rover.md
- docs/tutorials/projects/make-a-plant-watering-robot.md
The description of Caution use is "This provides notices that a certain action or event could damage hardware or cause data loss" so I think these ones are more in line with Note
> Change caution to note where applicable

- docs/manage/fleet/_index.md
> Update permissions for GA

- docs/services/slam/_index.md
- docs/services/slam/cartographer/_index.md
* tiny fixup to match Cartographer page caps
> fix RPlidar caps and quote on slam landing 

- docs/components/_index.md
> Update components intro

- docs/components/arm/fake.md
* noticed this while working on DOCS-696 and wanted to make a quickfix pr!
> quotes fix fake arm 

- docs/manage/fleet/organizations.md
Quick fix to 'navigation bar' formatting.
> Quick fix of navigation bar formatting

- docs/viam/_index.md
Tried to make some links more relevant. Took out sensor link because I think it's more distracting than useful there. Dunno if LAN needs to be expanded or not; happy to revert if folks think not.
> Fix Viam in 3 minutes nits

- docs/tutorials/get-started/confetti-bot.md
- docs/tutorials/get-started/lazy-susan.md
- docs/tutorials/projects/claw-game.md
- docs/tutorials/projects/modernize-retro-robot.md
- docs/tutorials/projects/pet-treat-dispenser.md
- docs/tutorials/projects/tipsy.md
placeholders for upcoming tutorials
> tutorial placeholders

- docs/services/data/configure-data-capture.md
Hi @agreenb - I think we were already using triplets for remote objects but I've added the camera one as an additional example - can you confirm everything is correct?
> DOCS-719: Add additional example for data capture

- docs/components/arm/_index.md
* noticed that these were missing while working on DOCS-214
> catch errors on go sample in arm component docs

- docs/program/extend/modular-resources/_index.md
* fix constructor method name referenced in registration, make pythonic
* fix ":=" -> "="
* update inline commenting
> fix python code sample issues in extend

- docs/components/gripper/_index.md
> Update _index.md for Gripper

- docs/program/extend/modular-resources/_index.md
* Make both is_powered, odd mismatch fix!
> match methods on motor for is_moving python module template 

- docs/components/arm/_index.md
* noticed "ismoving" was linked to the method above, "stop" -> fix
> tiny link fixup arm 

- docs/components/board/_index.md
* Was using singular method instead of plural in python code sample
> fix method call board api 

- docs/components/camera/_index.md
> Make camera API tab labels consistent

- docs/program/extend/modular-resources/_index.md
* suggested, to match example that's led through earlier in the page
> update example json in modular resources 

- docs/components/camera/webcam.md
- docs/tutorials/configure/scuttlebot.md
- docs/tutorials/projects/light-up.md
- docs/tutorials/projects/send-security-photo.md
video0 no longer shows up in the UI in favour of now only specifying the human readable id.
> DOCS-377: Remove references to video0

- .github/workflows/pr-deploy-and-comment.yml
Reverts viamrobotics/docs#1231
> Revert "Update pr-deploy-and-comment.yml"

- docs/installation/prepare/jetson-agx-orin-setup.md
- docs/installation/prepare/microcontrollers/_index.md
- docs/installation/update/_index.md
- docs/program/extend/modular-resources/examples/add-rplidar-module.md
- docs/services/slam/cartographer/_index.md
* realized that lowercase is standard, we have a mix, make it all start lowercase
> make macOS capitalization consistent

- docs/components/gripper/softrobotics.md
- docs/components/movement-sensor/adxl345.md
- docs/components/movement-sensor/cameramono.md
- docs/components/movement-sensor/fake.md
- docs/components/movement-sensor/gps/gps-nmea.md
- docs/components/movement-sensor/gps/gps-rtk.md
- docs/components/movement-sensor/gps/rtk-station.md
- docs/components/movement-sensor/imu/imu-vectornav.md
- docs/components/movement-sensor/imu/imu-wit.md
- docs/components/movement-sensor/mpu6050.md
- docs/installation/prepare/microcontrollers/_index.md
- docs/manage/configuration.md
- docs/manage/ml/train-model.md
- docs/manage/ml/upload-model.md
- docs/manage/parts-and-remotes.md
- docs/program/extend/modular-resources/_index.md
- docs/services/frame-system/_index.md
- docs/try-viam/rover-resources/rover-tutorial-fragments.md
- docs/try-viam/try-viam-tutorial.md
- docs/tutorials/configure/build-a-mock-robot.md
- docs/tutorials/control/yahboom-rover.md
- docs/tutorials/custom/custom-base-dog.md
- docs/tutorials/projects/make-a-plant-watering-robot.md
Per https://docs.rackspace.com/docs/style-guide/terminology/alphabetical-terms
> Change sub-tab to subtab

- docs/tutorials/projects/guardian.md
So as not to confuse folks with respect to what "components" means
> Change hardware section heading in Guardian tutorial

- docs/manage/configuration.md
A suggestion based on this ticket https://viam.atlassian.net/browse/DATA-1377
> Clarify default values

- docs/components/board/_index.md
* Add a requested note for an issue with the set power mode method in the board API.
* Clean up and fix board status method parameters, I had added power mode in there erroneously 🤦‍♀️
> DOCS-603: add note for power management api error

- docs/components/base/_index.md
* these samples were added before we had gotten clarification that Base effectively wraps BaseClient, this had slipped by me until now!
> change BaseClient to Base in python base samples

- docs/manage/parts-and-remotes.md
* Randomly noticed this -> remove caps post colon  on /manage/parts-and-remotes/, I think that is correct?
> remove unnecessary capitalization 

- docs/tutorials/projects/tipsy.md
> Add Tipsy STL link

- docs/services/slam/_index.md
i struggled to find this page and just saw a discord user who was also struggling to. i think this may help. 
i was also considering reworking the requirements and configuration of the cartographer page to make the rplidar steps harder to miss, but that is a less trivial reworking.
> Link to RPLidar module docs from SLAM docs

- docs/components/board/nanopi.md
* @mcvella tested & advised marking this as experimental. Could also specify support varies with board arch?
> DOCS-318: add experimental note for nanopi board

- config.toml
- docs/program/sdks/_index.md
> config.toml tiny typo fix

- docs/tutorials/projects/modernize-retro-robot.md
> Capitalize V for volt in MAIV tutorial

- .htmltest.yml
* quickfix as tests are failing 
* flaky external site
> add ufactory website to ignore

- docs/tutorials/projects/make-a-plant-watering-robot.md
* Add suggested power supply for 3B to hardware steps 
* Direct people to power on their Pis at the beginning of the tutorial
> DOCS-852: Add Pi power supply directions to plant watering tutorial 

- docs/components/base/_index.md
Linear and angular velocity comments were swapped, plus some newlines and expansion of mm to millimeters.
> Fix base API nits

- docs/tutorials/projects/make-a-plant-watering-robot.md
link redirects to a sold out item, now fixed!
> Update link to adc

- docs/manage/CLI.md
* made it into a note and added reauthentication detail
> DOCS-434: Clarify session re-authentication on the CLI page

- docs/services/navigation/_index.md
* change capitalization and formatting
* remove empty comment
> Make quick-fixes on new navigation service docs 

- docs/try-viam/rover-resources/rover-tutorial.md
Feedback from the last internal rover workshop
> Update rover-tutorial.md with punching advice

- docs/note.md
(and test branch auto-delete feature)
> Clarify note/tip description

- docs/extend/modular-resources/_index.md
Based on my experience building modular resources for python, here are changes I think should be made
> Modular resource updates for python

- docs/tutorials/projects/send-security-photo.md
Removed excess `to` article -- LMK if anyone thinks that the other `to` should be removed!
> Remove excess article

- docs/note.md
Just a quick change to re-trigger a site deploy.
> Monospace webm2mp4 command

- layouts/docs/baseof.html
> Fix missing else statement for toc

- docs/tutorials/services/constrain-motion.md
> Fix motion tutorial

- docs/components/arm/_index.md
- docs/components/board/_index.md
* Add new method into Arm api docs
* Add note explaining this is currently only available in the Python SDK
* Add method to program/apis
> DOCS-907: Document new Kinematics method for Arm in Python SDK 

- assets/scss/_styles_project.scss
- layouts/shortcodes/card.html
> Fix video width on small cards

- docs/tutorials/projects/modernize-retro-robot.md
> Fix image on retro robot tutorial

- docs/tutorials/custom/custom-base-dog.md
In my testing, it seems like this works more reliably. Including the note about other IP addresses because I was having some trouble with the server connecting and this might help folks who run into the same issue.
> Update IP address info on robot dog tutorial

- docs/tutorials/services/accessing-and-moving-robot-arm.md
- docs/tutorials/services/plan-motion-with-arm-gripper.md
I tested this new position works on a UR arm.
> RSDK-3613 update motion tutorial code to not use a singularity

- docs/services/vision/detection.md
> Fix typo on vision detections example code

- docs/components/arm/ur5e.md
- docs/components/arm/xarm6.md
- docs/components/arm/xarm7.md
- docs/components/arm/xarmlite.md
- docs/components/arm/yahboom-dofbot.md
- docs/services/navigation/_index.md
Make it consistent within a given doc, within components, and with what folks see on the app, and fix one invalid one
> Make brackets more consistent

- docs/program/_index.md
- Move parens out of link text
- minor fixes.
> Clarify link text

- docs/services/vision/_index.md
- docs/services/vision/classification.md
- docs/services/vision/segmentation.md
Also fix some copy pasta errors and missing params
> DOCS-938: Document Vision Service API

- docs/extend/modular-resources/examples/_index.md
- docs/extend/modular-resources/examples/custom-arm.md
* Add "custom arm" page to modular-resources/examples
> DOCS-854: Document implementation of a modular arm 

- docs/services/vision/detection.md
- docs/services/vision/segmentation.md
> Fix segmentation typo

- docs/tutorials/get-started/servo-mousemover.md
Updated video from teaser video to full video.
> DA-339: Update Youtube link in docs tutorial.

- docs/tutorials/projects/make-a-plant-watering-robot.md
Recent update to Server causes `TypeError: __init__() got an unexpected keyword argument 'components' `
Also updating rev count to match comment
> Fix plant watering robot tutorial

- docs/extend/modular-resources/create/_index.md
Tested & this all works now. Venv stuff is frustrating but I got some clarity on directing users for that by eavesdropping on james talking behind me in the office
> DOCS-763: More improvements to Python code sample in extend

- docs/services/slam/cartographer/_index.md
i've seen a couple people fail to add the module with the current order. hoping this helps (and that i edited the MD properly)
> Add the module before the service for cartograph

- docs/services/motion/_index.md
- static/include/services/apis/motion.md
Would love a careful review of code changes
> DOCS-991, DOCS-1007: Fix motion ResourceName, ax MoveSingleComponent

- docs/services/vision/classification.md
- docs/services/vision/detection.md
- docs/services/vision/segmentation.md
Python syntax -> Go syntax fix
The changes from visService to "my..." are just cosmetic (and make more sense, and align with the Python)
> DOCS-1032: Fix invalid vision Go syntax

- docs/extend/modular-resources/upload/_index.md
Just until current CLI `latest` becomes `stable`, where DOCS-1048 will deliver the change fully.
> Correct field name

- docs/extend/modular-resources/upload/_index.md
Quick fix to `update` section to remove `org-id`.
> Update from workshop feedback

- docs/internals/RDK.md
* Just noticed this description was rendering without changing to code-- we could probably update something on site theme css to make it render as code if dev content overall doesn't want to make this change
> Update RDK.md remove code ticks that don't render well in previews 

- docs/components/board/upboard.md
Noticed this is not actually visible in config builder atm, can re-un-comment whenever the FE is updated. 
SME is OOO rn but has been updated and approves of change being made temporarily!
> Comment out config builder section on `upboard`

- docs/note.md
This is causing a markdownlint error.
> Fix unmatched bold tags

- .github/workflows/docs.yml
> Fix deploy step

- .github/workflows/docs.yml
- Add typesense upload job
- Fix typesense upload build step
> Fix typsense upload build step

- docs/services/vision/classification.md
- docs/services/vision/detection.md
- docs/services/vision/segmentation.md
- docs/tutorials/projects/send-security-photo.md
- docs/tutorials/services/color-detection-scuttle.md
> Remove VisionServiceClient imports

- docs/extend/_index.md
- docs/extend/modular-resources/_index.md
- docs/extend/modular-resources/configure.md
- docs/extend/modular-resources/create/_index.md
- docs/extend/modular-resources/examples/_index.md
- docs/tutorials/custom/_index.md
- docs/viam/_index.md
Hi Fahmina, I'm gonna go get lunch now.
- [/extend/modular-resources/](https://docs-test.viam.dev/b9f182e993c1d385340a28e4d240b59353a13f4b/public/extend/modular-resources/)
> DOCS-1067: Add Viam Registry landing page

- docs/extend/modular-resources/_index.md
Fix Odrive link to module page
> Fix odrive link

- assets/scss/_styles_project.scss
> Speed up tutorials filter animation

- assets/scss/_styles_project.scss
- static/js/tutorials.js
> Update tutorials filtering UI

- README.md
Internal feedback from WTD conference
> Add templates to readme so contributors can find them more quickly

- docs/extend/modular-resources/examples/rplidar.md
Update this to specify this it's a camera and match other page descriptions' style (appears as text boxes on https://docs.viam.com/extend/modular-resources/examples/)
> DOCS-1069: Update rplidar.md page description

- docs/extend/modular-resources/examples/odrive.md
* Update this to be more consistent with other resource page descriptions and not use "how to"
> DOCS-1098: Update odrive.md page description

- docs/program/apis/robot.md
> Update robot.md fix typo

- docs/manage/fleet/robots.md
Was confused on how to delete a robot myself from the instructions from AI chatbot and App UI, think this rephrase could be an improvement
> Update robots.md for better instructions to delete robot

- docs/components/arm/_index.md
- docs/components/base/_index.md
- docs/components/camera/_index.md
- docs/components/encoder/_index.md
- docs/components/gantry/_index.md
- docs/components/gantry/single-axis.md
- docs/components/sensor/_index.md
- docs/components/servo/_index.md
Encoder one had incorrect info
> Make component config sections correct and consistent

- .github/workflows/alias-reminder.yml
> Update GitHub Action trigger

- .github/workflows/alias-reminder.yml
> Update alias reminder action

- docs/tutorials/services/try-viam-color-detection.md
> Update color detection tutorial

- layouts/docs/glossary.html
> DOCS-420: Fix heading links for glossary

- docs/program/apis/sessions.md
Think needs colon here to break up sections
> Update sessions.md add colon

- .github/workflows/prettier-lint.yml
- package-lock.json
- package.json
> Add prettier GitHub Action

- README.md
> Add instructions for local prettier linting

- assets/js/tutorials.js
> Address Sentry issue

- docs/tutorials/get-started/confetti-bot.md
* Fix blank md image, make img, fix other images that were centered weirdly
* Add missing link for STL files (talked with hazal, in same repo)
> DOCS-1003: Update confetti-bot.md fix images

- docs/program/run.md
> Update run.md remove typo

- docs/tutorials/projects/make-a-plant-watering-robot.md
took out process and remotes parts and added module
> Update tutorial with adc module

- docs/tutorials/projects/tipsy.md
To account for the updated Tipsy code in the [DevRel Demos repo](https://github.com/viam-labs/devrel-demos) that added support for a configurable number of ultrasonic sensors, this PR updates the content of the published tutorial to demonstrate this new functionality. I also clarified the difference between the tutorial Tipsy and the one used in "production", namely 2 vs 5 ultrasonic sensors. To help with this clarity, I updated the "Raw JSON" view to only configure 2 sensors and removes the IMU configuration as it is not mentioned in the tutorial until the end as a bonus challenge for the reader.
> DA-420: Update Tipsy tutorial with variable number of sensors

- docs/components/board/upboard.md
* Make it clear that this is necessary to work with the board, re. SME request
> DOCS-892: Emphasize upboard pin driver

- docs/services/vision/segmentation.md
Is `ground_plane_normal_vec` also present or is that only for the `obstacles_pointcloud` segmenter?
> DOCS-1189: Update obstacles depth attributes

- assets/scss/_styles_project.scss
- docs/_index.md
- docs/appendix/local-configuration-file.md
- docs/components/board/customlinux.md
- docs/installation/_index.md
- docs/installation/prepare/beaglebone-setup.md
- docs/installation/prepare/jetson-agx-orin-setup.md
- docs/installation/prepare/jetson-nano-setup.md
- docs/installation/prepare/pumpkin.md
- docs/installation/prepare/rpi-setup.md
- docs/installation/prepare/sk-tda4vm.md
- static/include/install/install-linux-aarch.md
- static/include/install/install-linux.md
> Update installation pages

- docs/components/board/beaglebone.md
- docs/components/board/pi.md
- docs/components/board/ti.md
Make it more clear that the setup guide is on a different page
> Fix board note wording nit

- docs/components/movement-sensor/mpu6050.md
We say "boolean" in every other JSON template
> Update mpu6050.md consistency nit

- docs/modular-resources/_index.md
- docs/modular-resources/examples/csi.md
This line snuck in from a merge conflict, and doesn't belong here.
> Delete extra line

- docs/modular-resources/examples/rplidar.md
- docs/services/slam/cartographer/_index.md
Re-add device path step that should not have been removed.
> DOCS-1258: Re-add RPlidar devpath step

- docs/services/navigation/_index.md
Found a small error while looking over the docs to send to a customer.
> Change position_polling_frequency to position_polling_frequency_hz

- .github/workflows/pr-deploy-and-comment.yml
> DOCS-1163: Deploy staging to prnumber link

- .github/workflows/pr-deploy-and-comment.yml
> Update deploy action

- .github/workflows/pr-deploy-and-comment.yml
> DOCS-1163: Update deploy and comment to deploy to pr number link

- docs/components/board/pca9685.md
Will soon become required, but for now we should at least make clear what the best practice is
> Add recommendation to pca9685

- docs/manage/CLI.md
- docs/modular-resources/upload/_index.md
Add mention to CLI > `viam organizations list` command that namespace is now also returned if one exists.
- Also added to MR upload steps, as the original ask for the eng ticket was to ease new module creation and upload workflow.
- Do not merge until APP-2546 indicates release has occurred (probably Oct 17).
> DOCS-1263: Add namespace to CLI org list

- docs/tutorials/get-started/lazy-susan.md
Realized this rather crucial part was missing when cross-posting this tutorial, I think this is how Kacey did it?
> Update lazy-susan.md instructions for connecting board/plate and motor

- static/include/micro-rdk-hardware.md
* Adds this info to "hardware requirements" includes
> DOCS-1289: Edit memory and core info and add supported models of ESP32 

- docs/program/_index.md
> Update  C++ SDK alpha> beta in Program Machine section

- docs/program/apis/cloud.md
Docs match SDK docs, but this PR makes these docs match the actual behavior
Related to https://viam.atlassian.net/browse/RSDK-5381
> Update get_robot_part error documentation

- assets/js/models.js
- assets/scss/_styles_project.scss
- docs/modular-resources/_index.md
- layouts/partials/scripts.html
This should simplify and improve the MR top level page. Some detail we currently go into can be deferred to subpages.
> DOCS-1198: Update MR top level page

- .github/workflows/check-methods.yml
- .github/workflows/check_python_methods.py
> DOCS-1226: Add workflow to check python methods covered

- docs/components/power-sensor/_index.md
- static/include/components/apis/power-sensor.md
* Adds `get_readings`/`Readings` to Power Sensor api docs
> DOCS-1151: Add `Readings` to power sensor

- docs/components/camera/_index.md
- docs/components/camera/ultrasonic.md
- docs/components/sensor/_index.md
- docs/components/sensor/ultrasonic.md
Re. conversation with Rand-- we haven't actually tested anything else so just recommending this model is best for now. Rand has signed off on this and un-requires her review
> Update phrasing on `ultrasonic` sensor/camera to recommend specific hardware

- docs/components/movement-sensor/_index.md
- docs/components/movement-sensor/imu/imu-vectornav.md
- docs/components/movement-sensor/merged.md
- docs/services/navigation/_index.md
- static/include/components/apis/movement-sensor.md
Marking as draft instead of outright removing in case we get it working again in future
> DOCS-1302: Remove imu-vectornav

- docs/modular-resources/_index.md
- docs/modular-resources/create/_index.md
- docs/modular-resources/upload/_index.md
Just some small changes, couldn't find a lot to improve on with how throughly everyone has reviewed it already!
> DOCS-1196: Modular resources review

- docs/micro-rdk/motor/_index.md
I _think_ this is all that needs to happen?
> DOCS-1305: Add GetProperties to micro-RDK motor

- static/include/micro-rdk.md
Forgot to change the title of the card
> Change micro-rdk tip card title to beta as well

- docs/components/board/_index.md
Found this issue
- Changes "base" to "board"
> Update _index.md change base to board on board page

- docs/tutorials/projects/make-a-plant-watering-robot.md
* We link to and use a resistive soil moisture sensor rather than capacitive, update docs to be accurate
> DOCS-1346: Update make-a-plant-watering-robot.md change sensor type to be accurate

- .github/workflows/check-methods.yml
> Run GA on any branch

- docs/manage/fleet/_index.md
I think we need something *explicitly* connecting the word "fleet" to the concept of a group of smart machines.
> Update fleet _index.md

- docs/installation/prepare/microcontrollers/_index.md
Add instructions and remove download information now that that's handled in setup tab
> DOCS-1354: Update setup tab instructions in prepare microcontrollers page

- .github/workflows/check_python_methods.py
Staging this for when we're ready
> Check app and robot APIs

- docs/micro-rdk/encoder/incremental.md
> Fix docs for configuring micro-rdk incremental encoder

- docs/appendix/glossary/slam.md
- docs/internals/slam.md
- docs/program/use-extra-params.md
- docs/services/slam/cartographer/_index.md
- docs/services/slam/orbslamv3/_index.md
Modify SLAM definition & update docs with tooltip. I didn't update where SLAM was referenced in parameter definitions.
> DOCS-1336: Add SLAM tooltip

- docs/services/navigation/_index.md
- static/include/services/apis/navigation.md
* `GetObstacles` --> `Obstacles`
> Fix Obstacles method name in Go code sample

- docs/program/apis/data-client.md
* Adds parameter and adds to code sample
> DOCS-1353: Add file_extension parameter for binary upload

- docs/services/navigation/_index.md
- static/include/services/apis/navigation.md
* Document `Paths` method of navigation service
> DOCS-1247: Document Navigation `Paths()`

- docs/appendix/glossary/modular-resource.md
- docs/appendix/troubleshooting.md
- docs/components/motor/_index.md
- docs/components/movement-sensor/adxl345.md
- docs/manage/parts-and-remotes.md
- docs/micro-rdk/movement-sensor/accel-adxl345.md
- docs/program/apis/cloud.md
- docs/program/apis/data-client.md
- docs/registry/examples/odrive.md
- docs/tutorials/configure/build-a-mock-robot.md
- docs/tutorials/projects/build-an-outdoor-rover.md
- docs/tutorials/projects/claw-game.md
- docs/tutorials/projects/integrating-viam-with-openai.md
- docs/tutorials/services/accessing-and-moving-robot-arm.md
- static/include/components/test-control/base-control.md
Convert full links to docs md pages to use rel links instead.
> DOCS-1383: Fix full self links in docs

- docs/manage/CLI.md
Add robot and location api key part 2
> DOCS-1370: Add robot api key - part 2

- docs/registry/create/_index.md
Copy button interprets extra leading space as part of the code. This fixes ability to copy & run this code.
> Fix sh spacing

- docs/components/board/_index.md
- docs/services/ml/_index.md
- docs/services/motion/_index.md
- docs/services/navigation/_index.md
- docs/services/sensors.md
- docs/services/slam/_index.md
- docs/services/vision/_index.md
- static/include/components/apis/analogreader.md
- static/include/components/apis/digitalinterrupt.md
- static/include/components/apis/gpiopin.md
- static/include/services/apis/ml.md
- static/include/services/apis/motion.md
- static/include/services/apis/navigation.md
- static/include/services/apis/sensors.md
- static/include/services/apis/slam.md
- static/include/services/apis/vision.md
Almost forgot the signaling apis!
> DOCS-1376: Document `close()` for all services and signaling apis attached to board

- docs/components/arm/_index.md
- docs/components/base/_index.md
- docs/components/board/_index.md
- docs/components/camera/_index.md
- docs/components/encoder/_index.md
- docs/components/gantry/_index.md
- docs/components/generic/_index.md
- docs/components/gripper/_index.md
- docs/components/input-controller/_index.md
- docs/components/motor/_index.md
- docs/components/movement-sensor/_index.md
- docs/components/power-sensor/_index.md
- docs/components/sensor/_index.md
- docs/components/servo/_index.md
- static/include/components/apis/arm.md
- static/include/components/apis/base.md
- static/include/components/apis/board.md
- static/include/components/apis/camera.md
- static/include/components/apis/encoder.md
- static/include/components/apis/gantry.md
- static/include/components/apis/generic.md
- static/include/components/apis/gripper.md
- static/include/components/apis/input-controller.md
- static/include/components/apis/motor.md
- static/include/components/apis/movement-sensor.md
- static/include/components/apis/power-sensor.md
- static/include/components/apis/sensor.md
- static/include/components/apis/servo.md
* Adds both Python and Go
All services to come
> DOCS-1376: Document `close()` method for all components

- docs/components/servo/gpio.md
> Update gpio.md PMW -> PWM

- docs/services/ml/_index.md
> Update _index.md change link

- docs/installation/_index.md
- docs/installation/prepare/jetson-agx-orin-setup.md
- docs/installation/prepare/jetson-nano-setup.md
- docs/installation/prepare/microcontrollers/_index.md
- docs/installation/prepare/pumpkin.md
- docs/installation/prepare/rpi-setup.md
- docs/installation/prepare/sk-tda4vm.md
- static/include/install/install-linux-aarch.md
- static/include/install/install-linux.md
Addressing suggestions from the UX research. I am not sure how we can make the next steps card less tangential. If you have an idea, please feel free to assign the rest of the ticket back to yourself once this merges
> DOCS-1267: Refactor Installation Guide

- docs/registry/examples/rplidar.md
> Update rplidar.md module string

- docs/registry/examples/rplidar.md
Stated it extends movement sensor API when really camera
> DOCS-1423: Update rplidar.md fix API misquote

- docs/micro-rdk/servo/_index.md
- docs/micro-rdk/servo/gpio.md
- static/include/micro-rdk.md
* Adds documentation for micro-RDK GPIO servo
@gvaradarajan Unsure if config builder tab should be in there-- LMK and I can delete if not supported?
> DOCS-1412: Make micro-RDK servo page

- docs/tutorials/configure/pet-photographer.md
Adding an image to the data filtering module tutorial.
> DOCS-1045: Add filter module tutorial pt2

- docs/registry/advanced/_index.md
- docs/registry/advanced/mlmodel-design.md
Add brief intro to custom ML model design doc on Registry > Advanced page.
> DOCS-1432: Add ML model design to Advanced

- docs/services/data/_index.md
- docs/services/frame-system/_index.md
- docs/services/ml/_index.md
- docs/services/vision/_index.md
> Remove required legend where needed

- docs/services/navigation/_index.md
* Remove linear and angular velocity
* Add supported methods
> DOCS-1462: Update Navigation requirements

- docs/build/configure/components/sensor/_index.md
Add power sensor as well to existing "see all" alert on sensors component landing page.
> Add power sensor to sensor alert

- docs/build/configure/components/camera/webcam.md
> Update webcam.md fix period where comma

- docs/get-started/installation/prepare/beaglebone-setup.md
Update second instance, same link.
> Fix second 404 link

- docs/mobility/navigation/_index.md
[Ticket](https://viam.atlassian.net/browse/RSDK-4512)
Updates nav defaults https://github.com/viamrobotics/rdk/pull/3294
> RSDK-4512 - Update default motion configuration

- docs/components/movement-sensor/gps/gps-nmea.md
* Make index
* Remove board attribute
> DOCS-1418: Update I2C attributes for GPS-NMEA

- docs/components/board/pi.md
- docs/components/board/pi5.md
- docs/components/motor/tmc5072.md
- static/include/components/board/board-analogs.md
* Make index instead of name across docs
Some slight confusion on my end about scope of this ticket, so @penguinland if I missed anything please let me know!
> DOCS-1442: Update the SPI strings in analogs

- docs/appendix/troubleshooting.md
> Update troubleshooting description language

- docs/get-started/try-viam/reserve-a-rover.md
- docs/registry/configure.md
Placing this here because it feels odd with the try viam content that should be more introductory. Open to other ideas
> Add note to explain modules not allowed on rovers

- docs/tutorials/projects/make-a-plant-watering-robot.md
Changed two instances of "JSON Template" to "Raw JSON" since they're not so much templates as just exactly what to do. Also fixed some newlines.
> DOCS-1511: Change JSON Template title in plant watering

- layouts/partials/edit-on-github.html
I'm not sure how I feel about this but people frequently miss this so I thought a less subtle approach might help.
> Update edit button

- docs/mobility/base-rc/_index.md
- docs/mobility/navigation/_index.md
> Fix service name caps

- docs/fleet/rbac.md
> Update rbac.md fix typo

- docs/build/micro-rdk/base/_index.md
- docs/build/micro-rdk/base/two_wheeled_base.md
Docs changes for moving this wheeled base into common.
> DOCS-1542: Change name of `esp32_wheeled_base` to `two_wheeled_base`

- docs/build/program/apis/cloud.md
- static/include/services/apis/cloud.md
Add documentation for the 7 methods that were added to Cloud App API
> DOCS-1520: Document App Client new methods 

- docs/build/program/apis/_index.md
- docs/components/movement-sensor/_index.md
- docs/mobility/slam/_index.md
- docs/mobility/slam/cartographer/_index.md
Tickets: 
* https://viam.atlassian.net/browse/RSDK-6203
* https://viam.atlassian.net/browse/RSDK-6204
* https://viam.atlassian.net/browse/RSDK-4720
Done:
* Added a link to make it easier to find cartographer
* Added movement sensor to "Used With" section
* Added slam to "Related Services" in movement sensor
* Inform the user that the lidar has to be mounted at the "center" of the base
* Fix typo
> RSDK-6203 & RSDK-6204 & RSDK-4720 - Improve slam documentation

- docs/build/program/apis/_index.md
- docs/data/dataset.md
> Update description of data upload

- docs/registry/create/_index.md
> DOCS-1636: Add logging examples for python

- docs/build/configure/_index.md
More significant revision might happen as part of configure a fleet page creation (separate ticket/PR)
> DOCS-1591: Clean up configure page

- docs/get-started/try-viam/rover-resources/rover-tutorial/_index.md
Clearly the new year did not get through to me
> Update _index.md fix year

- docs/build/micro-rdk/board/_index.md
- docs/components/arm/_index.md
- docs/components/board/_index.md
- docs/components/component/_index.md
- docs/components/gantry/_index.md
- docs/tutorials/configure/build-a-mock-robot.md
- static/include/components/apis/arm.md
- static/include/components/apis/board.md
- static/include/components/apis/gantry.md
- static/include/components/apis/gpiopin.md
- static/include/components/board/board-digital-interrupts.md
> DOCS-1575: Use proto names consistently

- docs/appendix/contributing.md
- Video encoding type no longer working, change to equivalent supported
> Update contributing.md update .webm ffmpeg command

- docs/get-started/try-viam/rover-resources/rover-tutorial/_index.md
Some requests from Chris! 
* Remove A3 and update A1 mount information for rplidar
* Add a note explaining open source and linking to designs
> Update rplidar info and add note to rover tutorial

- docs/build/program/apis/_index.md
> Update _index.md add link for data client

- docs/build/program/run.md
This is based on some user confusion that I observed from the AI chat
> Improve information for running code without internet connectivity

- docs/tutorials/projects/verification-system.md
What do you think about using the video for preview?
> Update preview to use video

- docs/components/base/wheeled.md
> Update wheeled.md base is not an arm

- docs/get-started/try-viam/rover-resources/rover-tutorial-fragments.md
* Request from Chris-- found that they had 2 different I2C buses
> Make separate rover fragments for jetsons

- docs/registry/upload/_index.md
> Github actions docs typo

- docs/fleet/rbac.md
- static/include/snippet/show-secret.md
**Remember to do a final sweep after merging in new changes to check for missed spots in between**
> DOCS-1667/1713: Update docs for security tab removal and update tabs on RBAC page R2D2

- docs/data/_index.md
> Add visualize to data landing page

- docs/tutorials/services/data-mlmodel-tutorial.md
Unless you want weight on this one!
> Remove weight and fix date II

- docs/components/board/customlinux.md
We are removing board packages from the package registry. This and #2439  are where I could find mentions of this command.
> RSDK-6277 Update customlinux.md to remove board packages

- docs/fleet/cli.md
We are removing board packages from the registry. This and #2438 are were I could find mentions of this command
> RSDK-6277 Update cli docs to remove board package

- docs/mobility/slam/cartographer/_index.md
* Update to reflect that data management and capture are no longer automatically configured in this workflow
> DOCS-1578: Add data management and capture steps to Cartographer SLAM page

- docs/components/board/customlinux.md
> Fix tabs on customlinux

- docs/tutorials/projects/tipsy.md
Reverts viamrobotics/docs#2125
> Revert "Update tipsy to use sensors service"

- docs/build/configure/_index.md
- docs/build/program/_index.md
- docs/build/program/apis/ml-training-client.md
- docs/build/program/connectivity.md
- docs/build/program/run.md
- docs/components/arm/_index.md
- docs/components/base/_index.md
- docs/components/board/_index.md
- docs/components/camera/_index.md
- docs/components/component/_index.md
- docs/components/encoder/_index.md
- docs/components/gantry/_index.md
- docs/components/generic/_index.md
- docs/components/gripper/_index.md
- docs/components/input-controller/_index.md
- docs/components/motor/_index.md
- docs/components/movement-sensor/_index.md
- docs/components/power-sensor/_index.md
- docs/components/sensor/_index.md
- docs/components/servo/_index.md
- docs/fleet/_index.md
- docs/ml/deploy.md
- docs/mobility/navigation/_index.md
- static/include/snippet/show-secret.md
* Also updating some outdated API key phrasing and ended up editing docs/build/program/_index.md phrasing slightly
> DOCS-1662: Change Code sample tab to page on CONNECT tab

- docs/get-started/installation/prepare/microcontrollers/development-setup.md
We have moved the repository containing the template code for Micro-RDK into the micro-rdk repository. The PR reflects the path changes
> Micro-RDK doc update

- docs/components/board/customlinux.md
Alan and Olivia--wasn't sure who to add as a reviewer so added both but only need one! Please advise if anything else needs to be changed other than these notes--thank you!
> DOCS-1570: Change hardware PWM note

- docs/appendix/troubleshooting.md
- docs/build/micro-rdk/board/esp32.md
- docs/build/program/run.md
- docs/components/base/sensor-controlled.md
- docs/data/cloud-sync.md
- docs/ml/vision/color_detector.md
- docs/ml/vision/detector_3d_segmenter.md
- docs/ml/vision/mlmodel.md
- docs/ml/vision/obstacles_depth.md
- docs/ml/vision/obstacles_pointcloud.md
- docs/mobility/frame-system/_index.md
- docs/mobility/slam/cartographer/_index.md
- docs/registry/configure.md
- docs/registry/examples/tflite-module.md
This isn't quite everything, ticketed everything that came up that I couldn't do yet that wasn't already ticketed
* Change save config instructions
* Update references to config tab subtabs for new workflows
> DOCS-1726: Update references to config tab subtabs

- docs/ml/vision/color_detector.md
- docs/ml/vision/detector_3d_segmenter.md
- docs/ml/vision/mlmodel.md
- docs/ml/vision/obstacles_depth.md
- docs/ml/vision/obstacles_distance.md
> DOCS-1765: Align vision model page titles

- docs/fleet/_index.md
- docs/fleet/rbac.md
* Add shoutout in fleet and section in rbac
> DOCS-1730: Document org permissions on mobile app

- docs/build/program/run.md
- static/include/program/authenticate.md
Also fixed typo in authentication snippet
> DOCS-1692: Edit Run Code Remotely

- docs/build/micro-rdk/base/two_wheeled_base.md
These could have any number of non-drive wheels
> Tweak two-wheeled base description

- docs/ml/vision/mlmodel.md
Looks like it was the indentation of the tabs (which doesn't affect the rendering--they're still nested!)
> DOCS-1817: Fix mlmodel page footer bug

- docs/ml/upload-model.md
Update wording for changes making label files not required but suggested in App upload workflow.
Q for reviewers: does anybody prefer "(Suggestion)" or "(Recommended)" to "(Optional)"?
> DOCS-1772: Update upload-model.md label files not required

- docs/components/movement-sensor/_index.md
* Document change to response and fields for both sdks 
* Reword GetAccuracy method intro
> DOCS-1539: New structure for Movement Sensor GetAccuracy response objects

- docs/components/generic/_index.md
- docs/registry/advanced/generic/_index.md
Add link from each generic to the other.
> DOCS-1826: Link between generics

- docs/fleet/_index.md
adding images with links to app store sites
I have seen this on other docs sites and it is a good draw to the mobile app. Let me know if how i pasted in the images is not how you tend to store them.
> Images of respective app stores with links

- .htmltest.yml
> Ignore chromewebstore link

- docs/_index.md
> Fix try viam link

- docs/registry/create/_index.md
* Add instruction to use generator (necessary to fully use template) and instruction that just points to template
> DOCS-1407: Add viam module generator / README template to create page

- docs/tutorials/custom/custom-base-dog.md
> Fix custom-base-dog.md code formatting

- .htmltest.yml
> Add raspberry pi link to htmltest ignoreURLs

- docs/components/movement-sensor/gps/gps-nmea.md
Figured this makes sense as it's supported by all GPS models?
> Update gps-nmea.md add GetAccuracy as supported method

- docs/registry/create/_index.md
> Update typo in registry docs

- docs/tutorials/projects/guardian.md
- docs/tutorials/projects/send-security-photo.md
> DOCS-1832: Update guardian tutorial to use ml model from registry

- docs/fleet/_index.md
> Center app store images 

- docs/components/_index.md
- layouts/docs/content.html
> Fix components cards

- layouts/docs/content.html
> Use permalinks instead of permalink to get page

- docs/components/movement-sensor/_index.md
- docs/components/movement-sensor/gps/gps-nmea-rtk-pmtk.md
- docs/components/movement-sensor/gps/gps-nmea-rtk-serial.md
- docs/components/movement-sensor/gps/gps-nmea.md
- docs/components/movement-sensor/imu/imu-vectornav.md
- docs/components/movement-sensor/imu/imu-wit.md
adding GetAccuracy to gps-nmea-rtk-pmtk, gps-nmea-rtk-serial, and imu-wid
> DOCS-1688: Update gps to add links

- docs/registry/create/_index.md
Fix several CPP repo links from the Create page now that CPP SDK team has restructured resource folder structure.
> DOCS-1889: Fix CPP links

- docs/fleet/machines.md
An instruction in https://github.com/viam-labs/YOLOv8?tab=readme-ov-file pointed here until I just fixed it; maybe other places also do
> Add alias to machines.md

- docs/build/provision/_index.md
> Update provisioning to be SDK agnostic

- docs/components/movement-sensor/_index.md
> Update _index.md fix built-in models

- docs/fleet/rbac.md
Updating mobile docs to reflect new information architecture. This change shouldn't go out until it is merged. This is specific to 1.9.0
> Update mobile app instructions for accessing settings

- docs/data/upload.md
Mobile app information architecture changes that will be a part of 1.9.0
> Update instructions for mobile app data upload

- docs/ml/_index.md
This link currently links to the page you're already on.
> Fix ml model link

- docs/build/configure/_index.md
* Add requirements from regex
Choose not to add regex itself but can if think appropriate?
> DOCS-1914: Add resource name requirements to configure a machine

- docs/tutorials/projects/claw-game.md
Fix https://github.com/viamrobotics/docs/issues/2656
> Remove homedepot links

- .github/workflows/run-htmltest.yml
- docs/tutorials/projects/guardian.md
> test broken link

- docs/ml/vision/color_detector.md
- docs/ml/vision/mlmodel.md
* Make attributes table
* Add new attributes
* Clean up rest of page a bit
> DOCS-1897: Add attributes to ML model vision service

- docs/appendix/changelog.md
- docs/ml/_index.md
- docs/ml/deploy/_index.md
- docs/ml/deploy/tflite_cpu.md
- docs/ml/vision/_index.md
- docs/registry/_index.md
- docs/tutorials/projects/filtered-camera.md
* Move and rework page a little bit
> DOCS-1999: Move `tflite_cpu` to its own page

- docs/ml/deploy/_index.md
> Update deploy page to remove child page card

- docs/ml/vision/mlmodel.md
> Update mlmodel.md fix detector or classifier phrasing

- docs/components/board/_index.md
> SetPowerMode board API section is titled SetPWM

- docs/fleet/provision.md
Add links to Agent and Agent Provisioning subsystem GH repos now that they are public.
> DOCS-1304: Add links to agent repos

- docs/appendix/changelog.md
Add Viam Agent changelog entry.
> DOCS-1902: Add Viam Agent changelog

- docs/components/base/sensor-controlled.md
Updating sensorcontrolled base doc to include the controlled MoveStraight and to accurately reflect requirements for the controlled version of each API. 
ticket: https://viam.atlassian.net/browse/DOCS-1673
> DOCS-1673: Document sensorcontrolled move straight

- docs/registry/create/_index.md
Sky left some great comments on https://github.com/viam-labs/agilex/pull/4/files updating links and styling, implementing here
> Apply Sky's suggestions on module readme

- docs/data/capture/_index.md
> Update data page to add links to tutorial and subpage

- docs/components/board/_index.md
Fix link and "extra" parameter on WriteAnalog()
> Update board WriteAnalog() fix link

- docs/build/program/apis/billing-client.md
> Update billing-client.md is not data client

- static/include/services/apis/billing-client.md
> Update billing-client.md add links to include

- docs/build/configure/parts-and-remotes.md
> Update parts-and-remotes to add remote instructions for select

- docs/mobility/slam/cartographer/_index.md
thought more applicable than service page as that doesn't mention cloud SLAM
- Add brief notice
> DOCS-2004: Add notice that cloud SLAM is temporarily disabled to cartographer 

- docs/appendix/changelog.md
Add end-of-feb --> all-of-march 2024 changelog. Think this is everything!
> DOCS-2019: Add Mar 2024 changelog

- docs/use-cases/_index.md
- Make simple use cases landing page with cards
> DOCS-1587: Make use cases landing page

- docs/get-started/installation/_index.md
An attempt to provide more context, but quickly w/o drowning reader in details. Would love SME to review with respect to whether this is incomplete, misleading, overly simplistic or otherwise not useful.
> DOCS-1925: Add viam-server explanation to install intro

- docs/build/program/_index.md
Have a look at https://docs-test.viam.dev/2694/build/program/#apps-with-authentication
> DOCS-2041: Add auth note

- docs/build/configure/_index.md
Edit restart viam-server instructions for new workflow on part card
- Edit on docs/build/configure (this is the only place I could find this was mentioned)
> DOCS-2050: Restart button change R2D2

- assets/scss/_styles_project.scss
> Fix css for mobile

- docs/fleet/cli.md
- docs/registry/create/_index.md
- docs/registry/upload/_index.md
Implementing suggestions from [scope](https://docs.google.com/document/d/1E0EzdlBNrPXZi5ki1J5FGAiOIETYVHE0fUVtV9JN5I8/edit#heading=h.tcicyojyqi6c)
> DOCS-1592: Make PyInstaller recommended method and edit build command

- docs/tutorials/control/flutter-app.md
Could not find anything besides this lol
> DOCS-1939: Scan flutter app tutorial for updates R2D2

- docs/tutorials/services/constrain-motion.md
Idk why I felt the need to edit the commented out frame section as well -- @JessamyT is there a reason that part would be readded or could I delete it?
> DOCS-1949: Review constrain motion tutorial

- docs/ml/vision/obstacles_pointcloud.md
Realized this was off while doing R2D2 updates, figured it might be better to fix before R2D2
> Update obstacles_pointcloud.md model name

- docs/get-started/installation/prepare/microcontrollers/_index.md
- static/include/micro-rdk-hardware.md
With the release of v0.1.8 we support multiple concurrent connections,  I changed the language slightly to reflect this
> Update micro-rdk docs

- docs/fleet/configure-a-fleet.md
- docs/internals/local-configuration-file.md
(it hasn't technically been renamed debug from full yet but [APP-4517](https://viam.atlassian.net/browse/APP-4517) pr is about to be released) 
[APP-4517]: https://viam.atlassian.net/browse/APP-4517?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOCS-2104: Document re-add see full config button as view debug configuration

- docs/tutorials/get-started/try-viam-sdk.md
> DOCS-1934: Review try viam sdk tutorial for R2D2

- docs/build/configure/parts.md
> Update remote selection remove old method R2D2

- layouts/partials/head.html
> Remove Google Analytics dependency

- docs/tutorials/projects/filtered-camera.md
- docs/tutorials/projects/send-security-photo.md
> Fix security photo tutorial

- docs/tutorials/get-started/servo-mousemover.md
> DOCS-2154: Fix css bug on videos

- docs/tutorials/configure/build-a-mock-robot.md
- docs/tutorials/configure/configure-rover.md
- docs/tutorials/configure/pet-photographer.md
- docs/tutorials/custom/controlling-an-intermode-rover-canbus.md
- docs/tutorials/custom/custom-base-dog.md
- docs/tutorials/get-started/blink-an-led.md
- docs/tutorials/get-started/lazy-susan.md
- docs/tutorials/get-started/servo-mousemover.md
- docs/tutorials/projects/claw-game.md
- docs/tutorials/projects/filtered-camera.md
- docs/tutorials/projects/helmet.md
- docs/tutorials/projects/integrating-viam-with-openai.md
- docs/tutorials/projects/make-a-plant-watering-robot.md
- docs/tutorials/projects/pet-treat-dispenser.md
- docs/tutorials/projects/send-security-photo.md
- docs/tutorials/services/accessing-and-moving-robot-arm.md
- docs/tutorials/services/data-mlmodel-tutorial.md
- docs/tutorials/services/visualize-data-grafana.md
- docs/tutorials/services/webcam-line-follower-robot.md
- static/include/snippet/setup.md
> DOCS-1925: Make setup instructions the same everywhere

- docs/data/capture/_index.md
Just ran into this as I was editing a fragment--it's hard to find which options are available!
> Add more attributes to data JSON config example

- docs/components/board/_index.md
- static/include/components/apis/board.md
> DOCS-2022: Document `StreamTicks()`

- docs/fleet/provision.md
@ale7714 there is nothing better to link to for typescript than the implementation code currently right?
> Update provisioning to include typescript

- docs/data/dataset.md
- docs/data/export.md
- docs/data/view.md
- docs/fleet/cli.md
- docs/use-cases/image-data.md
> DOCS-2182: Update filtering UI

- docs/build/program/apis/robot.md
> DOCS-2240: Update robot management go snippets

- docs/appendix/changelog.md
> Update board changelog entry

- docs/get-started/installation/prepare/sk-tda4vm.md
Came across this while working on orangepi
> Update sk-tda4vm.md add better balenaetcher download link

- docs/data/query.md
> DOCS-2242: Add warning for data query docs

- docs/tutorials/configure/configure-rover.md
- docs/tutorials/control/gamepad.md
- docs/tutorials/custom/controlling-an-intermode-rover-canbus.md
- docs/tutorials/get-started/try-viam-sdk.md
- docs/tutorials/services/color-detection-scuttle.md
- docs/tutorials/services/try-viam-color-detection.md
> Add learning goals for rover tutorials

- docs/get-started/installation/prepare/microcontrollers/development-setup.md
* Update as suggested to cover new versions
> DOCS-2275: Update cargo espflash command

- docs/registry/upload/_index.md
In these docs we do not judge 😂
> Adjust support callout language

- docs/ml/deploy/tflite_cpu.md
> Add next steps to tflite

- docs/data/capture/_index.md
- docs/data/cloud-sync.md
- docs/tutorials/services/data-mlmodel-tutorial.md
Add notice of new full disk handling feature to Data management service > data capture reference page
- Also updated warning on Cloud sync page
- Also made tiny mention on Data ML tutorial
> DOCS-1842: Add handling for disk full

- docs/cli.md
> Add delete data snippet

- docs/cli.md
> Update cli to use shell background

- layouts/partials/toc.html
> Fix another TOC bug

- docs/cli.md
> DOCS-1422: Change robots to machines in CLI

- docs/registry/create/_index.md
assume this was not intentional that it wasn't updated alongside template?
> Update module readme example from template

- docs/sdks/_index.md
- layouts/shortcodes/sectionlist-custom-item.html
- layouts/shortcodes/sectionlist-custom.html
@loopDelicious Have a look at https://docs-test.viam.dev/2939/sdks/ and let me know if this is what you were looking for to separate the SDKs / provide more info
> Update SDKs page

- .github/workflows/update_sdk_methods.py
Update `update_sdk_methods.py` to be Python 12 compatible.
- Update escaping of `{}` characters in raw string
- Updated setup instructions (in wiki) to accommodate for different dependency sourcing if `brew`.
Unrelated fix:
- PySDK introduced linked data types for errors raised (starting with `get_detections_from_camera()`). Added support for scraping these links as well.
> DOCS-2379: Update for Py12 compatibility

- docs/mobility/slam/_index.md
- docs/mobility/slam/cartographer/_index.md
* add notice where requested 
Unsure whether to delete the cloud SLAM part of the cartographer alert bc a bit duplicative? but might be good to specify?
> DOCS-2271: Add notice for live SLAM being unavailable

- docs/get-started/installation/_index.md
> Add extra boards

- layouts/docs/baseof.html
- layouts/docs/changelog.html
- layouts/docs/content.html
- layouts/docs/glossary.html
- layouts/docs/tutorials.html
> Update GA include to definitely not run on staging

- .github/workflows/update_sdk_methods.py
based on the refactoring draft
> Fix ordering automation

- docs/data/capture/_index.md
Needs SME review
[TODO: surface/make this section more visible]
> DOCS-2266: Update service configs capture methods in remote data capture example

- .markdownlint.yaml
- docs/components/generic/_index.md
- docs/components/motor/_index.md
- docs/components/movement-sensor/_index.md
- docs/ml/vision/_index.md
- docs/registry/advanced/generic/_index.md
> Update markdownlint rules

- docs/components/arm/_index.md
Realized this while making SDK edits
> Update Arm MoveToPosition make it clear that Pose parameter is destination pose

- docs/components/camera/_index.md
* Fix missing parenthesis on camera method
> Update _index.md fix parentheses

- .github/workflows/update_sdk_methods.py
Fix four issues with Go SDK site parsing:
- Fix parsing of methods that make use of type inference to omit select data type for required parameters.
- These are the parameters: `angleDeg`, `linear`, `positionsMm`, `rpm`, and `srcName`,
- Fix single instance of two word parameter name for `ch chan`, a channel type parameter.
- Fix returns sometimes having bogus "return names" included: Go returns are unnamed.
- Fix Viam-specific data types sometimes having malformed URLs.
> DOCS-2474: Fix omitted data types

- .github/workflows/update_sdk_methods.py
Add support for also scraping code samples from inherited Go methods (like `Actuator` interface method: `IsMoving`, for example).
> DOCS-2473: Add Go inherited method code samples

- docs/fleet/_index.md
* Change history tab mention to part history page
* Make periods consistent
> Quick fixups on deploy a large fleet

- static/include/components/apis/generated/arm-table.md
- static/include/components/apis/generated/arm.md
Update generated `arm.md` and `arm-table.md` with fixes from https://github.com/viamrobotics/docs/pull/2992 and https://github.com/viamrobotics/docs/pull/2993
> Update arm.md and arm-table.md

- docs/use-cases/_index.md
- layouts/docs/tutorials.html
https://docs-test.viam.dev/3022/use-cases/
https://docs-test.viam.dev/3022/tutorials/
> Add content type explanations

- .htmltest.yml
> DOCS-2499: Do not test rtk2go links

- docs/services/ml/train-model.md
I see that the beginning of the GIF on this page is technically out of date, but I think the UI is sufficiently self-explanatory and has nice descriptions on each element so I think leaving the GIF as-is makes sense; it's a nice data set of Toast pictures :)
> DOCS-2402: Update model training flow

- static/include/components/apis/generated/camera-table.md
- static/include/components/apis/generated/camera.md
Correct instance of third-person verb.
> Correct third-person verb

- docs/get-started/_index.md
- layouts/partials/card.html
- layouts/shortcodes/manualcard.html
> Fix link based on website feedback

- docs/use-cases/_index.md
> Update how to guide landing page

- docs/registry/create/_index.md
> Fix broken link

- .github/workflows/sdk_protos_map.csv
- static/include/robot/apis/generated/robot.md
Add Robot API `shutdown` Go method code sample
- Also adds Flutter methods for this API.
> DOCS-2307: add robot API shutdown

- docs/tutorials/configure/pet-photographer.md
- docs/tutorials/projects/filtered-camera.md
- docs/tutorials/projects/helmet.md
- docs/tutorials/projects/verification-system.md
- docs/tutorials/services/data-mlmodel-tutorial.md
Additionally made some steps numbered to match the rest of that tutorial and for easier user interaction (per feedback on how-to content)
> DOCS-2599: Instruct users to set MIME type in data capture UI

- .github/workflows/update_sdk_methods.py
- docs/appendix/apis/_index.md
- docs/services/base-rc/_index.md
- docs/services/data/_index.md
- static/include/services/apis/base-rc.md
- static/include/services/apis/data.md
- static/include/services/apis/generated/base_remote_control-table.md
- static/include/services/apis/generated/base_remote_control.md
- static/include/services/apis/generated/data_manager-table.md
- static/include/services/apis/generated/data_manager.md
- static/include/services/apis/overrides/methods/go.base_remote_control.ControllerInputs.Control.return.md
Merge autogen content for `base_remote_control` and `data_manager` service APIs.
> DOCS-2424: Merge autogen: baserc, datamgr

- docs/registry/create/_index.md
* Fix broken link on agilex module template
> DOCS-2578: Fix broken link on template 

- docs/fleet/fragments.md
- docs/registry/upload/_index.md
- docs/tutorials/control/air-quality-fleet.md
Fixes bug where expanders that are indented appear like this:
> Fix expander formatting bug

- docs/use-cases/collect-sensor-data.md
Realized we have 3 of the same. Query makes sense for the other two but this one should be different.
> Update collect-sensor-data.md thumbnail

- docs/use-cases/sensor-data-query.md
Per ticket ask: Clarify which flavor of SQL data query supports (Atlas SQL) and bring MQL reference link to top of this page.
> DOCS-1867: Specify SQL dialect

- docs/build/configure/triggers.md
* Demonstrate this in docs (not sure if we should start doing more to document?)
> DOCS-2559:Add new headers to triggers

- docs/cloud/_index.md
- docs/fleet/_index.md
- docs/use-cases/_index.md
> Make title caps match

- docs/components/movement-sensor/gps-nmea-rtk-pmtk.md
- docs/components/movement-sensor/gps-nmea-rtk-serial.md
- docs/components/movement-sensor/gps-nmea.md
The GPS chip that we use supports RTCM ver <= 3.3
> Add RTCM version for GPS 

- docs/appendix/changelog.md
- docs/cloud/rbac.md
- docs/tutorials/control/air-quality-fleet.md
> DOCS-2636: Add operator permissions change

- layouts/shortcodes/tablestep.html
I've tried making it say "More info" and it doesn't look great. So I'm trying a question mark circle instead. Let me know what you think.
> DOCS-2641: Change more info icon

- .htmltest-local.yml
- .htmltest.yml
> DOCS-2722: Stop testing link for researchgate

- docs/get-started/quickstarts/write-code.md
- docs/use-cases/_index.md
- docs/use-cases/configure.md
- docs/use-cases/create-module.md
- docs/use-cases/develop-app.md
- **Update styling on use-cases**
- **DOCS-2739: Update configure page**
> DOCS-2739: Update configure page

- docs/configure/processes.md
> Update processes.md add alias

- docs/configure/_index.md
- static/include/components/camera-view-camera-stream.md
* document exporting screenshot, refresh rate, picture in picture
* add better information about test section
> DOCS-2589: Document picture in picture

- docs/_index.md
> Change front page

- docs/get-started/_index.md
https://docs-test.viam.dev/3211/get-started/
> Split Viam intro page into two sections

- docs/use-cases/_index.md
> Include fragment how to in how to list

- docs/get-started/drive-rover.md
> Mention control panel on the drive rover quickstart

- docs/services/ml/upload-training-script.md
@tahiyasalam can you review the template please to make sure I didn't mess that up? 
There are more changes I'll be making but I think that's the biggest one.
Also: Is it only setup.py that’s needed in addition? Because there’s also:
- PKG-INFO
- model
- `__init__.py`
- setup.cfg
- setup.py
- training.egg-info
- PKG-INFO
- SOURCES.txt
- dependency_links.txt
- requires.txt
- top_level.txt
> DOCS-2653: Update the training script docs

- docs/get-started/collect-data.md
- docs/get-started/control-motor.md
- docs/get-started/detect-people.md
- docs/use-cases/develop-app.md
waiting for https://docs-test.viam.dev/3247/use-cases/develop-app/
> Update quickstart videos

- docs/cli.md
* changes robot-machine in more places as they were aliased
* adds four commands: viam data tag filter add, viam data tag filter remove, viam data tag ids add, viam data tag ids remove
* tested all commands
> DOCS-2007: Add tag cli argument

- .github/workflows/pr-deploy-and-comment.yml
- .github/workflows/run-htmltest-local.yml
- .github/workflows/run-htmltest.yml
- Makefile
> Test caching node_modules

- .github/workflows/upload_tutorials.py
> DOCS-2845: Upload how-tos to typesense

- docs/how-tos/collect-sensor-data.md
- docs/how-tos/sensor-data-query-sdk.md
- docs/how-tos/sensor-data-query-with-third-party-tools.md
- docs/how-tos/sensor-data-visualize.md
- docs/services/ml/edit.md
I don't think this script needs to be on any of these pages?
> Remove unnecessary script from frontmatter

- docs/architecture/rdk.md
- docs/installation/_index.md
- docs/installation/micro-rdk-dev.md
@loopDelicious you had said the installation for esp32 was confusing, could you review 
https://docs-test.viam.dev/3302/installation/ and tell me what you think?
> DOCS-2785: Update installation guide for new UI

- assets/js/howtos.js
- assets/js/tutorials.js
- assets/scss/_styles_project.scss
- static/include/app/apis/overrides/protos/app.GetFragmentHistory.md
- static/include/app/apis/overrides/protos/dataset.ConfigureDatabaseUser.md
- static/include/robot/apis/overrides/protos/robot.GetMachineStatus.md
Decided to not add a hover effect on a hover effect. I think this works
> DOCS-2846: Add content type legend

- docs/how-tos/collect-sensor-data.md
- docs/how-tos/image-data.md
* changes model used to bijan's face detector for simplicity
* adds images from other quickstart 
* adds some more details and clarifications
> DOCS-2789: QA capture sync image data how-to with filtered camera

- docs/appendix/try-viam/rover-resources/rover-tutorial-fragments.md
- docs/appendix/try-viam/rover-resources/rover-tutorial/_index.md
- docs/components/board/pi5.md
~~@randhid IDK the actual hardware nitty-gritty of how someone would wire this. Do they need to get rid of the ribbon cable and wire the entire thing with jumper wires or can they just snip two wires in the ribbon connector and attach them to each other? Or some other solution entirely?~~
> DOCS-2815: Update Viam rover fragment instructions for RPi5

- docs/appendix/changelog.md
- docs/services/generic/fake.md
- docs/services/slam/orbslamv3/_index.md
- docs/tutorials/services/plan-motion-with-arm-gripper.md
Came across these whilst doing upload data (which also had some pre-R2 instructions)
> Update old tab verbiage

- docs/cli.md
* add logs command 
* tested and works
> DOCS-2871: Add `logs` command to `train` in CLI

- docs/how-tos/create-module.md
OAK was migrated to viam-modules. This updates the link and tag
> Update OAK link

- docs/_index.md
> Update landing page link to version module

- docs/how-tos/image-data.md
- docs/services/data/_index.md
- docs/services/data/capture/_index.md
- docs/services/data/cloud-sync.md
- docs/services/data/export.md
- docs/services/data/view.md
- docs/services/vision/mlmodel.md
- docs/tutorials/projects/filtered-camera.md
- docs/tutorials/services/data-mlmodel-tutorial.md
These pages should go away entirely. For now moving them to drafts.
> Move data pages to drafts

- docs/how-tos/manage-fleet.md
* tested in app.viam.com and app.viam.dev -- found one bug reported [here](https://viam.atlassian.net/browse/APP-6155) but otherwise pretty straightforward
* add better instructions for RBAC, explicitly tell them its on organization settings page
> DOCS-2798: QA manage a fleet of machines

- docs/components/servo/_index.md
> Remove duplicate table on servo component

- docsearch.json
> Ignore hovercard content for search

- docsearch.json
- **Ignore hovercard content for search**
- **Improve search on docs page**
> DOCS-2919: Improve search on docs page

- docs/services/frame-system/_index.md
- docs/services/motion/_index.md
- docs/services/slam/_index.md
Some of these are incorrect: idk a use case for using board with the frame system, and motion does not require a movement sensor.
> Update used with

- assets/js/howtos.js
- assets/js/tutorials.js
- assets/scss/_styles_project.scss
- layouts/docs/howto.html
- layouts/docs/tutorials.html
https://docs-test.viam.dev/3420/how-tos/
> Change how-to guides page to filter by area

- docs/appendix/changelog.md
* updates changelog for mid july-sept 6th
> DOCS-2929: Update changelog

- docs/tutorials/projects/rover-typescript.md
> update rover tutorial rss link

- docs/how-tos/deploy-packages.md
- static/include/robot/apis/generated/robot.md
Have run this past Shawn - he says this is helpful to add. He may have additional things we can add to the script. Will add when he sends.
> DOCS-2947: Use machine status to get machine info

- docs/tutorials/services/color-detection-scuttle.md
> Update color follower intro

- docs/_index.md
- docs/appendix/apis/billing-client.md
- docs/appendix/apis/data-client.md
- docs/appendix/apis/ml-training-client.md
- docs/appendix/changelog.md
- docs/architecture/viam-micro-server.md
- docs/cli.md
- docs/fleet/provision.md
- docs/how-tos/_index.md
- docs/how-tos/drive-rover.md
- docs/installation/_index.md
- docs/installation/manage-viam-agent.md
- docs/installation/manage-viam-server.md
- docs/installation/viam-micro-server-dev.md
- docs/platform.md
- docs/services/ml/_index.md
- docs/services/ml/deploy/_index.md
- docs/services/ml/training-scripts.md
- layouts/partials/head.html
We now get warnings for old content. Currenty only for pages we have a date in the frontmatter for. We'll need to add dates to the rest of the content but should do so in stages.
```
WARN  Last update more than 6 months ago (2024-01-04 00:00:00 +0000 UTC): /how-tos/navigate
WARN  Last update more than 6 months ago (2022-10-11 00:00:00 +0000 UTC): /tutorials/configure/build-a-mock-robot
WARN  Last update more than 6 months ago (2024-01-17 00:00:00 +0000 UTC): /tutorials/control/flutter-app
WARN  Last update more than 6 months ago (2023-09-17 00:00:00 +0000 UTC): /tutorials/configure/pet-photographer
WARN  Last update more than 6 months ago (2022-10-04 00:00:00 +0000 UTC): /tutorials/get-started/blink-an-led
WARN  Last update more than 6 months ago (2023-03-30 00:00:00 +0000 UTC): …
```
> Print pages with last update more than 6 months ago

- docs/architecture/viam-micro-server.md
- docs/get-started/_index.md
- docs/get-started/collect-data.md
- docs/get-started/control-motor.md
- docs/get-started/detect-people.md
- docs/installation/viam-micro-server-dev.md
https://docs-test.viam.dev/3518/get-started/
> Shorten learn about viam page

- docs/components/camera/transform.md
* document attribute as Michael Lee described
> DOCS-2970: Document angle_deg attribute in rotate pipeline of transform camera

- docs/appendix/troubleshooting.md
- layouts/partials/footer.html
* add status info in footer and troubleshooting
@npentrel I'm not sure if this is exactly how you wanted it to be done so just lmk if it needs to be changed and I can change it
> DOCS-2978: Basic automated status page

- docs/how-tos/collect-sensor-data.md
- docs/how-tos/configure.md
- docs/how-tos/create-module.md
- docs/how-tos/deploy-ml.md
- docs/how-tos/detect-color.md
- docs/how-tos/drive-rover.md
- docs/how-tos/image-data.md
- docs/how-tos/navigate.md
- docs/how-tos/sensor-module.md
- docs/how-tos/trigger-sync.md
* added wherever I found appropriate
> DOCS-3002: Add instructions for physically connecting components to how-tos

- .gitignore
- assets/js/index.js
- assets/js/search-results.js
- assets/scss/_styles_project.scss
- docs/search/_index.md
- docsearch.json
- layouts/docs/search.html
> Search dropdown improvements

- docs/cloud/machines.md
- docs/how-tos/sensor-module.md
- docs/registry/advanced/create-subtype.md
- docs/tutorials/configure/build-a-mock-robot.md
- docs/tutorials/control/flutter-app.md
- docs/tutorials/get-started/blink-an-led.md
- docs/tutorials/get-started/servo-mousemover.md
- docs/tutorials/services/accessing-and-moving-robot-arm.md
- docs/tutorials/services/color-detection-scuttle.md
This has been bothering me for a while. Our sample code is not actually boilerplate code ([wiki definition](https://en.wikipedia.org/wiki/Boilerplate_code)).
> Remove boilerplate word

- docs/tutorials/configure/configure-rover.md
- docs/tutorials/configure/pet-photographer.md
- docs/tutorials/control/air-quality-fleet.md
- docs/tutorials/custom/custom-base-dog.md
- docs/tutorials/get-started/blink-an-led.md
- docs/tutorials/projects/make-a-plant-watering-robot.md
- docs/tutorials/projects/verification-system.md
- docs/tutorials/services/navigate-with-rover-base.md
- docs/tutorials/services/visualize-data-grafana.md
- docs/tutorials/services/webcam-line-follower-robot.md
* most of these already included instructions!
> DOCS-3004: Add prereqs to tutorials

- docs/_index.md
> Shorten sentences

- docs/how-tos/sensor-data-visualize.md
- docs/tutorials/services/visualize-data-grafana.md
> Add new grafana video

- .github/workflows/sdk_protos_map.csv
- static/include/app/apis/generated/data.md
- static/include/components/apis/generated/motor-table.md
- static/include/components/apis/generated/motor.md
- static/include/components/apis/generated/sensor-table.md
- static/include/components/apis/generated/sensor.md
- static/include/components/apis/generated/servo-table.md
- static/include/components/apis/generated/servo.md
> Update generated code snippets

- assets/scss/_styles_project.scss
- docs/_index.md
> Update top area of the landing page

- docs/how-tos/collect-data.md
- docs/how-tos/control-motor.md
- docs/how-tos/detect-color.md
- docs/how-tos/detect-people.md
I think these are the right former quickstarts? I checked the how-tos that were moved in the [new front page PR](https://github.com/viamrobotics/docs/commit/980f53b99841d8b3ade08a913a39f5b7ab1aa8f8#diff-ba86e80f5b7483551756f2e4c925571f360b5f945b0abe41b3f42ab3c1994863). Please LMK if I am mistaken.
> DOCS-3001: Add physical assembly instructions to quickstarts from learn about viam

- docs/components/arm/lite6.md
- docs/components/arm/xarm6.md
- docs/components/arm/xarm7.md
* add set_speed and set_acceleration
> DOCS-2972: Add DoCommand methods for xArms

- docs/how-tos/image-data.md
* "Add new model" not mentioned elsewhere
* scanned for images and didn't find any
> DOCS-3020: Update text from app on mlmodel configuration pane 

- docs/services/data/capture-sync.md
* add new attribute to data capture
> DOCS-2673: Add data retention policy option

- docs/services/data/_index.md
> Update _index.md fix title capitalization

- docs/registry/training-scripts.md
> Update training-scripts.md fix title capitalization

- static/include/components/apis/generated/gantry.md
- static/include/components/apis/generated/generic_component.md
- static/include/components/apis/generated/gripper.md
- static/include/components/apis/generated/input_controller.md
.* mostly small fixups and a couple issues mostly on input controller
> DOCS-2950: Fix gripper-input controller component pages 

- test-scripts/test-go/test-gripper-controller.go
- test-scripts/test-gripper-controller.py
> Add test scripts for gripper-controller

- docs/appendix/troubleshooting.md
- docs/architecture/viam-server.md
- docs/configure/_index.md
- https://docs-test.viam.dev/3661/architecture/viam-server/#debugging
- https://docs-test.viam.dev/3661/configure/#components
- https://docs-test.viam.dev/3661/appendix/troubleshooting/
> Add Debug log info

- docs/services/data/_index.md
> Update _index.md quick fix

- docs/configure/_index.md
My understanding is that this works for any resource, not just components
> Add log config for services

- docs/how-tos/train-deploy-ml.md
* make expander with tips and tricks from khari/tahiya blogs and dan masi
> DOCS-2547: Make expander with tips for train deploy ml guide

- docs/architecture/viam-server.md
@cheukt could you confirm these details are correct? 
@hexbabe I should've probably asked before putting this up but why did you need to know this and is this something we think users will actually need to know?
> DOCS-3177: Clarify reconfiguration details

- docs/tutorials/projects/make-a-plant-watering-robot.md
Ignore failing htmltest, unrelated
> DOCS-3254: Update make-a-plant-watering-robot

- docs/data-ai/ai/act.md
- docs/data-ai/ai/advanced/upload-external-data.md
- docs/data-ai/ai/create-dataset.md
- docs/data-ai/capture-data/advanced/how-sync-works.md
- docs/data-ai/capture-data/capture-sync.md
> v3.0 edits apply feedback

- docs/dev/reference/apis/data-client.md
- docs/dev/reference/apis/services/motion.md
- docs/dev/tools/cli.md
* flags are different for each
> DOCS-3273: Split out data export into data export binary and data export tabular

- static/include/app/apis/generated/data_sync.md
- tested 
- added datetime import
> DOCS-3233: Change tabular data example to be movement sensor

- .github/workflows/sdk_protos_map.csv
- static/include/services/apis/generated/vision.md
So I can link back to it from Flutter SDK
> Add vision service get properties to CSV

- docs/data-ai/capture-data/capture-sync.md
- change linktitle and title to be the same
- fix typo
> Update capture-sync.md quick feedback

- docs/data-ai/reference/data-management-client.md
* realized this was missing and should probably be here
> Add data management client to data-ai reference section

- assets/scss/_styles_project.scss
Compare the list in docs.viam.com/tutorials/control/flutter-app/ to https://678f72b359a4730008e16fa5--viam-docs.netlify.app/tutorials/control/flutter-app/ to see the difference
> DOCS-1742: Fix CSS for lists

- docs/data-ai/ai/deploy.md
- docs/data-ai/capture-data/capture-sync.md
- docs/dev/_index.md
- docs/dev/reference/apis/components/_index.md
- docs/dev/reference/apis/services/_index.md
- docs/dev/reference/contributing.md
- docs/dev/reference/sdks/cpp.md
- docs/dev/reference/sdks/flutter.md
- docs/dev/reference/sdks/go.md
- docs/dev/reference/sdks/python/_index.md
- docs/dev/reference/sdks/typescript.md
- docs/dev/reference/try-viam/_index.md
- docs/dev/tools/tutorials.md
- docs/manage/_index.md
- docs/manage/fleet/provision/setup.md
- docs/manage/troubleshoot/alert.md
- docs/manage/troubleshoot/teleoperate/default-interface.md
- docs/operate/reference/architecture/machine-to-machine-comms.md
- docs/operate/reference/services/vision/color_detector.md
- docs/operate/reference/viam-micro-server/_index.md
- netlify.toml
- package-lock.json
https://app.netlify.com/sites/viam-docs/deploys/678f9d49ddec9000074ede08 shows missing link aliases
> Fix missing link forwarding

- docs/data-ai/data/visualize.md
* explicitly refer to it as dashboard so ai chatbot knows and can refer it over grafana
> DOCS-3428: Surface teleop dashboarding functionality

- docs/data-ai/reference/mlmodel-design.md
> DOCS-3453: Add error to troubleshooting

- docs/dev/reference/glossary/board.md
Made chatbot think it's supported
> DOCS-3441: Remove mention of Arduino from glossary

- assets/js/models.js
- assets/js/tutorials.js
> Remove baseurl

- docs/data-ai/ai/train-tflite.md
Questioned this sentence and I can't really back it up so changing to more of our customer stories
> DOCS-3423: Update train-tflite.md feedback from tahiya

- layouts/partials/scripts.html
- static/js/embed.js
Reverts viamrobotics/docs#3946
> Revert "Update how embed.js is loaded"

- docs/operate/get-started/other-hardware/_index.md
> Add additional module implicit dependencies module

- docs/data-ai/_index.md
Feedback from devin-- write more things you can use data for/different user stories than the main one we are telling.
> DOCS-3423: Update _index.md feedback from devin

- docs/data-ai/ai/deploy.md
* hopefully this helps-- will retest once synced
> DOCS-3531: Make phrasing more clear on versioning ml models

- docs/dev/tools/cli.md
* also added modules bc I thought that could also be useful for AI
> DOCS-3525: Add clarifying sentence for AI

- static/include/app/apis/generated/data.md
- static/include/components/apis/generated/camera.md
- static/include/services/apis/generated/vision.md
> DOCS-3560: Run automation on data, camera, vision

- docs/operate/get-started/supported-hardware/_index.md
Adding another column to specify
Removing Xs since visually this is easier to parse
> DOCS-3502: Address Micro-RDK table feedback

- .github/workflows/update_sdk_methods.py
- static/include/components/apis/generated/camera.md
- static/include/components/apis/overrides/methods/python.camera.get_image.after.md
* to be done upstream as well 
* make mime_type optional since erroneously marked required
* tested
> DOCS-3284: Add a basic python example to get_image

- docs/operate/get-started/setup.md
> DOCS-3591: Where do i type a name and click add machine?

- docs/manage/software/deploy-software.md
- docs/manage/software/update-software.md
https://deploy-preview-4032--viam-docs.netlify.app/manage/software/update-software/#update-the-software-version
https://deploy-preview-4032--viam-docs.netlify.app/manage/software/deploy-software/#set-the-version-and-update-strategy
> Add callouts for maintenance windows for config changes

- .github/workflows/sdk_protos_map.csv
- .github/workflows/update_sdk_methods.py
- docs/dev/reference/apis/_index.md
- docs/dev/reference/apis/components/button.md
- docs/dev/reference/apis/components/sensor.md
- docs/dev/reference/apis/components/servo.md
- docs/dev/reference/apis/components/switch.md
- docs/operate/get-started/supported-hardware/_index.md
- docs/operate/get-started/supported-hardware/button.md
- docs/operate/get-started/supported-hardware/switch.md
- docs/operate/reference/components/button/_index.md
- docs/operate/reference/components/switch/_index.md
- static/include/components/apis/generated/button-table.md
- static/include/components/apis/generated/button.md
- static/include/components/apis/generated/switch-table.md
- static/include/components/apis/generated/switch.md
- static/include/components/apis/overrides/protos/button.Close.md
- static/include/components/apis/overrides/protos/button.DoCommand.md
- static/include/components/apis/overrides/protos/button.Push.md
- static/include/components/apis/overrides/protos/switch.Close.md
- static/include/components/apis/overrides/protos/switch.DoCommand.md
- static/include/components/apis/overrides/protos/switch.GetNumberOfPositions.md
- static/include/components/apis/overrides/protos/switch.GetPosition.md
- static/include/components/apis/overrides/protos/switch.SetPosition.md
SME reviewer: Main question is whether the descriptions of the components and APIs are good or should have more details/different wording. Most of the rest of this PR is just autogeneration.
> DOCS-3490: Add Button and Switch resource APIs

- docs/operate/get-started/other-hardware/_index.md
- docs/operate/get-started/other-hardware/hello-world-module.md
Ran through Python steps to test this; it works.
> DOCS-3600: Move generated Python module definition out of main.py

- docs/manage/fleet/reuse-configuration.md
- docs/manage/software/update-software.md
Update a fragment: https://deploy-preview-4055--viam-docs.netlify.app/manage/fleet/reuse-configuration/#update-a-fragment
Update software: https://deploy-preview-4055--viam-docs.netlify.app/manage/software/update-software/
> DOCS-3651: Add versions and tags for fragments

- docs/dev/tools/cli.md
Also fixing some styling issues
> DOCS-3429: Add viam machines part list

- docs/dev/reference/apis/sessions.md
All tested and confirmed working
> DOCS-3556: Increase timeout for sessions

- docs/operate/reference/components/base/_index.md
- Board isn't actually part of the base as such
- Doesn't move all components
> DOCS-3194: Fix base description

- docs/dev/reference/sdks/_index.md
- docs/dev/reference/sdks/connectivity.md
@njooma According to the wiki C++ should support mDNS, however I was not able to connect over a local network with C++. Is the wiki wrong or am I missing something for C++? Thanks!
> DOCS-3469: Cover mDNS for local connections

- docs/operate/reference/module-configuration.md
@benjirewis to double check--this is there for local modules too right?
> DOCS-3637: Add VIAM_MODULE_STARTUP_TIMEOUT env variable

- docs/dev/reference/changelog.md
> Fix changelog ordering

- docs/dev/reference/changelog.md
- docs/tutorials/projects/helmet.md
@njooma Is there a recency limit to Python versions we support fully? Also, someone in the ai bot wondered whether there's a recommended best Python version for working with Viam. Is there one?
> DOCS-3692: Note that we support recent Python versions

- docs/dev/reference/try-viam/rover-resources/rover-tutorial/_index.md
- docs/dev/reference/try-viam/rover-resources/rover-tutorial/jetson-rover-setup.md
- static/include/services/apis/generated/data_manager.md
- static/include/services/apis/overrides/protos/data_manager.Sync.md
> Fix alert colors

- docs/tutorials/services/navigate-with-rover-base.md
Originally was making AI bot changes but turns out it's more complicated so reverting those changes and just fixing the massive images since I'd already done that
> Shrink massive images on nav tutorial

- docs/operate/get-started/other-hardware/_index.md
- docs/operate/get-started/other-hardware/hello-world-module.md
> DOCS-3633: Update module docs for new generated structure

- assets/scss/_styles_project.scss
- docs/manage/fleet/provision/setup.md
Hey @ale7714, we got this question about re-provisioning. Could you confirm that what I wrote here aligns with your understanding of how it works?
> DOCS-3755: Add info about reprovisioning

- assets/scss/_sidebar-tree.scss
- assets/scss/_styles_project.scss
- layouts/docs/baseof.html
- layouts/docs/content.html
- layouts/docs/landing.html
- layouts/partials/footer.html
- layouts/partials/sidebar-tree.html
Reverts viamrobotics/docs#4145
> Revert "DOCS-3737: Move TOC"

- docs/operate/get-started/other-hardware/_index.md
Adding to top of procedure so it doesn't break step numbering
> DOCS-3772: Add details to AlwaysRebuild

- docs/operate/get-started/setup-micro.md
- docs/operate/get-started/setup.md
Answer an AI chatbot question (since the bot doesn't have the ability to read the app content)
Also incorporate a lil more explanation of why we're sending them off to the app for setup
> DOCS-3867: Add OS details to micro setup instructions

- docs/manage/fleet/provision/setup.md
- docs/manage/reference/viam-agent/_index.md
- docs/manage/reference/viam-agent/manage-viam-agent.md
- docs/manage/troubleshoot/troubleshoot.md
- docs/operate/get-started/other-hardware/micro-module.md
- docs/operate/reference/viam-server/manage-viam-server.md
This was causing confusion with the configuration file
> DOCS-3753: Clarify machine cloud credentials

- docs/operate/get-started/other-hardware/micro-module.md
Merge after https://viam.atlassian.net/browse/RSDK-10125 is released
> DOCS-3664: Update docs for handle HTTP redirection in micro OTA

- docs/dev/tools/common-errors.md
Including hidden content here due to a related AI question, so that AI can pick it up even though there's not currently a great place to add it in the docs.
> DOCS-3871: Add camera streaming info

- assets/js/inkeep.js
change 'Please do not to share sensitive information' -> 'Please do not share sensitive information'
> minor copy edit in inkeep prompt

- static/include/app/apis/generated/app.md
- static/include/app/apis/overrides/protos/app.UpdateOrganizationMetadata.md
- static/include/app/apis/overrides/protos/app.UpdateRobotMetadata.md
- static/include/app/apis/overrides/protos/app.UpdateRobotPartMetadata.md
We don't usually put billing info in but this is an odd one that may be surprising to people.
> DOCS-3665: Add billing information for adding metadata

- docs/operate/reference/components/camera/webcam.md
A chatbot answer was wrong, and I think it should actually be this, based on https://github.com/viam-modules/csi-camera?tab=readme-ov-file
> DOCS-4000: Fix CSI camera note

- docs/operate/get-started/other-hardware/manage-modules.md
> Copy edit ('darin' -> 'darwin')

- config.toml
https://viaminc.slack.com/archives/C055G9S1W3Y/p1747988394582899
> Update config.toml Hugo version

- docs/dev/reference/sdks/docommand.md
Try to get bot to pick up the Python version and land on this page
> DOCS-4026: Update docommand.md

- docs/operate/get-started/other-hardware/dependencies.md
Follow on to comment here https://github.com/viamrobotics/docs/pull/4347
> Add optional vs required dependency order detail

- docs/operate/get-started/other-hardware/manage-modules.md
Fixing strange commas from recent PR
> Update manage-modules.md nits

- docs/operate/get-started/other-hardware/manage-modules.md
Relevant Slack thread: https://viaminc.slack.com/archives/C081S6K8BS4/p1748544886894729
> Tweak Intel Mac in cloud build table

- docs/operate/get-started/other-hardware/module-configuration.md
> Add missing \ to VIAM_HOME Windows path

- docs/manage/manage/white-labelled-billing.md
[ticket](https://viam.atlassian.net/browse/APP-8347)
This PR simply updates our docs to also mention/define the "cost_per_year" attribute in billing fragments where "cost_per_month" already is.
> APP-8347: Define "cost_per_year"

- docs/operate/get-started/other-hardware/manage-modules.md
Do you think this is helpful? They would've already done this when they first published the module anyway so LMK if this feels like a fix
> DOCS-4149: Add explicitness to module update step

- .github/workflows/test-code-snippets-python.yml
> Check test architecture

- docs/dev/reference/apis/fleet.md
- docs/dev/reference/apis/ml-training-client.md
> Update support notices

- static/include/services/apis/generated/navigation.md
- static/include/services/apis/overrides/methods/go.navigation.AddWaypoint.point.md
- **DOCS-3897: Fix add waypoint param description**
- **DOCS-3897: Follow up**
> DOCS 3897: Follow up
