viamrobotics/docs

docs/tutorials/data-management-tutorial.md
Looks like a typo: "With data capture enabled, you can now configure data capture" -> "With data management enabled, you can now configure data capture"
=> Fix typo in data-management-tutorial.md

docs/components/arm/_index.md
Noticed some odd formatting/old naming conventions and tried to make it better. Did not review this whole doc just a quick fix.
=> Fix arm component intro nits

docs/components/board.md
this should soon be refactored anyways but thought i'd fix for now!
* change SPI bus to I2C bus (assume was copy/pasted)
* add code styling to values
=> fix mislabel in i2c configuration

assets/scss/_styles_project.scss, docs/installation/_index.md
This way we won't have to manually add a `<br>` at the top of every tab.
Before:
After:
=> Add padding to top of tabbed content

docs/program/SDK-as-client.md
* go get is deprecated
* see https://viam.atlassian.net/browse/RSDK-2601, also tested
=> DOCS-650: change go install command

docs/components/motor/dmc4000.md
We don't have this newline in most instances.
=> Make DMC frontmatter consistent

docs/program/extend/modular-resources/add-rplidar-module.md, docs/services/slam/_index.md, docs/services/slam/run-slam-cartographer.md
* Fixed issue on linux tabs
* macOS needs SME validation, this is what I found when I tested on MacOS
=> DOCS-673: fix executable path in SLAM docs

docs/installation/prepare/jetson-agx-orin-setup.md
The docs didn't quite match up with the Jetson Orin on my desk:
- Pins 3 and 5 are I2C bus 7, as shown by plugging something into those pins and running `i2cdetect -y -a -r 7`
- Pins 27 and 28 are I2C bus 1, as shown by an analogous check.
- I did _not_ swap the I2C `jetson-io.py` IDs, since they look correct (based on running `jetson-io.py` myself).
- The SPI bus is number 0, as found by reading from an ADC plugged into it. I'm happy to share my config if you want; setting this up is more complicated than I'd prefer.
- Things in the `/dev` column should start with slashes, to show that they're absolute paths.
- I changed the device names to the nearest things that actually exist in `/dev`. Are those the right devices? I'm unsure; our code doesn't interact with them directly. but they're …
=> fix typos in Jetson Orin documentation

docs/tutorials/projects/send-security-photo.md
- install link was empty, quickfix
=> DOCS-687: add link to security detector tutorial

docs/components/motor/28byj48.md, docs/components/motor/_index.md, docs/components/motor/tmc5072.md
* another, smaller alignment pr to standardize links w/ title names on motor page
* typo model name fixes
=> DOCS-480: standardize links with title names motor

docs/components/camera/align-color-depth-extrinsics.md, docs/components/camera/align-color-depth-homography.md, docs/components/camera/calibrate.md, docs/components/camera/dual-stream.md, docs/components/camera/fake.md, docs/components/camera/ffmpeg.md, docs/components/camera/image-file.md, docs/components/camera/join-color-depth.md, docs/components/camera/join-pointclouds.md, docs/components/camera/rtsp.md, docs/components/camera/single-stream.md, docs/components/camera/transform.md, docs/components/camera/velodyne.md, docs/components/camera/webcam.md
* align titles as names-- align & join look ugly but I think it still helps for quick reference alongside ui 
* make required attributes bold vs. all italics, and put on top of table
* <br> defaults> 
* Configuration `name` for JSON when referencing another component
=> DOCS-480: align cameras with other components

docs/components/movement-sensor/_index.md
This https://viam.atlassian.net/browse/RSDK-2634 got fixed so now we have a better link to link to
=> Link to fixed properties link from movement sensor API

docs/services/slam/cartographer/_index.md
- all the other service tabs are capitalized
=> change cartographer capitalization in linkTitle

docs/services/slam/cartographer/_index.md
Ticket: https://viam.atlassian.net/browse/RSDK-2910
Problem:
* The slam tutorial had instructions to have `"sensors": ["rplidar"]`, whereas in the rplidar tutorial we're telling the user to pick a name of their choice. 
* This can easily lead to slam not working if the user named their rplidar component anything else except for `"rplidar"`
Solution:
* Indicate to the user that they have to refer to their rplidar component name by changing the `"sensors"` reference to: `"sensors": ["<YOUR_RPLIDAR_COMPONENT_NAME>"]`
=> Change rplidar component name in slam tutorial

docs/manage/configuration.md
Adding one line for Auth after all - I think that's better than leaving it out in case someone stumbles on it
=> DOCS-122: Add Auth/Network section

docs/program/extend/modular-resources/examples/add-rplidar-module.md
- update “A Rplidar” to “An RPlidar” to match the rest of the document
=> fix caps on rplidar title and linktitle 

docs/components/motor/gpio/encoded-motor.md
- quick win
- changed attributes format & clarified model specification
- changed description of ticks_per_rotation attribute to make meaning of rpm control / rate specification clearer
=> DOCS-491: add clarification for ticks_per_rotation and change attributes on encoded motor

docs/program/extend/modular-resources/examples/add-rplidar-module.md
While QA'ing for SLAM, I noticed it might be confusing why there is no sub-tab to set the attributes / device_path for an rplidar on Linux. I added a note saying it's not needed on Linux.
=> RSDK-2847 State that attributes not needed for rplidar on Linux

docs/components/arm/_index.md, docs/components/base/_index.md, docs/components/camera/_index.md, docs/components/gantry/_index.md, docs/components/gripper/_index.md, docs/components/input-controller/_index.md, docs/components/motor/_index.md, docs/components/movement-sensor/_index.md, docs/components/sensor/_index.md, docs/components/servo.md
- subtask of DOCS-480 alignment
- remove full code samples in favor of directing to code sample tab 
- standardize component names
- standardize code samples
=> DOCS-697: align code sample instructions

docs/components/arm/eva.md, docs/components/arm/fake.md, docs/components/arm/yahboom-dofbot.md, docs/components/board/beaglebone.md
Fixed a few more JSON quote mismatches. VSCode Regex: `"[A-Za-z0-9]*": "<[A-Za-z0-9_-]*"`
=> Fix a few more JSON misquotes

docs/_index.md
The other cards on this page aren't clickable but rather include body text links, so it seems like the Community one should be the same.
=> Align Community landing page card with other cards

docs/appendix/glossary/client-application.md, docs/installation/_index.md, docs/installation/prepare/rpi-setup.md, docs/installation/update/_index.md, docs/internals/robot-to-robot-comms.md, docs/program/SDK-as-client.md, docs/try-viam/_index.md, docs/try-viam/rover-resources/_index.md, docs/try-viam/rover-resources/rover-tutorial.md, docs/tutorials/get-started/servo-mousemover.md, docs/tutorials/projects/integrating-viam-with-openai.md, static/include/try-viam/create-a-reservation.md
Small tweaks to low-hanging fruit where discussion or further consideration is unlikely to be necessary. Kept most changes to within onboarding sections -- Viam in 3 Minutes, Try Viam, and the Installation Guide -- but my monospace efforts for `viam-server` ended up being corpus wide 😅 .
Happy for any corrections if I did something wrong -- thanks!!
=> DOCS-716 asses onboarding docs + extra nits

docs/appendix/glossary/resource.md
software services and hardware components are analogous so should be formatted the same way
=> Make resource.md formatting uniform

.htmltest.yml
* another external one that keeps timing out and making the test fail
=> htmltest ignore slamtec link 

docs/components/base/_index.md, docs/components/board/_index.md, docs/components/component/_index.md, docs/components/encoder/_index.md, docs/components/gantry/_index.md, docs/components/input-controller/_index.md, docs/components/motor/_index.md, docs/components/sensor/_index.md, docs/components/servo/_index.md
* change `Context` to `ctx`
* remove naming from `error` 
(Match RDK specs)
=> DOCS-733: make context and error typing consistent

docs/components/arm/_index.md
- Replaced obsolete community slack link with community discord link.
=> Replace slack link with discord

docs/services/slam/cartographer/_index.md
We realized if [full modularization](https://viam.atlassian.net/browse/RSDK-2210) finishes before [cloud story](https://viam.atlassian.net/browse/RSDK-2262), we’ll temporarily not be able to support offline slam for customers (because we’ll only support offline with a replay camera, and only support a replay camera in the cloud).
We're taking offline mode out of the public docs so no one new starts depending on it until we can support it in the cloud again.
Has to be merged after https://github.com/viamrobotics/slam/pull/193 is merged, a new version of the slam repo is tagged, the viam-cartographer repo is updated to import the new version of the slam repo, and a new stable version of viam-cartographer is tagged.
=> RSDK-2961 Remove offline mode from slam public documentation

docs/tutorials/services/accessing-and-moving-robot-arm.md
- Move image up
- Take arm spec out of note because the fake part is just as important, and because the full tutorial code link is kind of a separate thought, but having 3 different alerts is a lot.
- Caps nit
=> Fix nits on accessing-and-moving-robot-arm.md

docs/services/slam/cartographer/_index.md
This extra bit should have also been removed as part of https://github.com/viamrobotics/docs/commit/6083fbe6f5faf8eebf5bedc04b2b6dbd5af7b7d6
=> RSDK-2961 Also remove troubleshooting note for dataset mode

docs/_index.md, docs/components/board/_index.md, docs/components/board/pi.md
* Add as an image to board carousel
* Add to board documentation where supported models of RPI are mentioned
=> DOCS-784: Add Raspberry Pi 3 to carousel & board docs

docs/try-viam/rover-resources/rover-tutorial-fragments.md
This is a weird case and I don't want users thinking that enable pins typically equate to PWM pins.
=> Add note about ENA and ENB not being enable pins

.github/vale/styles/Viam/SentenceLength.yml
As singular value, we must provide token as plain string, not a list of strings.
=> SentenceLength Vale action tweak 2

.github/vale/styles/Viam/Spacing.yml
Because this blocks merging on some things like Resource.name
=> Make spacing lint rule warning not error

docs/program/sdks/_index.md
In this case, "remote" is used generally, not in the Viam-specific way. Open to suggestions for how to reword this, but in the meantime taking this definition off here is important.
=> Fix different use of "remote"

.gitignore
This dir managed as a `git submodule` instead, should be safe to exclude. Testing now (and with `make purge`)
=> Ignore themes dir

Makefile
Now properly clearing docsy theme content without touching parent folder. Together with recent .gitignore change, this seems to restore expected git status output for both post-purge, and after next site build.
Wonky double `themes` `rm` call is due to `rm` complaining about `.` and `..`, which, obviously, should not be removed ;). I could have used something like `2 > /dev/null` to ignore, but this avoids the warning altogether, and is a bit more explicit about our deletions; always good.
=> Tweak purge

docs/_index.md
* Realized this needed to match with official capitalization/product name 😆
=> update BeagleBone labeling to match official

docs/components/encoder/_index.md
`GetPosition` and `GetProperties` in the golang SDK were recently changed to be more in line with other component methods for the golang SDK, I changed where I could find them in the docs. Feel free to add anyone else to this pull request.
=> Change GetPosition to Position

assets/scss/_styles_project.scss
For TOC entries only: override existing blue monospace code coloring to use same coloring as non-`a` elements.
Two entries:
- `.td-toc #TableOfContents ul li li a > code` for H3s
- `.td-toc #TableOfContents ul li a > code` for H2s
Staging Links:
- Example with H3s: [SLAM Cartographer](https://docs-test.viam.dev/7dad8d5578c8500b9ec7bcccf0ec90ff78c893bd/public/services/slam/cartographer/#adjust-data_dir)
- Example with H2s: [Vision Segmentation](https://docs-test.viam.dev/7dad8d5578c8500b9ec7bcccf0ec90ff78c893bd/public/services/vision/segmentation/#configure-a-radius_clustering_segmenter)
=> DOCS-810 remove blue from monospace toc entries

.htmltest.yml
Link: https://www.softroboticsinc.com/products/mgrip-modular-gripping-solution-for-food-automation/
404s on their end, I reported to them, but for now we omit from htmltest.
Discovered in https://github.com/viamrobotics/docs/pull/1393
=> Exclude softroboticsinc from htmltest

config.toml, docs/program/sdks/_index.md
Add Flutter SDK to SDK dropdown and programs page.
NOTE: Prism.js has no Flutter syntax highlighting option, so re-using `cpp`, as Flutter is written in C++ and the highlighting looks acceptable. LMK if anyone disagrees!
=> DOCS-853: Add Flutter SDK

docs/_index.md
Consider some alternate options to how we introduce our Welcome page.
Staged options to choose from:
- [Absolute basic](https://docs-test.viam.dev/438c5ec82347f0e731417b7295117700e9182672/public/index.html)
- Swapped title to first sentence, and trimmed title to absolute minimal.
- [Absolute basic, with text separator](https://docs-test.viam.dev/93439c77e90d2553e45e10edf2c92f6752d03a6c/public/index.html)
- Same as above, but with single intro sentence between two image sections.
- [Two more carousels](https://docs-test.viam.dev/e66668c9d417e75a4a871134273097d539e9c7a2/public/index.html)
- Added image carousels for components and services, and swapped board to be below getting started tiles.
Questions for team:
- Do we find additional carousels useful? Is the single sentence text intro to …
=> DOCS-839: Explore welcome page intro

docs/services/motion/_index.md
- Adding "Obstacles are defined by a pose and a geometry with dimensions. The pose location is the point at the center of the geometry." because nowhere else in our docs is it specified that dimensioned geometries are centered on their pose points, as opposed to extending (per their dimensions) from the point, with the point being at one corner of the geometry.
- An obstacle is a geometry (whereas not all geometries are obstacles), so I changed those to be more clear.
- Realized one of the changes to the Python tab hadn't been carried into the Go tab, so changed that.
=> Clarify Motion Service obstacle location definition

docs/services/motion/_index.md
* Document new method for using motion planning with a slam map/service, `MoveOnMap`
* Change motion service name on robot to "your_motion_service" from "builtin" across doc
=> DOCS-643: Add documentation on new MoveOnMap method to Motion API

docs/tutorials/services/plan-motion-with-arm-gripper.md
Make consistent between the Python and Go tabs, and with the description.
=> Fix motion planning tutorial table dimensions

docs/components/base/_index.md, docs/services/frame-system/_index.md
Clarify base API coordinate system.
Remove note in frame system doc because the frame system has no inherent "forward" etc.; it's all relative and user-defined.
=> DOCS-845: Clarify coordinate system definitions

docs/program/extend/modular-resources/_index.md, docs/services/slam/cartographer/_index.md
In discussion to https://viam.atlassian.net/browse/DOCS-851, Tess mentioned that viam-cartographer should be described as a modular resource, not an integrated library.
Question:
- Does the same apply to [ORB-SLAM3](https://docs-test.viam.dev/2e25d1f27d016afc5861925853fa7739b9725542/public/services/slam/orbslamv3/), (currently a draft doc, not public, just getting ahead of future questions, thanks!)
=> DOCS-859: Clarify viam-cartographer as modular resource

docs/components/camera/_index.md
* Document the use case for the RawImage helper function `bytes_to_depth_array`: converting images of `viam.dep` MIME type to a standard image representation 
* Document a code snippet to show conversion to standard image data
NOTE: re. ticket this functionality will eventually be added to all SDKs
=> DOCS-760: Document Get_image helper function bytes_to_depth_array on Camera API 

docs/services/motion/constraints.md
Fix the Python stuff because it's currently broken, and add link. Go will come in another PR.
=> Fix motion constraints syntax

docs/tutorials/get-started/make-an-led-blink-with-a-raspberry-pi-and-sdk.md, docs/tutorials/get-started/make-an-led-blink-with-the-viam-app.md, docs/tutorials/get-started/try-viam-sdk.md
This hardware URL list is vestigial and redundant with the hardware reqs at the top of the tutorial, and I wanted to put a card on here to make it more like the next steps format on many of our tutes and other pages.
The Discord link is redundant with the one that autopopulates at the bottom of the page.
=> Clean up links at bottoms of some tutorials

docs/services/motion/_index.md
I think simply adding these links might be a good solution here since trying to add full examples gets overwhelming quickly (to the user, and to maintain). We don't show example obstacles etc., so I realized adding example transforms may also be best left to tutorials and perhaps links to other examples.
=> DOCS-871: Help users understand transform geometries

docs/manage/ml/_index.md, docs/manage/ml/train-model.md, docs/services/ml/_index.md, docs/tutorials/projects/integrating-viam-with-openai.md, docs/tutorials/projects/tipsy.md
Expand ML landing page intro copy with explanatory description and simple example.
- Maybe just a little too much for the Manage section? Remove the cat pictures example?
=> DOCS-815: Expand ML intro copy

docs/components/board/_index.md, docs/extend/custom-components-remotes.md, docs/extend/modular-resources/_index.md, docs/program/apis/_index.md, docs/services/data/_index.md
- Converted a few direct links to glossary to use tooltip shortcode instead.
=> DOCS-901: Convert glossary links to tooltips

docs/components/camera/webcam.md
Small tweak to render only executable, copy-able commands within the code fence, and move interface selections and other instructions out.
=> Move non-commands out of code fence

docs/extend/modular-resources/_index.md
* Apply Alan's feedback for compiling a go module 
* Add code in from the Viam examples repo's [complexmodule module.go](https://github.com/viamrobotics/rdk/blob/a0dec7d74085139fe77a637335ba43640355ca47/examples/customresources/demos/complexmodule/module.go) 
* Try to clear up module execution
=> DOCS-886: Improve Go modular resource code template by adding module with contextual main

docs/tutorials/services/try-viam-color-detection.md
Quickfix from DOCS-911: 
* Change attribute name to button to reflect UI dropdown menu change-- now auto populates **Color Detector** instead of using `color_detector` which could introduce confusion
=> Fix dropdown menu code to button name in try color detection tutorial

docs/components/camera/transform.md
Add missing colon noticed while troubleshooting (unrelated) App transform camera error. Also standardizing whitespace.
=> Add missing colon

docs/program/use-extra-params.md
* Switch "utilize" and "define" use cases
* Change wording to make this more clear that this is meant to be used by users who implement modular components (later on should go with broader changes when registry is ready) 
* Hide "utilize" code steps in expand
=> DOCS-878: Apply Matt Vella's feedback to extra params

docs/tutorials/get-started/try-viam-sdk.md
This is an entry-level tutorial and we don't define SDK here.
=> Add SDK definition to drive rover tutorial

docs/tutorials/configure/scuttlebot.md
The current title makes it sound as though you're adding a camera to an already configured SCUTTLE. Basically all SCUTTLEs have cameras so I think it's better to take this off.
=> Shorten SCUTTLE tutorial title

docs/components/base/_index.md, docs/program/apis/_index.md
Implements the third segment of the changes outlined here: [Docs Changes for GPS Navigation](https://docs.google.com/document/d/1ReL7RU0FoaAe8gyPbMgMovHpgdx3Jy4c3R0LFCVWkKI/edit) (section below "Changes to https://docs.viam.com/components/base/")
* Add the GetProperties() method with small code samples, add info for navigation service usage
=> DOCS-942: Add documentation for GetProperties() to base component

docs/services/navigation/_index.md
A newline in the row caused this table to appear a little funky in production, this pr fixes that newline
=> Fix motion attribute formatting on navigation service 

docs/components/camera/_index.md
The camera API varies much more widely between languages than most of the APIs. I think we should address that in some way. I'm not sure whether this is the way--very open to other ideas but had a thought and wanted to make a suggestion!
I'll make a ticket to discuss.
=> DOCS-946: Deal with camera SDK differences

docs/services/slam/cartographer/_index.md
[Ticket](https://viam.atlassian.net/browse/RSDK-3550)
Follow up to https://github.com/viamrobotics/docs/pull/1521
In the original PR,, I didn't realize that the cartographer-module docs referred to the old data_dir contents. 
This removes references to the data_dir contents which no longer exist in the stable version of cartographer-module
Update “sensors list may not be empty“ (as per description )
=> RSDK-3550-cartographer-full-mod2

docs/note.md, layouts/shortcodes/readfile.html, static/include/sample.md
Fix table rendering in includes by removing wrapping `<div>` elements from `readfile.html`.
- Also using opportunity to expand `note.md` to showcase HTML and MD tables in includes, useful for testing this.
=> DOCS-941: Fix table rendering in includes

docs/extend/modular-resources/examples/_index.md, docs/extend/modular-resources/examples/add-tflite-module.md, docs/extend/modular-resources/examples/tflite-module.md
Add C++ Modular Resource tutorial showcasing example ML module for classifying audio samples using TensorFlow Lite.
Workarounds:
- Using `--appimage-extract-and-run` to workaround lacking FUSE support in our [`bullseye` docker image](https://github.com/viamrobotics/viam-cpp-sdk/tree/main/etc/docker). Also backgrounding `viam-server` because of this.
- Using `VIAMCPPSDK_USE_DYNAMIC_PROTOS=ON` until RSDK-4295 is addressed.
- Supplying `DYLD_LIBRARY_PATH` env var before running `example_audio_classification_client` on macOS until RSDK-1996 is addressed.
Staging:
- [add-tflite-module.md](https://docs-test.viam.dev/b08be992cf0b70cc97a22ef88ed8371f2cd74d5c/public/extend/modular-resources/examples/tflite-module/)
=> DOCS-779: Add C++ ML modular resource tutorial

docs/extend/modular-resources/examples/tflite-module.md
Updates C++ ML Modular Resource tutorial with macOS-specific C++ build workaround to RSDK-1996.
=> DOCS-970: Add DYLD workaround to C++ ML tutorial

docs/manage/CLI.md, docs/manage/data/export.md
changes for docs around CLI, will go in after the [RDK](https://github.com/viamrobotics/rdk/pull/2714) and [app](https://github.com/viamrobotics/app/pull/2115) prs are merged, let me know if they are other places to change
=> RSDK-4286 - CLI consistent flag naming scheme

docs/extend/modular-resources/create/_index.md
From feedback from Michael Lee and Abe -- this error is fairly easy to catch but annoying 
* Update Golang module code sample to raise an unimplemented error for `Properties` so that the sample doesn't error out when the module starts because `Properties` was added to the base API
=> DOCS-763: Update Go SDK module code sample for the addition of `Properties` to base API

docs/extend/modular-resources/create/_index.md
Part of Michael Lee's feedback from DOCS-763
- Used Python SDK's example module to base these updates off of: https://github.com/viamrobotics/viam-python-sdk/tree/main/examples/simple_module so I believe Cheuk or Nicole are the relevant SMEs! 
This fixed @abe-winter 's module while he was working on it in office so is prob good change
=> DOCS-763: Update the out of date Python SDK module code in Extend 

docs/manage/CLI.md, docs/manage/data/export.md, docs/tutorials/services/data-management-tutorial.md
Update Viam CLI tool installations instructions to use new compiled binary executable downloads.
- Retained "Build from Source" as fifth tab: build in Go for any supported platform.
- Using `stable` in place of `latest` in the URL links per discussion.
Question:
- Sending the downloaded binary to `/usr/local/bin/viam`, so requiring `sudo` twice. Same way we have users [download our pre-built modules](https://docs.viam.com/extend/modular-resources/examples/rplidar/#requirements). Look good?
=> DOCS-986: Update Viam CLI installation

docs/appendix/troubleshooting.md
Add brief troubleshooting item addressing `PulseAudio` / `jackd` errors with best effort fix:
- Fix is specific to Linux OS / sound library combo, but included RPI example command to install missing deps for that specific platform / sound library combo.
=> DOCS-948: Add PulseAudio troubleshooting

docs/components/base/_index.md
If you try to move a base at 1mm/s, or 1 deg/sec, not only would that motion theoretically be almost imperceptible to a human, but it won't actually physically work because most motors won't get enough power to break the static friction, so it will stall/not move at all. Changing these to values that would reasonably be expected to work for many hobbyist bases.
Also, I think the Go examples all need "nil" as the extra argument instead of nothing?
=> Fix base API code examples

docs/components/base/_index.md
Since this method is provided through actuator, may make more sense to link to the page that actually shows the stop method
=> Change base stop link

docs/appendix/release-notes.md, docs/extend/modular-resources/examples/tflite-module.md, docs/manage/ml/_index.md, docs/services/ml/_index.md, docs/services/vision/classification.md, docs/services/vision/detection.md, docs/tutorials/projects/guardian.md, docs/tutorials/projects/send-security-photo.md, docs/tutorials/projects/tipsy.md
Also noticed there's not a good reason to tell them to head to the components tab since they might test with existing images and not need to configure a transform camera.
=> Fix classification typo

docs/manage/configuration.md
Adds brief notice of **Duplicate component** and **Trash** buttons in Viam app > Config > Components UI.
- Seems too simple. Is there anywhere else in the docs we talk about configuring components in the app that could use this notice?
- Drive-by alert indentation fix while in here.
=> DOCS-1018: Add duplicate component button

docs/components/movement-sensor/_index.md, docs/components/movement-sensor/cameramono.md
* Taking this model out of RDK as it is being removed 
keeping page with `draft: true` for now in case we want that info in the future for `mono-camera` module? can remove
=> DOCS-1009: Remove `camera_mono` movement sensor experimental model

docs/installation/prepare/jetson-nano-setup.md
* Add different spec for power jack connector for Orin Nano as requested
* Add note about polarity into troubleshooting to make users extra aware 
* Edit instructions to make clear micro-usb powering is a no-go
=> DOCS-1012: Fix power supply notes on Jetson Nano 

docs/components/base/_index.md, docs/components/motor/_index.md, static/include/components/apis/base.md, static/include/components/apis/motor.md
- Add the IsMoving method to the base API documentation
- Change the order of the API for motor so that Stop (which is part of the actuator API) is grouped more logically next to the other actuator API method (IsMoving)
Note to reviewers: The motor index file isn't changing meaningfully; it's just a copy paste order change.
=> DOCS-1015: Add IsMoving to base

docs/manage/fleet/_index.md
The only title case heading on the page
=> Fix caps nit on fleet management

docs/tutorials/control/scuttle-gamepad.md
* Change to amazon link that is less likely to be removed
=> DOCS-1049: Change gamepad link on scuttle tutorial to fix failing test 

docs/components/movement-sensor/_index.md, docs/extend/modular-resources/examples/odrive.md
Sorry if this is a bit out of order, but wanted to get these changes in since they were simple and the readmes were updated:
- Our API contract for angular velocity of movement sensors is degrees/second
- The odrive naming triplet has changed.
cc @jeremyrhyde because I couldn't find your docs ticket.
=> [DOCS-1047][DOCS-DOCS-1053]Odrive Renaming and Movement sensor units

docs/manage/fleet/organizations.md
Add link to Viam App from Fleet > Organizations page, based on Friday's workshop feedback.
=> Add link to Viam App

README.md
As I was setting up this project for the first time, I noticed the link to getting started with Hugo for Windows pointed to the Node.js download site. This PR updates the README to use the expected URL.
=> Update README link to Windows hugo install

docs/extend/modular-resources/create/_index.md
* Sol-eng request: Add in a note gently urging them to use lowercase letters
=> DOCS-1035: Add naming tip for uppercase models bug with module registry

docs/extend/modular-resources/upload/_index.md
- Replace erroneous build step in `update` with fixed step from `create`.
=> Fix update go package step

docs/extend/modular-resources/examples/rplidar.md
Per this thread (https://viaminc.slack.com/archives/C02KFSY4H89/p1693405628296269), we're going to remove the Config Builder tab so that the docs don't have non-working instructions. The docs should be updated again once rplidar-module is uploaded to the modular registry.
=> remove config builder tab from rplidar docs

docs/tutorials/projects/integrating-viam-with-openai.md
Make AI Companion tutorial's left-nav entry title case, to be consistent with other tutorials.
=> Make AI Companion left nav title case

docs/tutorials/projects/guardian.md
"security" is confusing because we have another tutorial called "A Person Detection Security Robot That Sends You Photos" that is actually more about security, whereas this one is more about pet monitoring. So whether this link title is interpreted by people as a guardian to guard your pets, or a cute pet guardian (like a pet rock usage of the word "pet"), this is a better link title.
=> Change Guardian link title

docs/extend/modular-resources/upload/_index.md, docs/manage/CLI.md
Add `--force` flag to CLI reference docs. Not mentioning on `upload` workflow procedural. LMK if you'd like a mention there (we wish to discourage its use, yes?)
[`viam module` Named Arguments](https://docs-test.viam.dev/7372e15f303e7516a92d82a576913a716754ce62/public/manage/cli/#named-arguments-1)
=> DOCS-1058: Add --force flag to CLI

docs/extend/modular-resources/create/_index.md, docs/extend/modular-resources/upload/_index.md
Add guidance on the required form of the `requirements.txt` file when building custom modules (for upload to the Registry).
- Link to this new guidance from `import` steps, for Python example.
Note that this appears to be under consideration for re-evaluation with engineering: See RSDK - 3941.
[Compile the module into an executable](https://docs-test.viam.dev/41b8d4046aa6ff21884a331f5e26fc7d3fc6a790/public/extend/modular-resources/create/#compile-the-module-into-an-executable)
=> DOCS-1051: Add guidance on requirements.txt

docs/extend/modular-resources/examples/tflite-module.md
With recent updates to the C++ SDK, the following are no longer required:
- Explicitly setting `DYLD_LIBRARY_PATH` in advance of build. Library linking is now handled closer to the build.
- Explicitly enabling `VIAMCPPSDK_USE_DYNAMIC_PROTOS` - it is now enabled by default
=> DOCS-1046: Update C++ ML Tutorial with updated build flags

docs/manage/CLI.md
- Add `viam login --api-key` and `viam organization api-key create` reference documentation, with usage instructions.
- [/manage/cli/#authenticate](https://docs-test.viam.dev/91609eb01c0541117f13ec11ef0aaf2ab4004b2f/public/manage/cli/#authenticate)
=> DOCS-1071: Add CLI org API key commands

docs/extend/modular-resources/configure.md, docs/extend/modular-resources/create/_index.md, docs/extend/modular-resources/key-concepts.md, docs/extend/modular-resources/upload/_index.md, docs/manage/CLI.md, docs/tutorials/custom/controlling-an-intermode-rover-canbus.md
Add guidance to selecting a model name to the Modular Resources Key Concepts page
- Add links to this guidance from two places on existing `create` workflow page.
- Folded in separate guidance from DOCS-1035 as well (`to_lower()` pls!)
- Folded in additional guidance from DOCS-1050 as well (valid APIs to implement as custom models)
- Removing subtype content and API naming details per EH & FA feedback. Dedicated "New API subtype" page will move elsewhere in a separate PR.
- Updated links elsewhere to use new headers.
- [Modular Resources: Key Concepts](https://docs-test.viam.dev/0d6b450bee3620c3a98b715595977b9ca222723f/public/extend/modular-resources/key-concepts/#namespace-1)
=> DOCS-1044, DOCS-1050: Provide model implementation guidance

docs/extend/modular-resources/configure.md
Also applies a small body text change that was applied to the similar words in the other part of the doc.
=> Fix JSON indentation on modular config doc

docs/components/board/jetson.md
Hidden deep within jetson documentation is a spec that says the pins "all operate on 3.3v signals". This means that you can harm them by attaching signals over 3.3v, such as from an encoder powered by 5v. Here is my attempt at a warning to users so they don't fry their pins.
=> [RSDK-4743] Add warning for connecting jetson pins to signals over 3.3V

docs/installation/prepare/jetson-agx-orin-setup.md
* Arrow links keep failing the htmltest and we use NVIDIA links at beginning of document-- removing these links and replacing with all NVIDIA links
=> Make all AGX orin links the same

docs/installation/_index.md
Feedback relayed by @mcvella: install guide seems to lump microcontrollers in with the fully-supported SBCs
* Separate out into own section
=> Update _index.md separate out microcontrollers re. discord feedback

.htmltest.yml
- Temporarily removing `medium.com` from `htmltest` tests.
=> Removing medium.com for now

docs/extend/modular-resources/upload/_index.md, docs/manage/CLI.md
Add brief notice that a module's supported platforms can be viewed on that module's registry page.
- Will add additional related copy (selecting a platform) to the `configure` page for "add a module" steps as part of the DOCS - 1059 and DOCS - 1086 effort as soon as the eng tickets they are blocked on merge.
=> DOCS-1090: Note platform visibility in registry

docs/components/arm/_index.md, docs/components/motor/_index.md, docs/components/sensor/_index.md
First five examples are now covered-- last three are a little ambigious and unsure whether/where to add (tensorflow-lite for what the model name is and how to add it to docs, last two are old custom base tutorials)
=> DOCS-1098: Add link to modular resource examples in relevant resource pages

docs/components/servo/pi.md, docs/program/run.md
* Add clarification here that `max` is user's choice for maximum rotation (along with `min`) and `max_rotation_deg` should be based off of what your hardware can possibly support, for PWM safety protection
=> DOCS-1109: Clarify difference between `max_rotation_deg` and `max` attribute configuration for a `pi` servo

docs/extend/modular-resources/upload/_index.md
Correct key usage in GH action step for upload / update.
- [/extend/modular-resources/upload/#update-an-existing-module-using-a-github-action](https://docs-test.viam.dev/1fe708c6b502ecd9dc4bb1f3d43af9dd42bbf2de/public/extend/modular-resources/upload/#update-an-existing-module-using-a-github-action)
=> DOCS-1115: Correct key usage in GH action

docs/manage/CLI.md
Removed both macOS arch direct download steps in favor of new `brew` install.
- Also updated "To later update ..." sentence with macOS (brew)-specific instruction.
- Left Linux instructions as-are (but simplified `uname -m` tip, since it now only applies to a subset of installation paths)
- [/manage/cli/#install](https://docs-test.viam.dev/08459e33eca493b9327147cabd30ee23e22262d8/public/manage/cli/#install)
=> DOCS-1116: Update viam CLI brew install

docs/appendix/glossary/module.md, docs/appendix/glossary/resource.md, docs/extend/_index.md, docs/extend/modular-resources/_index.md, docs/extend/modular-resources/configure.md, docs/extend/modular-resources/create/_index.md, docs/extend/modular-resources/key-concepts.md, docs/manage/CLI.md, docs/manage/configuration.md
Some quick updates to MR language and copy day-of release.
- Adding note to consider platform support when adding modules
- Updating uses of `module` glossary tooltip to consistenly use `module` as title text instead of `modular resource`. MR should link instead to `key-concepts`.
- Updated glossary entry itself for `module` to reflect the latest wisdom, and small tweak to `resource` glossary entry in like fashion.
- A few more opportunities for linking between reference and procedurals
- A few language fixes.
=> DOCS-1107: Day-of MR tweaks

docs/program/apis/cloud.md, static/include/services/apis/cloud.md
Code examples have all been tested (with valid strings of course)
=> DOCS-1088: Document more of the cloud API

docs/manage/CLI.md
tested on linux x86_64.
Might as well include instructions so that people get updates.
@abe-winter Is there a reason we didn't include instructions for linuxbrew?
=> Add linuxbrew install instructions

docs/extend/modular-resources/_index.md, docs/extend/modular-resources/upload/_index.md, docs/manage/CLI.md
Clarified mentions of `visibility` field in `meta.json`. We already indicated that it was `private` by default (maybe I intuited the change, or saw an eng ticket somewhere coming down the pipe? Don't remember), so this is mostly to unify language.
=> DOCS-1110: Clarify visibility private by default

docs/extend/modular-resources/upload/_index.md
Super easy one, we now version the `upload-module` GitHub action.
=> DOCS-1106: Update upload github action to v1

docs/manage/CLI.md
=> Update CLI.md from organization to organizations

docs/extend/modular-resources/create/_index.md
Removing `import sys` because it isn't used.  adding imports for classes that are in fact used.
=> Fix up imports in main.py example

assets/scss/_styles_project.scss
On wide monitors this will create a gap instead (there's some margin magic going on for linking to headers that interferes with this) - I think that's probably fine though
=> DOCS-493: Clear images for new headlines

docs/program/run.md
* Trying to explain the "why" of this use case-- internal docs feedback from @mcvella and team
=> DOCS-1113: Add clarification for running code remotely to client SDK Run Code page

docs/tutorials/get-started/confetti-bot.md
* Noticed that raw JSON template was using `local` after naming board `party`
=> Update confetti-bot.md code for correct board name

README.md
Update pre-commit hooks descriptions to advise of need to `chmod` if creating a net-new hooks file.
=> Update README hooks instructions

docs/services/ml/_index.md, docs/services/vision/detection.md, docs/services/vision/segmentation.md
Everywhere else, we use bold for required attributes.
=> Make tables consistent

docs/components/arm/_index.md, docs/components/arm/yahboom-dofbot.md
We're kicking the yahboom arm out of the rdk. I've changed some of the wording and removed the attributes (there are none now https://github.com/viam-labs/yahboom).
I don't have access to viam-labs right now so can't upload it ... boo! So I've used my name as a placeholder for the namespace for now.
We can also not document this arm - I don't think we're uploading it to the viam namespace. 
Should I keep the state of the module (only supports joint position movement for now) in the readme?
Thanks.
=> Change yahboom documentation to modular.

docs/installation/_index.md
- Homepage has direct installation step, linked `/Installation` page instead has text "Instructions for a supported install of Homebrew are on the [homepage](https://brew.sh/)."
=> Update brew install link

docs/components/base/agilex-limo.md
In a recent PR with similar config options, it was decided that there shouldn't be spaces.
=> Make agilex config option formatting consistent

docs/components/board/pca9685.md
This config value was literally unused in the code, and has no semantic meaning (I believe each pin on the board has its own frequency independent of the other pins). So, https://github.com/viamrobotics/rdk/pull/3032 removes the value from the config, and this PR updates the docs to match.
I wasn't sure who should review, so I picked the first person Github suggested. Feel free to reassign if that's wrong.
=> remove pwm_frequency_hz from pca9685 board config

docs/extend/modular-resources/examples/triton.md
Happened to notice this while looking at weekly summary stuff— it was string when needs to be obj I think (nested dictionaries in json?)
=> Update triton.md parameter type

docs/services/data/_index.md
Remove a caution for data capture not resuming if cloud sync is disabled mid-sync. Data capture will continue regardless of cloud sync, and cloud sync will continue once reenabled.
=> Remove cloud sync interruption warning

docs/installation/prepare/jetson-agx-orin-setup.md, docs/installation/prepare/jetson-nano-setup.md
* Improve Serial Communiation protocol tips for AGX orin with links to NVIDIA's documentation
* Add table to Orin Nano with what Chris thought was helpful
=> DOCS-1210: Add pinout table reference and notes for launching `jetson-io.py` to Jetson Setup guides

docs/program/run.md
VLC is a specific dependency needed if I coded some video thing in my robot code, not a generic always-add. Removing in favor of re-used example text in code: `other required dependencies`.
=> Remove named dep from step 4

docs/modular-resources/examples/rplidar.md
Esha to submit separate instructions for Linux device path attributes, since RPlidar module only presently supports Linux.
Using this PR to "undo" instead of reverting previous because previous included a few typo fixes as well that I want to retain.
=> Remove macOS device path

docs/appendix/troubleshooting.md, docs/modular-resources/examples/csi.md, docs/modular-resources/examples/rplidar.md, docs/services/slam/cartographer/_index.md, static/include/install/install-linux.md
Add prominent mention of the need to install FUSE v2 in applicable places:
- For Linux installs, via the include file `static/include/install/install-linux.md`, which is included in parent pages:
- Installation Guide
- Raspberry Pi, Beaglebones, and SK-TDA4VM board Prepare Guides.
- Expanded troubleshooting section accordingly. Linked above here as well.
- Added need to install FUSE v2 to Requirements section on three modules that I was able to confirm require it:
- `csi-cam`
- `rplidar`
- `cartographer`
Questions
- Is there a good way to tell if FUSE 2 is installed, what version its running, that is platform agnostic? I would love something like `sshfs -v` or similar, if anyone knows of such an approach.
- Are there other modules that ship as AppImages that I missed??
=> DOCS-1257: Add more FUSE guidance

docs/manage/CLI.md
Add docs for new `viam board list` command, but also for missing `viam board upload` and `viam board download` commands while in here.
Guess: BDFs are for `customlinux` boards. Added that text guessing, but please correct if I guess wrong!
=> DOCS-1192: Add CLI board commands

docs/services/motion/_index.md
Was incorrectly in meters before 
- python SDK field name needs to be updated to be `plan_deviation_mm`, made ticket to track and apply those changes (https://viam.atlassian.net/browse/DOCS-1277) but veering on side of leaving name `plan_deviation_m` for now so still accurate for users?
=> Make plan deviation millimeters in `motion_configuration`

docs/_index.md
Request from Rand/team to surface the internals page more, then the internals page links to setup
=> Make ESP32 board link to micro-RDK page in internals rather than setup

docs/components/movement-sensor/adxl345.md
* Change "spi bus" to "i2c bus" for I2C attribute
* Updates incorrect attribute name (I checked in https://pkg.go.dev/go.viam.com/rdk@v0.11.1/components/movementsensor/adxl345)
=> Update adxl345.md fix wrong I2C info

docs/components/board/jetson.md, docs/installation/prepare/jetson-agx-orin-setup.md, docs/installation/prepare/jetson-nano-setup.md
This changes and summarizes a warning message on the jetson board to a caution message, as requested.
@npentrel added this to all the other jetson boards rather than just the Xavier.
=> Change warning about using 5V inputs to a caution message in Jetson Board docs

docs/installation/manage/_index.md
* Add docs for uninstalling viam-server on macos and linux
User feedback request 
Reached out to @Otterverse for linux instructions, there's a bit more to do than with MacOS as Andrew detailed on ticket
=> DOCS-1268: Add docs for uninstalling `viam-server`

docs/components/gantry/_index.md
* Was caught in SDK methods checker but was actually documented, just didn't have the right link.
=> DOCS-1321: Add correct link for Gantry method

docs/installation/prepare/microcontrollers/development-setup.md
We will be moving the `esp-idf` fork from @npmenard's org to `viamrobotics`, so this PR updates the one place in the docs where we reference the old name. Note that we intend to transfer the repo, so GH should forward requests and the old name will continue to work, so this does not need an immediate deployment. This will only be merged after the transfer is actually completed.
=> RSDK-5397 Use forks from viamrobotics not npmenard

docs/appendix/glossary/api-namespace-triplet.md, docs/appendix/glossary/model-namespace-triplet.md, docs/appendix/glossary/type.md, docs/manage/CLI.md, docs/modular-resources/configure.md, docs/modular-resources/create/_index.md, docs/modular-resources/examples/custom-arm.md, docs/modular-resources/key-concepts.md, docs/modular-resources/upload/_index.md, docs/tutorials/custom/controlling-an-intermode-rover-canbus.md, docs/tutorials/custom/custom-base-dog.md
Please review the following very carefully:
A category within a [type](https://docs-test.viam.dev/1938/public/appendix/glossary/#term-type) of [resource](https://docs-test.viam.dev/1938/public/appendix/glossary/#term-resource). Resource models belonging to a subtype share the same API. [Models](https://docs-test.viam.dev/1938/public/appendix/glossary/#term-model) implement that subtype’s API protocol with different drivers.
For example, an arm is a subtype of the [component](https://docs-test.viam.dev/1938/public/components/) resource type, while the ur5e is a [model](https://docs-test.viam.dev/1938/public/appendix/glossary/#term-model) of the arm subtype’s API.
The [Vision Service](https://docs-test.viam.dev/1938/public/services/vision/) is a subtype of the …
=> DOCS-1174: Clarify model triplet

docs/program/_index.md, docs/program/python-venv.md, docs/services/ml/_index.md, docs/tutorials/projects/guardian.md
Add notice that Python SDK users must now also install the `mlmodel` extra alongside the Python SDK in order to use the ML Model service.
- Notice to central Program and ML Model service reference pages
- Inclusion on tutorials that present Python code, and use the ML Model service (though none used the deprecated 
`input_data` or `output_data` nomenclature). Guess: no changes needed to these tutorials, besides additional dep install step now documentation.
=> DOCS-1105: Add mlmodel extra for PySDK

static/include/micro-rdk.md
Changes alpha to beta in micro-rdk docs.
I think this is all that's needed. From my understanding this file is included in a few other places and generates the warning. Will double check when the link is generated.
=> Change alpha to beta in micro rdk docs

assets/scss/_styles_project.scss, docs/components/arm/_index.md, docs/components/base/_index.md, docs/components/board/_index.md, docs/components/camera/_index.md, docs/components/component/_index.md, docs/components/encoder/_index.md, docs/components/gantry/_index.md, docs/components/gripper/_index.md, docs/components/input-controller/_index.md, docs/components/motor/_index.md, docs/components/movement-sensor/_index.md, docs/components/power-sensor/_index.md, docs/components/sensor/_index.md, docs/components/servo/_index.md, layouts/shortcodes/relatedcard.html
Add related service cards for components and related components cards for services. 
Possibly should be headed 'Commonly Used With' or 'Related Resources' and contain both services & components, as there are services commonly used with other services and the same with components.
=> DOCS-1204: Add component service cards

docs/installation/prepare/rpi-setup.md
* Bug Hazal noticed-- not getting same issue with this markdown image format and the size isn't a big difference, but I'm not entirely sure why it was happening with `imgproc`.
=> DOCS-1360: Fix image spacing on Raspberry Pi install page

.github/workflows/check_python_methods.py, docs/components/input-controller/_index.md, static/include/components/apis/input-controller.md
For two missing methods: 
- `trigger_event` has a note not to be documented without full implementation (raises not implemented error) and `reset_channel` I _think_ is random helper function that shouldn't be documented, no equivalent in Go SDK. 
Paging @cheukt to confirm: is it best not to document [`trigger_event`](https://python.viam.dev/autoapi/viam/components/input/client/index.html#viam.components.input.client.ControllerClient.trigger_event) and [`reset_channel`](https://python.viam.dev/autoapi/viam/components/input/client/index.html#viam.components.input.client.ControllerClient.reset_channel) at the moment, or are they ready to be documented?
=> DOCS-1319: Filter and add correct link for input controller API missing methods

docs/installation/prepare/rpi-setup.md
Add explicit recommendations on which protocols to enable for your Rpi, based on which hardware you are using, without mentioning the Rover.
- Rover set up doc already links [directly to](https://docs.viam.com/try-viam/rover-resources/rover-tutorial/#install-raspberry-pi-os) this edited section, so also benefits from this clarification.
GUESS: "will likely need to enable the serial port" is just 'cause most of our ( movement | power ) sensors require a `serial_path`. Did I guess right?
=> DOCS-1112: Clarify RPi raspi-config

.github/workflows/check_python_methods.py, docs/program/apis/cloud.md, static/include/services/apis/cloud.md
I was checking for new cloud methods and was halfway through adding boilerplate when I realized they were all unimplemented. So I changed the script to check for that.  Leaving the boilerplate in to make it easier to add them when we do
=> Do not flag unimplemented methods

docs/appendix/troubleshooting.md, docs/components/camera/webcam.md, docs/tutorials/services/webcam-line-follower-robot.md
Add troubleshooting entry (in appendix > troubleshooting) detailing two steps to troubleshooting problematic video devices on Linux.
- Converted webcam > video_path section from troubleshooting into "Using `video_path`" section.
- Added new "Using `format`" section, with a list of pixel formats supported by Viam, drawn from [webcam.go](https://github.com/viamrobotics/rdk/blob/55a0cbadbe4c4875110ec41452818b99ddce3785/components/camera/videosource/webcam.go#L207-L215).
Question:
- Should we be documenting supported pixel formats this directly? Since there is an explicit attribute for it, even if it is often auto-populated, I think it's worthwhile to present.
- Am I correct when I say "your camera must support at least one format to be used with Viam"?
=> DOCS-794: Add camera troubleshooting

docs/micro-rdk/motor/_index.md
* Motor `IsMoving` was implemented, this ticket is for docs to reflect that change
=> DOCS-1373: Say `IsMoving()` is implemented on micro-RDK motor

docs/services/ml/_index.md, docs/services/navigation/_index.md
Noticed out of sync, thought would align
=> DOCS-1382: Switch order of Python and Go samples in ML model and navigation services to match rest of docs

docs/program/apis/robot.md, docs/program/connectivity.md
Add reference docs for new timeout support for the robot API.
- Includes new timeouts section to robot API reference page, with examples for both python and go
- We didn't have a "but first, connect to the robot using this template code" section yet, as we have for the [cloud API](https://docs.viam.com/program/apis/cloud/#establish-a-connection) so I added that in too. Can't have "configure a timeout on your connection" if you don't have "your connection".
- Some language tweaks while in there.
Noticed:
- C++ also supports a configurable timeout for `RobotClient`, but no DOCS ticket for that, [upstream ticket](https://viam.atlassian.net/browse/RSDK-5195) says docs changes needed: No.
- No timeout reference in [Go SDK docs for `RobotClient`](https://pkg.go.dev/go.viam.com/rdk/robot/client#R …
=> DOCS-1181: Add robot API timeout

docs/program/apis/robot.md, static/include/services/apis/robot.md
Add the `with_api_key` method from Python SDK to Robot API docs
=> DOCS-1323: Document robotclient api key

docs/registry/configure.md
Add docs for configuring environment variables in module configuration.
- Supports static string vars, and referencing system env vars.
- Adds 4 new default env variables for registry modules
- Not discussing local modules yet
- No UI yet, so Raw JSON only.
Thanks for the helpful review, Zach!!
=> DOCS-1291: Add env vars to module conf

docs/components/input-controller/_index.md, docs/program/_index.md, docs/program/apis/robot.md, docs/registry/create/_index.md, docs/tutorials/custom/controlling-an-intermode-rover-canbus.md, docs/tutorials/get-started/blink-an-led.md, docs/tutorials/get-started/try-viam-sdk.md, docs/tutorials/projects/bedtime-songs-bot.md, docs/tutorials/services/accessing-and-moving-robot-arm.md, docs/tutorials/services/plan-motion-with-arm-gripper.md
* There was a typo in the package name. `logger.NewDevelopmentalLogger` and `logger.Logger` should have been `logging.*`.
* Steer away from the Developmental logger as an API. Developmental for viam employees is not the same as external users.
* I noticed the "go in a square" example still did not compile. The example code was missing trailing commas.
=> RSDK-5612: Correct the use of the logging package name.

docs/manage/CLI.md
Remove last mention of `viam module update` args, which are now no longer necessary.
=> DOCS-1433: Remove CLI update args

docs/components/power-sensor/ina219.md, docs/components/power-sensor/ina226.md
The config attribute `i2c_addr` was previously stated as `i2c-addr` and `i2c_address` in other locations. This fixes that
=> Fix typos in INA219 docs

docs/manage/CLI.md, docs/services/data/_index.md, docs/services/data/configure-data-capture.md, docs/services/data/configure-data-query.md, docs/tutorials/projects/bedtime-songs-bot.md
Add new data service sub page documenting querying captured data directly in the cloud.
- Walkthrough of configuration
- Quick `mongosh` usage example.
- Linking to relevant CLI commands.
- Linking to helpful MDB reference docs.
- Updating `"type": "data_manager",` `service_configs` to now include additional `"reader_name"` key on steps to configure, and in one tutorial that uses this configuration.
- What are the password constraints for the Atlas DB user we create? Does Viam check anything, or do we just hand off to Atlas' check and just faithfully forward any encountered error to the user?
- Do you have a better `mongosh` shell example command? Something practical ideally. How did you test this with actual sensor data -- can I use that example test command here please?
- What is the …
=> DOCS-1335: Add queryable sensor data docs

docs/manage/CLI.md, docs/registry/upload/_index.md
Add newly supported platforms to `--platform` support table for `viam module upload` command.
Note: Epic is named suggesting that multiple archs could be uploaded at the same time, but I wasn't able to do so with v0.13.0. 
EDIT: Thanks for helpful comments Zack, I've fixed up my misconceptions in the copy!
=> DOCS-1380: Support more platforms

docs/components/camera/ffmpeg.md, docs/components/camera/rtsp.md
Add link to `ffmpeg` camera from `rtsp` camera, for streaming cameras that use H264 or MP4 tracks.
- Clarified `video_path` attribute on `ffmpeg` camera to highlight usage with `rtsp` cams.
=> DOCS-1454: Add ffmpeg link to rtsp

assets/scss/_styles_project.scss, layouts/shortcodes/glossary_tooltip.html
Glossary tooltip items (the ones you add with `{{< glossary_tooltip term_id="term" text="text" >}}`) are now no longer clickable. They are also styled differently (black with a dotted line underneath).
=> Change glossary item styling

docs/ml/_index.md
Add SVG icon to ML landing page, so that it shows up with preview icon when viewed on other pages' `## Used With` sections (i.e. using `relatedcard`)
=> Add icon to ML landing page

docs/build/configure/components/motor/gpio/_index.md
Noticed these were messed up while working on micro-rdk GPIO motor
* Move to pins struct
=> Update _index. fix `en_low` and `en_high` attributes guide

docs/data/query.md
The previous command did not work; updated with one that does.
=> Update the mongosh command to connect the Viam org's MongoDB Atlas instance

docs/build/program/apis/data-client.md, static/include/services/apis/data-client.md
Add three missing DataClient API methods to DataClient API reference page:
- `add_bounding_box_to_image_by_id`
- `remove_bounding_box_from_image_by_id`
- `streaming_data_capture_upload`
=> DOCS-1430: Add missing DataClient methods

docs/registry/upload/_index.md
This page contained some references to the now-removed behavior regarding names & requirements for specifying an org-id. 
Now all modules use a `module_id` field in their `meta.json` so the action does not need the `org_id` and the `name` field does not exist anymore
The action PR: https://github.com/viamrobotics/upload-module/pull/5/files
=> Update registry upload with new cli behavior

docs/get-started/installation/prepare/beaglebone-setup.md
Previous link's target content at Beaglebone appears to have been removed in favor of this new all-in-one guide. Updated link on our docs page to match.
- Removed second link, which appears minimally useful at present, perhaps also recently changed on Beaglebone's side.
=> Update 404 link

docs/data/dataset.md, docs/data/view.md, docs/fleet/cli.md
Add CLI reference entries for `viam dataset` commands:
- `dataset add`, `dataset remove` and `dataset [add|remove] filter`
- Added mentions to Datasets and View Data pages.
=> DOCS-1493: Add dataset CLI command

docs/components/board/_index.md, docs/components/gantry/_index.md, docs/components/input-controller/_index.md, docs/components/sensor/_index.md
Somewhat subjective but, some of these don't seem directly related so I suggest we take these ones out.
If we *don't* take ML out of board, we need to replace the icon because it's currently empty.
=> Pare some related services

docs/components/board/_index.md, static/include/components/apis/board.md
Remove ModelAttributes from (docs.viam.com) SDK documentation.
- Ticket asked for Python method removal, but Go method also present in docs; removed both (as it seems both have been removed from the code: former from Python SDK, latter from RDK in the first place!)
=> DOCS-1464: Remove ModelAttributes

docs/registry/configure.md
Update `VIAM_MODULE_ROOT` description to indicate that it now serves as the `cwd` of the module process.
- Updated example path to no longer be based on `VIAM_HOME`
QUESTION:
- Is it still true that local module users must set `VIAM_MODULE_ROOT` manually if needed? Wasn't sure from scope / ticket / RDK PR. Thank you!
=> DOCS-1424: Update module cwd

docs/registry/create/_index.md, docs/tutorials/custom/custom-base-dog.md
Add C++ example code to Create docs for MR.
- Drew from [complex](https://github.com/viamrobotics/viam-cpp-sdk/tree/main/src/viam/examples/modules/complex) example in C++ SDK, as well as [`module-example-cpp` repo](https://github.com/viamrobotics/module-example-cpp).
- Fixed instances of `rdk:service:base`, which should be `rdk:component:base` instead, per Rand.
- (out of scope): Fixed instances of `rdk:components:*` elsewhere in the docs, these should use singular `component`.
CODE SAMPLES:
- Thanks so much Benji and Ethan for the help! Compiles and appears to run without errors.
QUESTIONS:
- You've answered all my questions, thank you!
NOTES:
- Changing 'client' language outside of C++ scope on this page to be handled separately in DOCS - 1527, per discussion thread. LMK if there are …
=> DOCS-514: Add C++ MR create examples

docs/fleet/cli.md, docs/registry/upload/_index.md
Add brief mention of Owner perms by default to API key steps on MR upload page, and also on organizations page.
- Since **Owner** is default, simply advising users on presence of option to change: no change is required for most users.
=> DOCS-1529: Add RBAC perms notice to API keys

docs/mobility/slam/cartographer/_index.md
Since cloud slam compute is quite expensive under our current pricing model, but it's a large effort to add a separate billing sku for cloud slam compute, for the moment we just stopped charging for cloud slam compute under APP-3453.
I wanted to suggest docs changes to reflect this, and marked APP-3453 as "Docs changes needed", but couldn't figure out if a DOCS ticket was automatically generated. So, I'm just putting up this PR, and adding it to the "Docs changes needed" description on APP-3453.
It's okay if this is merged after APP-3453 is released, since the current line about pricing in the docs is not very specific (and it's unlikely people will complain about getting a lower bill than they expected).
=> DOCS-1558 Update docs for "APP-3453 Do not bill for cloud slam compute"

assets/js/sentry.js
As I was reading through the module creation docs, I noticed that switching tabs for each supported programming language has a noticeable delay. When I traced the performance of that feature using the browser devtools, much of the time is taken up by the JavaScript for the Sentry Replay monitor. This is a [known issue](https://docs.sentry.io/product/session-replay/performance-overhead/?original_referrer=https%3A%2F%2Fduckduckgo.com%2F):
> There's a known performance issue that happens when replays with many DOM mutations are recorded. It generally occurs when rendering large data grids. We're working on a fix, but in the meantime we recommend you [use the blocking feature](https://docs.sentry.io/platforms/javascript/session-replay/privacy/#blocking) to avoid recording large mutations …
=> fix: block Sentry Replay for table class

docs/ml/deploy.md
Matt Vella sent over feedback from a community user where he filmed a YouTube video and apparently spent a lot of time on this docs page not realizing he needed a vision service/that that was his "next steps". We do make it pretty clear already on that page but this is what I could think of to make it even more clear
* Add sentence under "Used with" talking about combination of mlmodel service, mlmodel vision service, and transform camera
=> Add more info about vision service and camera to `mlmodel` page

layouts/shortcodes/expand.html
Fixes a few issues with the expander shortcode:
- Fixes indents and logic scope (`-`) to be renderable within HTML, and retain CSS styling.
- This should allow this shortcode to be useable outside of pure MD, such as in HTML tables. I think!
- Fixes typo in default expander title to now display a default title on the expander if one is not otherwise supplied.
- Previously, unset titles would result in blank expander titles.
=> Fix expander shortcode

docs/appendix/troubleshooting.md, docs/components/camera/webcam.md
Clarify supported camera pixel formats, which have very similar names.
- Taking opportunity to add additional alternate names for popular pixel formats, to aid with site search and google search users finding the `webcam.md` page.
- Added `v4l2-ctl --list-formats-ext` command to `webcam.md` to assist with self-determination.
=> DOCS-1579: Clarify pixel formats

docs/build/micro-rdk/base/two_wheeled_base.md, docs/build/micro-rdk/board/esp32.md, docs/build/micro-rdk/encoder/incremental.md, docs/build/micro-rdk/encoder/single.md, docs/build/micro-rdk/motor/gpio.md, docs/build/micro-rdk/movement-sensor/accel-adxl345.md, docs/build/micro-rdk/movement-sensor/gyro-mpu6050.md, docs/build/micro-rdk/servo/gpio.md
* Add micro-RDK in parenthesis to micro-RDK component titles so that they are clearly separate from RDK component pages when searching for a page or looking at the top of a page
I opted not to also add a sentence linking to the full component page because I think with this addition they should be ending up in the right place anyways, and it's pretty easy to find viam-server components section (at top level in nav). If people get confused again happy to add it in.
=> DOCS-1582: Add micro-RDK in parenthesis to titles

docs/components/camera/_index.md
Clyde confirmed method is supposed to work with other cameras but was created for realsense and similar cameras. 
* Add note to explain that
=> DOCS-1572: Add note to `GetImages()` method explaining imagers usage

.github/workflows/docs.yml, .github/workflows/pr-deploy-and-comment.yml, .github/workflows/run-htmltest.yml
- use `ubuntu-latest` instead of viam-hosted `x64` runners
- (I don't know this repo well, definitely feel free to close this if it's not helpful)
- long queue times on self-hosted runners
- this will appear to be queued because the `pr-deploy-and-comment` job is `on: pull_request_target`, which means it uses CI yaml from the `main` branch. here are passing runs of the edited jobs:
- [htmltest](https://github.com/viamrobotics/docs/actions/runs/7480426227/job/20359817215)
- [pr-deploy-and-comment](https://github.com/viamrobotics/docs/actions/runs/7480302372/job/20359428258)
- docs job -- I didn't test this one because it has a bunch of deploy steps. I can run it via `workflow_dispatch` if you want, or we can see what it does on `main` and fix if problems
=> Convert x64 self-host to ubuntu-latest

docs/get-started/try-viam/rover-resources/rover-tutorial/_index.md
I found that my power sensor wasn't getting readings and Jeremy noticed this was missing! 
* Add enable I2C on Pi step
=> Add enable I2C step to Viam Rover 2 docs

docs/registry/upload/_index.md
Clarify in module upload docs that the owner role is required for organization API keys to be usable with the upload-module GitHub action.
Thanks for a great docs ticket!!
=> DOCS-1581: clarify API key role req

docs/tutorials/get-started/try-viam-sdk.md
When we execute [Drive a Rover with the Viam SDK](https://docs.viam.com/tutorials/get-started/try-viam-sdk) tutorial and run Go code from that page, we get an error:
```
$ go run sdk.go 
./sdk.go:9:5: imported and not used: "go.viam.com/rdk/utils"
=> Remove unused import in Go code in Try Viam SDK tutorial

docs/fleet/cli.md
Add brief reference docs for `module build` subcommands
- Including additional `meta.json` object `build` to add
- Including Zack's awesome id --> logs workflow as well.
Questions:
- Do users have to set up cloud runner? Is there billing? Or is `module build start` all I need to get on Viam-provided hardware with my hefty build job?
=> DOCS-1721: Add build CLI commands

docs/mobility/slam/_index.md, static/include/services/apis/slam.md
This PR removes information regarding the deprecated `GetLatestMapInfo` endpoint from SLAM
**JIRA Ticket:** https://viam.atlassian.net/browse/DOCS-1504
=> DOCS-1504 RemoveGetLatestMapInfo

docs/fleet/cli.md
This comes from this PR: https://github.com/viamrobotics/rdk/pull/3572
This came from a misunderstanding of the scope doc and what the setup/build fields should accept.
We are restricting it to only accept valid bash commands (and the name of a shell script without a ./ is not a valid bash shell command)
=> Update module build setup docs to have `./setup.sh`

docs/components/movement-sensor/gps/gps-nmea.md
* Remove disable nmea option from gps-nmea movement sensors-- this is the only model where it was
=> DOCS-1745: Remove `disable_nmea` option from movement sensor

docs/registry/configure.md
I went through these last week and this didn't make sense. While you can add the module and the model in whatever order, the sentence "You can also add the module directly, without first adding its modular component or service:" is confusing, because it doesn't then say you need to add the component or service after? I think pointing out that you can add it in any order isn't super valuable so let's stick with one way or the other
=> Update local module instructions

docs/fleet/cli.md, docs/registry/upload/_index.md
Add intro to Registry > Upload page to raise awareness of GH upload action, by presenting choice between upload options in page into.
- Added tip to CLI update section to note existence of GH upload option instead.
- Clarifying header for CLI upload steps to use CLI in header title
=> DOCS-1850: Highlight upload GH action

docs/ml/vision/mlmodel.md
Add notice that vision service `mlmodel` detectors and classifiers require specfic tensor names
- Add attributes for remapping those names to meet these requirements.
=> DOCS-1830: Remap tensor names

docs/get-started/installation/_index.md
Add note that Windows users can install WSL to use `viam-server` "on windows".
- Including direct link to WSL install instructions
NOTE:
- Alternate: remove alert styling for notice, to draw less attention to it, if desired.
- Not adding Windows to "Viam-server supports:" list, since it's via WSL which is Linux, which is already listed. "Windows" as listed in this list would encourage users thinking of the .NET C# thing underneath the Linux, which we most definitely do not support.
=> DOCS-1887: Add WSL note

docs/mobility/navigation/_index.md
* As per RSDK-4509, change that was made is "This method should now also return all transient obstacles which are discovered by the vision services configured for the navigation service, in addition to the obstacles that are configured as a part of the service."
* Also decided to change wording from location to objects as that seems more accurate for GeoObstacle types?
=> DOCS-1544: Add information about transient obstacles from vision services in navigation `Obstacles`

docs/ml/deploy.md, docs/ml/train-model.md, docs/ml/upload-model.md
Model version format is outdated in 3 documentation pages (the only 3 occurrences). Updated formats, description and package config that was missing "type" key in 2 out of 3 places. Wasn't sure people would understand `T` in `YYYY-MM-DDThh-mm-ss` is just a letter 'T' so also gave an example of a version.
=> Update model version and description

assets/scss/_styles_project.scss
Changing the links to not be underlines except on hover. This should make it feel less overwhelming
=> DOCS-1446: Chang link styling to be less overwhelming

docs/build/provision/_index.md
Add mention that Provisioning users can also write their own mobile app using the Flutter SDK to connect to the Viam agent and provision machines.
=> DOCS-1857: Provision with your own app

.github/workflows/check_python_methods.py, .gitignore, docs/build/program/apis/robot.md, static/include/services/apis/robot.md
I think the links will start working tomorrow, so won't merge till then
=> DOCS-1901: Fix python error, add cloudmetadata

docs/fleet/cli.md, docs/registry/upload/_index.md
Remove `viam module update` from the module creation workflow steps
- Rationale: less steps better, as no use case exists for manual run of `update` (i.e. without `upload` immediately following).
-  If not, please correct!
- Adjust CLI docs to reflect that `upload` automatically runs `update`, but retain mention there as the command still exists.
=> DOCS-1899: Remove update from module create

docs/fleet/configure-a-fleet.md
https://docs-test.viam.dev/2622/fleet/configure-a-fleet/#modify-the-config-of-a-machine-that-uses-a-fragment
=> DOCS-1916: Add overwrite fragment mods

docs/get-started/_index.md
`viam-server` isn't displaying correctly because of the html tag right before it
=> Fix code formatting in Get Started

docs/registry/create/_index.md
Update Golang logging example code for module creation docs
- Including new example for `CWarnw`
=> DOCS-1827: Update Go module logging examples

docs/build/program/_index.md
`--save` option is no longer necessary when installing JS/TS packages. It's the default since [npm 5.0.0](https://blog.npmjs.org/post/161081169345/v500) which was published in 2017.
[NPM documentation](https://docs.npmjs.com/cli/v6/commands/npm-install) doesn't even list `--save` as an available option.
This is the only occurrence of `--save`.
=> Remove unnecessary --save option

docs/internals/rdk.md
Data management is covered in many other places and doesn't specifically need to be mentioned on this page when other services aren't specifically mentioned.
=> DOCS-1972: Remove data-specific heading from RDK page

docs/ml/deploy/tflite_cpu.md
Noticed that other configs did not look like our example format-- confirmed with Steven that out of these 3 options:
`"model_path": "${packages.ml_model.my_fruit_model}/my_fruit_model.tflite"
"model_path": "${[packages.my_fruit_model}/my_fruit_model.tflite"
"model_path": "/some/path/to/my_fruit_model.tflite"`
only 2 and 3 are valid, so our docs example is wrong. 
- Fix docs examples
- Tried to make clear that 3 is possible too
=> Fix tflite_cpu attributes

docs/components/camera/single-stream.md
The way to consume these cameras now is by using the modules.
=> Remove mention of Oak-D and Intel Real Sense from Dual and Single Server Camera model Docs

docs/components/board/_index.md, static/include/components/apis/digitalinterrupt.md
Request from eng., do not want to be documented
=> DOCS-2017: Remove `AddPostProcessor` from digital interrupt API / board docs

docs/registry/create/_index.md
- Get rid of duplicative build and run sections
- Make substitution easier to understand by using API and Model triplet pairs as they appear in github (also was slightly inaccurate)
- Add note directing to modular resources docs 
- Update agilex-limo to match (can update real readme if this gets approved)
=> Update Module readme template

docs/use-cases/configure.md, docs/use-cases/deploy-code.md
The double asterisks appear for "Test your components", and adding a line break fixed that problem but makes the linter mad about emphasis used instead of a heading, so this disables that MD rule for that section.
For Deploy, this fixes a copy pasta error.
=> DOCS-1574: Fix use case page nits

docs/ml/_index.md, docs/ml/deploy/_index.md, docs/ml/deploy/tflite_cpu.md, docs/ml/upload-model.md, docs/ml/vision/_index.md
a very long pr title
A combo of two related tickets.
Feedback: 
- A rough overview of ML and what Viam supports in the platform–Focusing on Computer Vision but more specifically Detection and Classification. Also, discuss the ML “Frameworks” that Viam supports
- Call out the Computer Vision service vs the ML Model Service and what the difference is or when you should use one vs the other
- The three ways to run an ML model on the Viam platform (really kind of four so I ended up editing that all around)
Deploy new model frameworks:
- Map framework types to services
- Make more clear in `tflite_cpu` that models at top of dropdown are models you've trained yourself and that they will only be tflite models
+ some small fixes across these docs 
Does not include best practices tips (will be …
=> DOCS-1707/DOCS-1997: Refresh ML landing page and model frameworks

docs/build/configure/_index.md
* Refactor docs webhooks section to account for different types 
* Add `part_online` example config
=> DOCS-2010: Add `part_online` type of webhook

docs/registry/create/_index.md, docs/registry/upload/_index.md
Re. [this ticket](https://viam.atlassian.net/jira/software/c/projects/DOCS/boards/31?quickFilter=40&selectedIssue=DOCS-2050), this should be only docs change needed for base image rollback Abe made 
- Comment out links to broken module
(Asking Abe about associated ticket: will track work to fix to uncomment when needed)
=> DOCS-2050: Remove links to C++ example module broken by base image rollback

docs/mobility/slam/cartographer/_index.md
I was double checking that the warning had been added and at first thought it hadn't because it was midway down the page and in an "info" box. Suggesting moving to the top of the page in a "warning" box.
Also included two minor cleanups I noticed while on the page
=> Move warning about cloud slam being disabled to top of page

docs/components/camera/_index.md, docs/registry/create/_index.md, docs/tutorials/projects/verification-system.md
OAK-D module now supports the OAK class of cameras generally-- not just OAK-D
=> [DOCS-2114] Update OAK-D -> OAK

docs/build/micro-rdk/board/esp32.md, static/include/micro-rdk-hardware.md
Since the latest release of micro-rdk we have dropped support of older models (ESP32-WROOM)  I have updated the minimum required hardware to reflect that.
=> [RSDK-7278] Update minimum hardware esp32

docs/components/motor/_index.md, docs/components/motor/dmc4000.md, docs/components/motor/tmc5072.md, docs/components/servo/_index.md
- Add "Component" to the end of "myMotor" because the code sample code appends it.
- Change TMC and DMC Python examples to use "my_motor" because that's how the code sample code does it.
- Clarify that two methods are for encoded motors.
- Print servo positions, and trim out a couple of excess servo example lines for concision.
=> DOCS-2085: Review motor and servo snippets

docs/components/input-controller/_index.md
Probably doesn't make sense to mention frame system here for most users since input controller is for a human to control the base instead of for the motion service to control it.
=> Update input controller related services

.github/workflows/sdk_protos_map.csv, .github/workflows/update_sdk_methods.py
Restructure generated include files to be by-resource instead of by-proto, cutting the number of includes down to 29 from 291. 👀 
- Also fixed some minor whitespace issues around code fences and `.after` override files.
- Also updated mapping file with recent board API changes to reader functions.
- Also omitting one more Py method until we can fix its upstream form: `write_analog`
=> DOCS-2300: Restructure generated includes

.github/workflows/sdk_protos_map.csv, .github/workflows/update_sdk_methods.py
Improve determination of upstream data type links.
- Should fix all remaining Python SDK data type issues.
- Adds Go SDK data type link and description for `ctx`
To support the above: 
- Reduce reliance on manually populating `python_datatype_links` array, by improving scrape logic.
- Now much more reliably getting the upstream data type links, no matter where they are defined.
- Exception: returns with multiple return data types, where at least one is a Viam data type still require manual override via `python_datatype_links` array.
- Add new `link_data_types()` function to help with linking built-in data types, and any override links from `python_datatype_links` array.
- I think there is still an edge cases where we might match a built-in data type to a multiple data-type return and stop …
=> DOCS-2302: Improve data type linking

.github/workflows/sdk_protos_map.csv, .github/workflows/update_sdk_methods.py
Add Go code sample scraping to `update_sdk_methods.py`:
- Scrape code samples from the live Go SDK documentation by default, or
- Scrape code samples from a locally-staged Go SDK docs site if detected.
- All other data objects are still populated from live site, even if staging link is found. This is only for code samples. Can be changed if desired.
- Script now checks to see which port `pkgsite` is using locally, and uses that (`8080` by default): thanks for the report, Sky!
- Sierra already handled the code needed for `write_markdown()` to display scraped Go code samples (🎉 ), so this PR just needed to update `parse()`
- Replaces tab characters with double-whitespace for scraped `usage` content as well, noticed while handling tab characters in code samples (which must be converted).
- …
=> DOCS-2301: Add Go code sample scraping

docs/components/board/_index.md
+ associated un-updated code samples
=> DOCS-2166: Change return from bool to error on Go `DigitalInterruptByName`

docs/components/board/_index.md
it looks like the Status method was already mostly removed and this was a duplicate ticket but I found a remaining instance and code sample error, fixed
=> DOCS-2201: Remove remaining `Status` usage from Board API

docs/cli.md, docs/data/query.md, docs/data/visualize.md
Update `viam data database hostname` reference and usage docs to reflect new returned Connection URI value.
- Converted query and visualize guidance to use connection URI directly, simpler.
- But retained mention of hostname and database name for visualize guidance, in case some third party tools use hostname / db name for connecting.
- Updated term "connection string" to "connection URI" to match command output.
=> DOCS-2279: Add connection URI reference

docs/ml/vision/mlmodel.md
* Adds two new attributes for applying minimum confidence score filters + examples
=> DOCS-2202: Add new post processor attributes to `mlmodel` computer vision service

docs/cli.md, docs/registry/upload/_index.md
More clearly indicate that example URL is example, using placeholder syntax.
=> DOCS-2340: Clarify example link

docs/mobility/slam/_index.md
We removed the component reference and extra returns from the slam service API. cleaning that up on the main page.
=> Update Slam service returns

docs/components/arm/fake.md
Slightly change the wording in the configuration documentation for a fake arm. A user can now leave all attributes empty and a fake arm will still show up on the arm RC card.
=> DOCS-2413: update fake arm docs

docs/components/board/pi5.md
* Fix with suggestion from @oliviamiller 
Olivia: need to confirm with you that this is `firmware` and not `firmare`? Googling ([this forum](https://forums.raspberrypi.com/viewtopic.php?t=367971)) seems  to suggest firmware so I figured it might be a typo but not sure, don't have access to pi5
=> DOCS-2418: Fix file path to enable PWM on pi5

docs/get-started/installation/_index.md
Images were spilling out to the right of the tabs on narrow screens
=> Fix windows installation image formatting

static/include/install/install-linux.md
* Removing as duplicated in app 
Figure it's probably ok to keep dependency mention at top + keep troubleshooting documentation in there in case ppl search for error in docs?
=> DOCS-2397: Remove FUSE steps from linux install include

.github/workflows/update_sdk_methods.py
Enhance `update_sdk_methods.py` to be able to scrape more locally-staged content:
- Now supports scraping all content from a staged Go docs instance, rather than only code samples
- Now supports scraping all content from a staged Python docs instance.
- Now supports scraping all content from a staged Flutter docs instance.
NOTE:
- Check out the new Wiki page in the Dev Content section for how to stage each of the three SDK docs sites locally.
=> DOCS-2410: Enhance staged docs site scraping

.github/workflows/update_sdk_methods.py
Fix a miss in my https://github.com/viamrobotics/docs/pull/2966 PR where scraped method links for Py and Go methods incorrectly retained the staging hostname (i.e. `localhost` & port number). These links now properly reflect the intended upstream live target.
- Staged Flutter method links did not require this fix.
=> DOCS-2449: Fix staged method links

.github/workflows/update_sdk_methods.py
Fix scraped Go parameter and return links that contain GO SDK versions to use latest instead.
- Some upstream param and return type links use versioned SDK url, some use latest. This standardizes on latest for all case, regardless of upstream.
NOTE:
- It is possible that there are times where we might actually want a version in the URL, like for legacy support of a method that has since been deleted from current versions, but exists in archived versions, for example. If this becomes the case, we can revert this. Nearer-term: leaving versions in is instead more likely to result in users finding themselves on upstream docs pages that contain outdated information.
=> DOCS-2439: Fix Go versioned links

docs/registry/create/_index.md, docs/registry/upload/_index.md
From feedback: 
- re-add how things work on other installation methods to packaged executable section 
- highlight testing and iterating doc before it is highlighted in uploading and deployment
- change bullet points on upload re. [this feedback](https://viam.atlassian.net/browse/DOCS-2370?focusedCommentId=30571)
=> DOCS-2370: Add more information for other Python methods

.github/workflows/update_sdk_methods.py
Fix parsed formatting for Go list data types in two forms:
- `param name []<a href param link>`
- `param name []*<a href param link>`
=> Fix Go list formatting

.github/workflows/update_sdk_methods.py
- Updates MD table generation to conform to [new linting requirements](https://github.com/viamrobotics/docs/pull/2958).
- Strips links from proto descriptions' first sentence when used as MD table proto description.
- Does not alter links in same proto descriptions (from proto override file) when used on API pages as full descriptions.
=> DOCS-2462,DOCS-2463: Improve MD table generation

static/include/components/apis/generated/arm.md
Re-ran automation with the fix from https://github.com/viamrobotics/docs/pull/2993 to now scrape updated (locally-staged) code samples for all inherited functions (from `resource.go`), for the `arm` component only (rest will be picked up automatically from now on).
=> Add inherited Go code samples

static/include/app/apis/overrides/protos/data.AddBinaryDataToDatasetByIds.md, static/include/app/apis/overrides/protos/data.BinaryDataByIDs.md, static/include/components/apis/overrides/protos/arm.GetEndPosition.md, static/include/components/apis/overrides/protos/arm.MoveToPosition.md, static/include/services/apis/overrides/protos/motion.MoveOnMap.md
Remove SDK links from proto descriptions.
- Converted `Pose` to use docs-side link target, matching other uses sitewide (like [this one](https://docs.viam.com/internals/kinematic-chain-config/#kinematic-parameters))
- Unlinked `BinaryData` entirely.
=> DOCS-2471: Remove SDK links from proto descriptions

docs/components/camera/_index.md
Realized this was tuple while looking at Python SDK docs. Code sample doesn't need to be changed
=> Update _index.md fix return on GetImages()

.github/workflows/update_sdk_methods.py, static/include/components/apis/overrides/protos/movement_sensor.GetCompassHeading.md
Improve the stripping of MD links from proto override files to handle links with title text that includes parens, skip square bracket pairs that aren't part of MD links (like text ```a float [`0.0`, `1.0`]```, and catch a few other misses from my first iteration.
- Also update override file with malformed link.
=> Improve MD link stripping

.github/workflows/update_sdk_methods.py
Fixes linking to headers for protos with periods in their name (required for `Options.with_api_key`)
=> Handle period in proto name

docs/components/board/_index.md, static/include/components/apis/analogreader.md, static/include/components/apis/board.md
Try 2 
- Fix python method and heading name on AnalogByName (see [this PR](https://github.com/viamrobotics/docs/pull/2861))
- Fix Analog `Read` links 
- Add Analog `Write` method
- Remove `WriteAnalog` method from board (was moved to Analog interface)
- Remove Analog `Close` method (not there/no longer exists) 
As far as I can tell this doesn't cross with with other signaling APIs pr to fix the way they're displayed on the [main APIs page?](https://docs.viam.com/appendix/apis/) (which seems to have been moved into the appendix anyways)-- if we change the way they're displayed on the board page I think this would still need to be fixed
=> Fix Board Analog API methods

.github/workflows/update_sdk_methods.py
This data type is the `FromRobot` return type for every resource: it returns a `RobotClient`.
=> Fix RobotClient linking

static/include/components/apis/generated/arm.md, static/include/components/apis/generated/power_sensor-table.md, static/include/components/apis/generated/power_sensor.md, static/include/components/apis/generated/sensor.md, static/include/components/apis/generated/servo.md, static/include/components/apis/overrides/methods/go.arm.EndPosition.Pose.return.md, static/include/components/apis/overrides/methods/go.arm.JointPositions.JointPositions.return.md, static/include/components/apis/overrides/methods/go.arm.MoveToJointPositions.positionDegs.md, static/include/components/apis/overrides/methods/go.arm.MoveToPosition.pose.md, static/include/components/apis/overrides/methods/go.power_sensor.Current.bool.return.md, static/include/components/apis/overrides/methods/go.power_sensor.Current.float64.return.md, static/include/components/apis/overrides/methods/go.power_sensor.Power.float64.return.md, static/include/components/apis/overrides/methods/go.power_sensor.Voltage.bool.return.md, static/include/components/apis/overrides/methods/go.power_sensor.Voltage.float64.return.md, static/include/components/apis/overrides/methods/go.servo.Move.angleDeg.md, static/include/components/apis/overrides/methods/go.servo.Position.uint32.return.md
Update already-merged autogen content (`arm`, `power sensor`, `sensor`, and `servo`) with new param and return descriptions overrides from https://github.com/viamrobotics/docs/pull/3019.
- Also includes the latest upstream Python descriptions.
- Script handles inherited method overriding for us, so this was actually pretty quick, only a dozen override files across all four merged components.
=> DOCS-2501: Update autogen descriptions

.github/workflows/update_sdk_methods.py
Add ability to override parameter descriptions and/or return descriptions, using (param|return) override files.
- Each SDK requires slightly-different override logic, see script comments.
- Also cleans up override file detection logic for `before` and `after` overrides: simpler, shorter, less filesystem traversal.
- Important: no longer supporting omitting literal string `before` for `before`-type overrides, we need this explicitness to support new param|return override filepath detection.
Note:
- If you are seeking to populate a bunch of param|return override files, see the notes in the script: you can uncomment print statements to get the full expected override path for each param|return to make populating these much easier.
- Even better, you can now use something like the following to …
=> DOCS-2488: Add param, return override support

static/include/app/apis/generated/app.md
Fix accidental inclusion of staging links instead of their intended target live domain.
=> Fix staging links

docs/services/vision/obstacles_pointcloud.md
=> Correct invalid JSON example in obstacle point cloud docs

.github/workflows/update_sdk_methods.py
Fixes staging link bug with Python for params and return. Previously causing find and replace on each character in `url` when no staging site was detected.
=> Fix staging link bug 2

.github/workflows/sdk_protos_map.csv, .github/workflows/update_sdk_methods.py, static/include/robot/apis/overrides/protos/robot.Shutdown.md
=> Add shudown method and revise ordering of board

.github/workflows/update_sdk_methods.py, static/include/app/apis/generated/app.md
@andf-viam I accidentally did this while investigating https://github.com/viamrobotics/docs/pull/3042. Didn't see it was assigned to you. Feel free to wait with merging this until after presentation.
=> DOCS-2506: Add raises to write_markdown

.github/workflows/update_sdk_methods.py
Remove three more PySDK API methods that were preventing parsing in some cases.
- I will investigate these later, but they do not seem user-facing. If so, will re-add with proper parsing fix if needed.
=> Remove more Py APIs

docs/get-started/quickstarts/control-motor.md
- A motor driver is required for all motors. A board cannot provide sufficient power to run a motor.
- `GoFor` requires that a maxRPM attribute is set. If max RPM is not set, the code will throw an error. Since many users won't know their max RPM off hand, SetPower is a better method to use here and un-breaks the code.
- Fixed some error handling for an absent error
- Removed the print isMoving line since there's no value for it so it'd throw an error
- Removed specific machine address
- Some spelling, code indentation, and other nits
- The heading formatting is optional; feel free to suggest changes/revert that part
=> Fix motor quickstart bugs

docs/fleet/provision.md
Add brief mention to provisioning reference page that Agent logs are now sent to the Viam app > **LOGS** tab.
=> DOCS-2432: Add Agent cloud logging

.github/workflows/sdk_protos_map.csv, .github/workflows/update_sdk_methods.py, static/include/components/apis/overrides/protos/arm.FromRobot.md, static/include/components/apis/overrides/protos/arm.Name.md, static/include/components/apis/overrides/protos/base.FromRobot.md, static/include/components/apis/overrides/protos/base.Name.md, static/include/components/apis/overrides/protos/board.FromRobot.md, static/include/components/apis/overrides/protos/board.Name.md, static/include/components/apis/overrides/protos/camera.FromRobot.md, static/include/components/apis/overrides/protos/camera.Name.md, static/include/components/apis/overrides/protos/gantry.FromRobot.md, static/include/components/apis/overrides/protos/gantry.Name.md, static/include/components/apis/overrides/protos/generic_component.FromRobot.md, static/include/components/apis/overrides/protos/generic_component.Name.md, static/include/components/apis/overrides/protos/gripper.FromRobot.md, static/include/components/apis/overrides/protos/gripper.Name.md, static/include/components/apis/overrides/protos/motor.FromRobot.md, static/include/components/apis/overrides/protos/motor.Name.md, static/include/components/apis/overrides/protos/motor.SetRPM.md, static/include/components/apis/overrides/protos/movement_sensor.FromRobot.md, static/include/components/apis/overrides/protos/movement_sensor.Name.md, static/include/components/apis/overrides/protos/power_sensor.FromRobot.md, static/include/components/apis/overrides/protos/power_sensor.Name.md, static/include/components/apis/overrides/protos/sensor.FromRobot.md, static/include/components/apis/overrides/protos/sensor.Name.md, static/include/components/apis/overrides/protos/servo.FromRobot.md, static/include/components/apis/overrides/protos/servo.Name.md, static/include/services/apis/overrides/protos/vision.FromRobot.md, static/include/services/apis/overrides/protos/vision.Name.md
Add support for scraping Flutter code samples to automation.
- This required switching Flutter HTML scrape target from protos content to `viam_sdk` content, which should have been the original target from the beginning - Flutter was the first scrape target I wrote and I've learned a lot since then! Fixed now.
- Many fixes to mapping file now that we are considering actual Flutter methods and not their backing-protos (many of which are not implemented as methods)
- Added proto overrides for `Name` and `FromRobot`; Flutter-only for now but will expand to other SDKs after.
Note:
- Using `markdownify` here for Flutter param and return usage string conversion to markdown. Works super-well, will later convert Go usage parsing to use `markdownify`, having now seen this in action.
- No longer …
=> DOCS-2039, DOCS-2435: Add Flutter code samples

docs/build/micro-rdk/board/_index.md
Boards are not modular in the micrordk (at least not in a sane, predictable, tested way) so removing that note.
=> Remove the module section for the micrordk board

docs/build/micro-rdk/board/esp32.md
To head off confusion, it would be nice to direct users to Espressif's documentation regarding the allowable range of PWM frequencies and duty cycles on the ESP32
=> Add link to Espressif's documentation for PWM limitations

docs/build/micro-rdk/board/esp32.md
The interrupt pin is an int, not a string (https://github.com/viamrobotics/micro-rdk/blob/main/micro-rdk/src/common/digital_interrupt.rs#L5). Plus added an example.
Will probably follow up with an example pr for i2c.
=> Fix interrupt pin type and add example

assets/scss/_styles_project.scss
Tablestep divs were sizing to the text, so if the image was bigger than the text, the grey background of the tablestep div would end above the bottom of the image.
=> DOCS-2593: Fix how-to formatting

docs/registry/advanced/iterative-development.md, docs/registry/configure.md
Add notice that tarballs can be provided as **Executable path** to local modules, in addition to executable files / binaries.
=> DOCS-2369: Add tarball as executable

docs/build/micro-rdk/data_management/_index.md, static/include/micro-rdk.md
This adds documentations for the Data service configuration in Micro-RDK. It's inspired from the RDK documentation and adapted for Micro-RDK.
Is there a way to inline a section from another documentation page?
=> [DOCS-1603] Document data management service for Micro-RDK

.github/workflows/sdk_protos_map.csv, static/include/app/apis/generated/app.md, static/include/components/apis/generated/arm-table.md, static/include/components/apis/generated/arm.md, static/include/components/apis/generated/camera-table.md, static/include/components/apis/generated/camera.md, static/include/components/apis/generated/encoder.md, static/include/components/apis/generated/gantry-table.md, static/include/components/apis/generated/gantry.md, static/include/components/apis/generated/gripper-table.md, static/include/components/apis/generated/gripper.md, static/include/components/apis/generated/input_controller.md, static/include/components/apis/generated/motor-table.md, static/include/components/apis/generated/motor.md, static/include/components/apis/generated/movement_sensor.md, static/include/components/apis/generated/power_sensor-table.md, static/include/components/apis/generated/power_sensor.md, static/include/components/apis/generated/sensor-table.md, static/include/components/apis/generated/sensor.md, static/include/components/apis/generated/servo-table.md, static/include/components/apis/generated/servo.md, static/include/components/apis/overrides/methods/python.camera.get_image.after.md, static/include/robot/apis/generated/robot.md
Add more autogen Flutter methods to API reference:
- Some have already been added, this adds the remainder save for the two unfinished tickets in https://viam.atlassian.net/browse/DOCS-2030.
- This also adds `Raises` to Python methods that haven't had them added yet.
- This also corrects a few data type links (fixed bug in scraper elsewhere, this autogens these links with fix in place)
- This also corrects a few code samples (fixed upstream, so fixed here with 0 action)
- Once code sample was a script bug though: code sample for `JointPositions` was using `MoveToJointPositions`. Fixed now.
- This also includes the first pass at adding `Name` and `FromRobot` everywhere: this first pass for Flutter only, but I will shortly add to `go` and `python` once this merges.
- Also adds `SetRPM`, …
=> DOCS-2595: Add more Flutter methods

.github/workflows/docs.yml, .github/workflows/pr-deploy-and-comment.yml, layouts/docs/baseof.html, layouts/docs/changelog.html, layouts/docs/content.html, layouts/docs/glossary.html, layouts/docs/tutorials.html, layouts/partials/head.html, package-lock.json, package.json
Fixes:
```
WARN  deprecated: .Site.GoogleAnalytics was deprecated in Hugo v0.120.0 and will be removed in a future release. Use .Site.Config.Services.GoogleAnalytics.ID instead.
```
And pins version number for deploys and staging (not for checks, I want to ensure we keep up with Hugo changes)
=> Pin version and update analytics variable

docs/use-cases/collect-sensor-data.md, docs/use-cases/configure.md, docs/use-cases/deploy-code.md, docs/use-cases/deploy-ml.md, docs/use-cases/image-data.md, docs/use-cases/manage-fleet.md, docs/use-cases/navigate.md, docs/use-cases/sensor-data-query-sdk.md, docs/use-cases/sensor-data-query.md, docs/use-cases/sensor-data-visualize.md, layouts/shortcodes/tablestep.html, static/include/how-to/query-data.md
Add Grafana tab to visualize data how-to guide, and convert existing steps to be all-others in separate tab.
- Opted for simple (how-to), so omitting example forms of various URIs and connection strings. Can re-add (from `docs/tutorials/services/visualize-data-grafana.md` if helpful)
NOTICED: `tablestep` and `tabs` seem to require a specific order, perhaps tabs with tablesteps within them are not permitted, but tablesteps with tabs in them is? If so I can try switching around, but more than one tablestep is specific to the grafana tab. I could see a solution where I declare the tabset in each tablestep, if there is no way to include tablesteps within tabs. Hoping I just did something wrong.
=> DOCS-2564: Add Grafana to viz howto

docs/use-cases/image-data.md
Addresses some of https://viam.atlassian.net/browse/DOCS-2640 as well
=> DOCS-2599: Add MIME type step to image how-to and address feedback

.github/workflows/update_sdk_methods.py, static/include/components/apis/generated/motor.md, static/include/components/apis/generated/power_sensor.md, static/include/components/apis/generated/servo.md, static/include/robot/apis/generated/robot.md
Add servo, motor, robot client Flutter code samples
- Add updated power sensor Flutter code samples
- Include new omit API for Python: `to_proto`
- Include better handling for missing description in PySDK, like with above.
=> DOCS-2647: Merge more flutter code samples

.github/workflows/sdk_protos_map.csv, static/include/components/apis/generated/motor.md, static/include/components/apis/overrides/methods/go.motor.SetRPM.rpm.md
Add `SetRPM` API for Go, PySDK.
- Flutter had been added previously, but its code sample is over in https://github.com/viamrobotics/docs/pull/3121
- No Go code sample for `SetRPM` upstream, creating other ticket to invent one, separately.
=> DOCS-2417: Add SetRPM API

.github/workflows/update_sdk_methods.py, static/include/app/apis/generated/app.md, static/include/app/apis/generated/data.md, static/include/app/apis/generated/mltraining.md, static/include/components/apis/generated/arm.md, static/include/components/apis/generated/base.md, static/include/components/apis/generated/board.md, static/include/components/apis/generated/camera.md, static/include/components/apis/generated/encoder.md, static/include/components/apis/generated/gantry.md, static/include/components/apis/generated/generic_component.md, static/include/components/apis/generated/gripper.md, static/include/components/apis/generated/input_controller.md, static/include/components/apis/generated/motor.md, static/include/components/apis/generated/movement_sensor.md, static/include/components/apis/generated/power_sensor.md, static/include/components/apis/generated/sensor.md, static/include/components/apis/generated/servo.md, static/include/robot/apis/generated/robot.md, static/include/services/apis/generated/generic_service.md, static/include/services/apis/generated/mlmodel.md, static/include/services/apis/generated/motion.md, static/include/services/apis/generated/navigation.md, static/include/services/apis/generated/slam.md, static/include/services/apis/generated/vision.md
Fix Flutter data type render bug whereby `>>` is rendered as `>>` but smushed. Hugo does that. We now escape earlier in the chain of tech-to-tech-to-tech to prevent it.
- Reran all auto with fix in place to pick up new syntax for gen content
- Also fixes a bunch of Py links, earlier fixed and never rerun, or recently changed upstream. Don't know.
- Also adds latest app client changes for fragment methods. We probably have a ticket for it somewhere.
- Looks like PySDK redid their DoCommand code sample.
=> DOCS-2651: Fix flutter datatype rendering

.github/workflows/sdk_protos_map.csv, .github/workflows/update_sdk_methods.py, static/include/services/apis/generated/vision-table.md, static/include/services/apis/generated/vision.md, static/include/services/apis/overrides/protos/vision.GetProperties.md
Add `GetProperties` Go and PySDK API methods. Flutter not implemented upstream yet.
- Add new data type to Python link array for `Properties`
=> DOCS-2063: Add GetProperties API

.github/workflows/sdk_protos_map.csv, static/include/services/apis/generated/vision-table.md, static/include/services/apis/generated/vision.md, static/include/services/apis/overrides/methods/go.vision.CaptureAllFromCamera.VisCapture.return.md, static/include/services/apis/overrides/methods/go.vision.CaptureAllFromCamera.cameraName.md, static/include/services/apis/overrides/methods/go.vision.CaptureAllFromCamera.opts.md, static/include/services/apis/overrides/protos/vision.CaptureAllFromCamera.md
Add `CaptureAllFromCamera` API.
- Only for PySDK and Go, not implemented in Flutter.
- Looks like PySDK has fixed / moved more data type links upstream.
- I guessed at whatever Go param `opts` and return `VisCapture` type mean. Former total guess, latter from the PySDK return. Feel free to update upstream or create a follow-up ticket if you would like to tell Eng what to put here instead!
- No code sample for Go. Please feel free to create a ticket to add one upstream if you'd like to see one!
=> DOCS-2349: Add CaptureAllFromCamera API

docs/services/ml/upload-training-script.md
Small phrasing change + keep styling of "tar.gz" consistent
=> Update upload-training-script.md small fix

docs/build/configure/triggers.md
-  Populated `headers` in the JSON template and example with the remaining headers outlined in [`webhooks/utils.go`](https://github.com/viamrobotics/app/blob/2df56ed1f0a95a3f45088580e0cfd10009bc02e2/webhooks/utils.go#L15).
- Added new requests to `payload` for both Python cloud/lamda function examples.
- Added a light amount of context to the explanation in the cloud/lamda function instructions to bring awareness to the existence of other headers.
=> DOCS-2244: Document part data ingesting header info

docs/build/configure/triggers.md
=> DOCS-2569: Clarify cloud function API usage

docs/components/board/customlinux.md
We changed pwm pins from being pwm only to be able to be used for gpio output and pwm. RDK PR: https://github.com/viamrobotics/rdk/commit/0adc7b9cb98fcc687100eb92b75edcb7c095f114?diff=unified&w=0
=> DOCS-2376 document new generic linux functionality

docs/services/_index.md, docs/services/base-rc/_index.md, docs/services/data/_index.md, docs/services/frame-system/_index.md, docs/services/generic/_index.md, docs/services/ml/_index.md, docs/services/motion/_index.md, docs/services/navigation/_index.md, docs/services/slam/_index.md, docs/services/vision/_index.md
- Un-bury vision, and put it by ML
- Put ML before mobility to match viam.com
- Make service page order match left nav
- Put the human-readable part of the frame system description first :D
=> Reorder services and tweak descriptions

docs/components/board/pi.md, static/include/components/board/board-digital-interrupts.md
- only needed for pi: change include to not show and not use include on pi
=> DOCS-2814: Separate out digital interrupt type attribute at request from esha

docs/components/camera/ffmpeg.md
Add a note to the ffmpeg camera page to tell users they need to have ffmpeg installed on their system to use this camera model. MacOS users get ffmpeg through viam-server's brew installation, but that does not apply to linux users depending on the app image they install. We are not adding an ffmpeg build dependency to viam-server. My hope is that this could be a module one day and handle its own dependencies, but until then, we add this note.
=> Include note about installing ffmpeg 

assets/scss/_styles_project.scss, docs/configure/agent.md, docs/fleet/provision.md, docs/how-tos/_index.md, docs/how-tos/provision-setup.md, docs/how-tos/provision.md, docs/platform.md
I've added two guides:
- [Prepare provisioning](https://docs-test.viam.dev/3269/how-tos/provision/)
- [Set a machine up](https://docs-test.viam.dev/3269/how-tos/provision-setup/)
=> DOCS-2822: Add provisioning guides

docs/how-tos/deploy-ml.md
* add more instructions on creating a machine to use 
* remove double-instructions for selecting ml model
* modal-dropdown where appropriate
=> DOCS-2790: QA deploy model how-to page

docs/how-tos/sensor-data-query-sdk.md
* add bson requirement
* add more steps/explicit instructions for scripts
* add viam organizations list instructions for org id
=> DOCS-2795: QA query sensor data sdk

docs/how-tos/performance-metrics.md, docs/how-tos/trigger-sync.md
Minor update to the performance data guide.
Structural change to the trigger sync guide. The guide is supposed to teach people how to add their own logic, I think it does a better job at that now.
=> Improve trigger sync guide

docs/appendix/troubleshooting.md, docs/installation/viam-micro-server-dev.md
Errors that felix found from process documented [here](https://docs.google.com/document/d/1a_UKv3A8pPl4Q3Elu1zw5uGcIR0Cv7qCeE1AfnofyLg/edit)
* third error felix provided was already covered in troubleshooting section of installation docs!
=> DOCS-2884: Add ESP32 errors to troubleshooting

docs/installation/viam-micro-server-dev.md
While going through the set up instructions for developing with the micro-rdk, I discovered some changes in the process were required to get it working. By looking at the [micro-rdk Dockerfile](https://github.com/viamrobotics/micro-rdk/blob/main/etc/docker/Dockerfile#L19-L24) used by canon and the GitHub workflows for that repo, the source and version of the ESP-IDF have been updated, as well as the Rust version to be installed by `espup` to support the xtensa architecture.
=> Update micro-rdk manual dev environment instructions

docs/configure/triggers.md
* Not really sure if we want to document this with the current state of our triggers documentation but docs changes were requested
* Add metadata to data received with timestamps and specify that data can be map[string]any
* used to just be a string or list of strings for conditional data ingested type (don't document yet) and data ingested type
=> DOCS-2874: Document per reading timestamps on trigger data

docs/services/data/capture/_index.md
adds based off [this pr](https://github.com/viamrobotics/micro-rdk/pull/272)
=> DOCS-2931: Add cache_size_kb to viam-micro-server data capture component configs

docs/get-started/drive-rover.md, docs/tutorials/control/flutter-app.md
* tested on rover rental bot and does appear to work if a bit flaky, definitely produces a square-like movement and hypothetically the call is the exact same as all the others that do work.
* paired with @kevin49999 and updated code for latest SDK version. Involved readding .id but we kept my other change with isloading.
=> DOCS-2781: QA drive a rover flutter app 

docs/services/data/capture-sync.md
Updates docs to reflect new data manager config defaults going in to next RDK release:
PR that introduced the changes:
https://github.com/viamrobotics/rdk/pull/4161
1. `sync_interval_mins` is and has always been the config key, this PR updates docs to match the viam-server implementation
2. `maximum_num_sync_threads` now has a new default.
=> DATA-2672: Update data manager config default docs

docs/services/vision/mlmodel.md
* overwrites default label path
=> DOCS-2853: Add label_path attribute to mlmodel vision service

static/include/program/authenticate.md
* make just copy/paste parts highlighted 
* also linted file
=> DOCS-3012: Correct highlighting on auth code snippets

docs/services/base-rc/_index.md
While helping a Discord community member configure a base remote control service to use the input controller's joysticks to control their base, following the current documentation around the `control_mode` attribute for the service did not work. After digging into [the code](https://github.com/viamrobotics/rdk/blob/main/services/baseremotecontrol/builtin/builtin.go#L130-L142) for the service, it appears to be a spelling discrepancy between the RDK and the docs. The docs specify "joyStickControl" as the expected mode name, while the RDK is looking for "joystickControl". 
I'm choosing to fix this in the docs as the quicker solution, however this could be seen as a bug in the RDK instead. If the latter is the better long term solution, please let me know and I will open the corresponding PR …
=> docs(service/base-rc): fix control_mode instructions

docs/how-tos/provision-setup.md
- updates to the 'manual install' path
Ran into trouble when trying it
Followed steps in rendered docs on a pi
1. Do we actually need this path? Like is the install script not sufficient. (I think the answer is yes, but LMK if not).
2. Should I nudge people to the 'install viam-agent on live systems' link at the top of the manual install tab? For many users that is actually the better choice
=> update commands in agent 'manual install' path

docs/tutorials/control/air-quality-fleet.md
I changed the `pm_2.5` key to `pm_2_5` for my module.
`pm_2.5` still works (it is not backwards-breaking), but `pm_2_5` is the preferred new way to access this key.
(periods in the keys are painful)
=> Update air-quality-fleet to use new preferred pm_2_5 key

docs/components/motor/28byj48.md, docs/components/motor/gpiostepper.md
This pr removes the docs for the builtin imu-vectornav movement_sensor, dmc4000 motor, and renogy power_sensor.
=> [RSDK-9015][RSDK-9023][RSDK-9015] Remove Vectornav, renogy and dmc4000 from docs

docs/cli.md, docs/how-tos/create-custom-training-scripts.md
https://docs-test.viam.dev/3617/cli/#train
https://docs-test.viam.dev/3617/how-tos/create-custom-training-scripts/
=> DOCS-2887: Support command line args for training scripts

docs/cli.md
The CLI `viam upload` command does not allow you to select a directory as a `path`. You must point to a specific file. In addition, the file should be zipped with tar, and have the .tar.gz extension
=> Update cli.md to fix incorrect command

docs/how-tos/manage-modules.md
* adds line for token and description that this is only for private git repos
=> DOCS-3009: Add token field to build-action for private build support

docs/how-tos/collect-sensor-data.md, docs/how-tos/conditional-sync.md, docs/how-tos/image-data.md, docs/how-tos/trigger-sync.md, docs/services/data/_index.md
https://docs-test.viam.dev/3652/how-tos/trigger-sync/#return-should_sync-as-a-reading-from-a-sensor
=> Update trigger sync page

docs/services/data/_index.md
[Ticket](https://viam.atlassian.net/browse/DOCS-3095)
1. Document the `Capture Directly to MongoDB` feature.
=> [DOCS-3095] - local mongo collection

static/include/services/apis/generated/mlmodel.md
* edits infer method, adds from robot, edits get resource name
=> DOCS-2953: Edit mlmodel service from QA

docs/architecture/viam-server.md, docs/configure/agent.md
@benjirewis can you confirm this is how it works?
https://docs-test.viam.dev/3703/architecture/viam-server/#maintenance-window
=> DOCS-3157: Use maintenance window within agent

docs/configure/agent.md
@benjirewis - thoughts on this? Does that cover it?
https://docs-test.viam.dev/3726/configure/agent/#version-updates
=> DOCS-3084: Update agent.md

docs/cli.md
Missing closing bracket for Markdown link: https://docs.viam.com/cli/
=> Fix Markdown typo in CLI docs

docs/components/camera/transform.md
We have not tested most of the transform camera's pipelines in over two years, and some of them remain extremely low use. I'm being a bit cautious and removing these attributes in preparation for a full deprecation of these pipelines and perhaps this model - tbd.
The models removed are configured on fewer than 5 machines total over Viam's four-year span, and 0 configured machines in the last year.
=> Remove some transform pipelines

static/include/app/apis/generated/data_sync.md
* example is still correct, with a motor 
* tip from matt vella
=> DOCS-3233: Fix tabular data upload to include tip to include key readings for sensors 

docs/how-tos/create-module.md
Edits the module how-to to reflect the replacement of `AttributeMap` with `ProtoStruct`
=> Update the C++ module creation docs to reflect new data type

docs/components/motor/gpiostepper.md
When using the gpiostepper component I noticed that the attribute name was changed to `stepper_delay_usec`. Also wanted to add a note that without this attribute defined you cannot call SetPower and get an exception message saying that it needs to be set.
=> Update stepper_delay_usec for gpiostepper

docs/dev/reference/apis/data-client.md
Vignesh pointed out that this is outdated as the data client API is now Golang, Python, Typescript, and Flutter SDKs. We have yet to add automation for any of those other ones but for now I thought removing the notice is a start to make it more accurate.
=> Update data-client.md remove support notice

docs/operate/get-started/other-hardware/_index.md, docs/tutorials/configure/pet-photographer.md
Ideally some of these would link to individual tablestep steps but fine for now https://viam.atlassian.net/browse/DOCS-3358
=> Add an alias and some links

docs/data-ai/data/visualize.md
* now supports visualizing data captured by non-sensor components
=> DOCS-3355: Update visualize.md for time series widget upgrades

docs/dev/tools/cli.md
Do not merge until next CLI release
=> DOCS-3395: Support downloading logs

assets/js/toc.js, assets/scss/_styles_project.scss, docs/dev/reference/contributing.md, docs/dev/tools/tutorials.md, docs/tutorials/_index.md, layouts/partials/sidebar-tree.html
This cleans up the sidenav for hidden pages and tutorials. Previously this would be either empty or not show the active path. Now it will show something sensible:
- For tutorials it will show a link to the tutorials page and the table of contents.
- For hidden pages, it will show the path to the page if we're on the page and hide it otherwise.
=> DOCS-3412: Show left nav for tutorials and hidden pages

docs/data-ai/ai/deploy.md, docs/data-ai/ai/run-inference.md, docs/dev/reference/apis/services/generic.md, docs/dev/reference/apis/services/vision.md, docs/operate/reference/services/vision/_index.md
try 2
* fix empty vision service page
=> Fix link structure for vision models and add generic alias

.github/workflows/sdk_protos_map.csv, .github/workflows/update_sdk_methods.py, static/include/components/apis/generated/camera.md, static/include/components/apis/overrides/methods/go.camera.Image.ImageMetadata.return.md, static/include/components/apis/overrides/methods/go.camera.Image.after.md, static/include/components/apis/overrides/methods/go.camera.Image.byte.return.md, static/include/components/apis/overrides/methods/go.camera.Image.mimeType.md, static/include/services/apis/generated/vision.md
* tested and confirmed with rand that decoded function is what we want to use for the vision service samples
=> DOCS-3196: Update Camera interface for Go Image function and remove Stream/Next

docs/tutorials/_index.md
We need to hide children to ensure the tutorials aren't put into the side nav
=> Fix bug that added the expand icon for tutorials

docs/data-ai/reference/architecture.md, docs/dev/reference/architecture.md, docs/manage/reference/architecture.md
Made link titles that are hopefully helpful in each separate context. For example, in Manage, didn't want people confused between this and Organize machines.
=> DOCS-3377: Add link to architecture from each reference section

docs/data-ai/capture-data/capture-sync.md
* hopefully this will make it more clear to the ai so it doesn't give the first example when someone is looking for the second or third
=> DOCS-2671: Make phrasing more clear on remote part data capture examples

docs/dev/_index.md, docs/dev/reference/apis/components/camera.md, docs/operate/reference/services/vision/color_detector.md, docs/operate/reference/services/vision/mlmodel.md
* API has already been removed but thought this needed to go? double checking with sean
=> DOCS-3471: Update camera.md remove stream from Go camera interface

docs/operate/get-started/other-hardware/_index.md, docs/operate/get-started/other-hardware/hello-world-module.md, docs/operate/get-started/other-hardware/manage-modules.md
https://deploy-preview-3890--viam-docs.netlify.app/operate/get-started/other-hardware/#test-your-module-locally
=> DOCS-3311: Update Python module test and upload steps

docs/data-ai/capture-data/advanced/how-sync-works.md
=> DOCS-3183: Add where data capture directory is for sudo users

docs/data-ai/ai/advanced/upload-external-data.md, docs/data-ai/ai/alert.md, docs/data-ai/capture-data/advanced/how-sync-works.md, docs/data-ai/capture-data/capture-sync.md, docs/data-ai/capture-data/conditional-sync.md, docs/data-ai/data/advanced/alert-data.md
=> DOCS-3499: Improve capture edge data 

docs/manage/fleet/reuse-configuration.md, docs/manage/manage/white-labelled-billing.md
@RoxyFarhad and @adithyagurunathan is this how you think this should work? https://deploy-preview-3957--viam-docs.netlify.app/manage/manage/white-labelled-billing/#set-custom-pricing You add a billing fragment and then add the fragment to another fragment that is used for provisioning?
=> DOCS-3481: Add billing fragment

docs/dev/tools/cli.md
https://deploy-preview-3974--viam-docs.netlify.app/dev/tools/cli/#machines-alias-robots
=> DOCS-3488: Add tunnel command to CLI

docs/dev/reference/glossary/module.md, docs/manage/fleet/reuse-configuration.md, docs/manage/software/deploy-software.md
@mcvella & @HipsterBrown thanks for the feedback so far - would you mind reviewing the changes to https://deploy-preview-3980--viam-docs.netlify.app/manage/software/deploy-software/ and see if this addresses your feedback? It's not a lot of changes but it may be enough to do the trick. If either of you have 10 min to chat through this and would prefer that, let me know.
=> DOCS-3497: Update deploy software

docs/data-ai/ai/train.md
* parsing labels and adding validation for num_epochs (used later if they decide to implement a fit function)
* removing google cloud imports bc already gets imported 
Manual testing notes:
* did test and successfully submitted training job with the labels which succeeded with cli (not with UI bc you have to put labels in the arg, put notes for that on docs and made alternate template with the corrections I found but without parsing labels)
=> DOCS-3423: Update training script to parse labels based on feedback from etai/tahiya

docs/data-ai/ai/deploy.md, docs/data-ai/ai/train-tflite.md, docs/dev/reference/changelog.md, docs/operate/reference/services/vision/mlmodel.md
* simplify docs and make easier to follow 
* remove prerequisites of camera and webcam from train-tflite bc that would have come earlier in the process
=> DOCS-3423: Add some feedback from Adrienne and redesign deploy.md based on Eliot's feedback for capture sync

docs/dev/tools/cli.md, static/include/how-to/install-cli.md
- change windows CLI instructions to make it clear this a binary you run directly
This is not an installer yet. (It's annoying to keep track of the loose binary so it's a good idea to make it an installer though).
=> update windows CLI instructions

docs/operate/reference/module-configuration.md
Staging: https://deploy-preview-3993--viam-docs.netlify.app/operate/reference/module-configuration/#environment-variables
@cheukt I could use confirmation of which vars are available on local modules vs not
=> DOCS-3438: Update module environment variables

docs/operate/get-started/setup.md, docs/operate/reference/components/board/esp32.md, static/include/micro-rdk-hardware.md
The changes set the minimum Flash requirements for the micro-server to 8MB. 
While it's technically possible for a user to build their project with a custom partition table to utilize a 4MB device, they would not be able to utilize certain key features (ex. OTA). 
Also updated some adjacent wording.
=> update hardware requirements for micro-server

docs/operate/get-started/other-hardware/_index.md
because this should actually be "the Micro-RDK" not viam-micro-server, but isn't necessary here anyway
=> Fix viam-micro-server terminology

docs/dev/reference/glossary/api-namespace-triplet.md, docs/dev/reference/glossary/subtype.md, docs/operate/get-started/other-hardware/cpp-module.md, docs/operate/reference/advanced-modules/create-subtype.md
I don't think anything else from https://github.com/viamrobotics/docs/pull/3994 needs reverting because the rest is conceptually true either way
=> DOCS-3623: Review subtype vs API distinction

docs/operate/get-started/other-hardware/_index.md
For now until c++ page is reinstated
=> DOCS-3493: Add link to C++ example module

docs/operate/reference/advanced-modules/create-subtype.md
I know a note in next steps is atypical but it relates to next steps, and shouldn't be on the regular implement a model page
=> DOCS-3578: Add custom API imports note

docs/operate/get-started/other-hardware/_index.md
Incremental; still considering a dependencies how-to or similar
@penguinland Mind reviewing the Go part? Edit: adding @martha-johnston per offline discussion
@michaellee1019 for Python part (or any other thoughts)
https://deploy-preview-4089--viam-docs.netlify.app/operate/get-started/other-hardware/#implement-the-component-api
=> DOCS-3695, DOCS-3401: Add to dependency, validate, and reconfigure info

docs/dev/reference/changelog.md
=> DOCS-3672: Add config api, namespace, type changes to changelog

docs/operate/get-started/other-hardware/_index.md
Chatbot continues to struggle. Maybe this will help.
=> DOCS-3795: Direct custom module questions

assets/scss/_styles_project.scss, layouts/partials/navbar.html
The link to the Viam app in the docs navbar doesn't appear to work anymore. I'm not sure how it was working in the past since it was only a button with no anchor tag. To keep this from being interrupted by JS issues, I've updated the button to wrap the `app.viam.com` and icon in an anchor tag instead of a span to make it a working link.
=> fix: wrap app.viam.com link in anchor tag

docs/operate/reference/viam-server/manage-viam-server.md
One of my suggestions in https://github.com/viamrobotics/docs/pull/4209 accidentally a word. This fixes that typo, polishes some nearby wording, and removes the 'command line' class and bash-prompt symbol from a non-interactive line.
=> Further polish a wording issue I created in #4209

assets/scss/_styles_project.scss
The image on the right side of the landing page is awfully distorted on Safari on the production site right now, stretched vertically to roughly the page height. I believe the landing page is the only page that uses this style, and it displays nicely in Firefox and Chrome and Safari after this fix. But let me know if we have other ways to test and validate style changes.
=> Fix broken landing page image on Safari

docs/operate/reference/advanced-modules/_index.md, docs/operate/reference/advanced-modules/docker-modules.md
https://deploy-preview-4187--viam-docs.netlify.app/operate/reference/advanced-modules/#package-and-deploy-using-docker
=> DOCS-2930: Add first_run flow for Docker modules

docs/manage/troubleshoot/alert.md
The code example is correct, the table was not
=> Fix argument case 

layouts/_default/_markup/render-codeblock.html
All of the highlighted lines in the docs are rendered one line above where they ought to be. This PR fixes the issue.
A few examples:
* https://docs.viam.com/tutorials/projects/helmet/
* https://docs.viam.com/operate/get-started/other-hardware/hello-world-module/#implement-the-api-methods (open the Go tab and look at the example in step 2; this example notably uses the first branch of the conditional logic, which sets an offset starting line)
* https://docs.viam.com/dev/reference/sdks/connectivity/ (all tabs)
There is probably a better way to do this -- for instance, I'm not convinced we need so much custom logic for code examples at all -- but this fix fixes the problem without changing all of the variables we use to configure code snippets, and without ripping out any internals like …
=> Fix off-by-one rendering of all highlighted lines in the docs!

docs/operate/get-started/other-hardware/micro-module.md, docs/operate/reference/components/board/esp32.md
Swept for instances of related versions and just found these two. We of course point to https://github.com/viamrobotics/micro-rdk/tree/main/templates/project but that is being updated.
Don't merge until https://viam.atlassian.net/browse/RSDK-8990 is released.
=> DOCS-3797: Modernize the Micro-RDK platform

docs/dev/tools/cli.md
Sniping DOCS-3191 from @npentrel (https://github.com/viamrobotics/docs/pull/4232) because a user experienced an issue with this CLI method and that led me to discover some other issues (like the fact that org-id and location-id are also no longer required when using the `ids` argument).
=> DOCS-3191,DOCS-3879: Remove mention of outdated file-ids argument and updated associated config

docs/tutorials/get-started/blink-an-led.md, docs/tutorials/projects/claw-game.md
=> DOCS-3893: Change code sample to connect

docs/manage/troubleshoot/troubleshoot.md
Arguably overkill but it's within a troubleshooting page so not in the way of other tasks
=> DOCS-3886: Add advanced Go module debugging

docs/operate/get-started/other-hardware/_index.md, docs/operate/get-started/other-hardware/hello-world-module.md, docs/operate/get-started/other-hardware/manage-modules.md
A user asked about what files to scp to a pi when testing a local module on a separate computer. I tested both this and scp'ing the tarball plus the meta.json (with a generated Python module), and both work. I'm thinking meta.json should be in the tarball so it's all together, but is there a reason that'd actually not be preferred?
=> DOCS-3895: Add meta.json to tarball

config.toml, layouts/partials/sidebar-tree.html
Given our tabbed configuration, the 'first level' is actually the third in configuration.
Much AI ink was spilled to discover this one-line change.
=> DOCS-3814: Expand left sidenav one level down by default to improve navigation and discoverability

docs/operate/get-started/other-hardware/_index.md, docs/operate/get-started/other-hardware/manage-modules.md
=> DOCS-3920: Add module build time note

docs/operate/get-started/setup-micro/_index.md
(Explanation of zillions of commits:
Had offline convo w/Gautham about which way we should actually document it. Turns out we can keep it the same after all. Disregard.)
=> Tweak micro page

docs/manage/fleet/reuse-configuration.md
* fixes an issue seen in the Ask AI slack channel.
Question:
How would a fragment override for an ml_model package version look like?
Answer:
Here's how you can override an ML model package version in a fragment:
```
"fragment_mods": [
{
"fragment_id": "abcd7ef8-fa88-1234-b9a1-123z987e55aa",
"mods": [
{
"$set": {
"packages.0.version": "latest"
}
}
]
}
]
```
You can set the version to:
- "^<major version number>" (e.g. "^1") for updates within the same major release
- "~<minor version number>" (e.g. "~1.8") for updates within the same minor release
- "latest" to always update to the latest release
- "<version number>" (e.g. "1.8.3") to pin to a specific version
Remember to check your machine's LOGS tab after configuring fragment overwrites to ensure there are no issues with the …
=> Ask AI feedback: Fix package version configuration example

docs/operate/reference/kinematic-chain-config.md, docs/operate/reference/module-configuration.md, docs/operate/reference/viam-micro-server/_index.md, docs/operate/reference/viam-server/_index.md
With reference open now, really needed some cleanup:
- Put things in an order that matches Build and Integrate overall
- Try to tell people immediately that they do *not* need to read about complex kinematic chains
=> Clean up build reference

docs/operate/reference/components/camera/webcam.md
Newer MacOS versions require manual Camera permission approval.
Just adding a small section to the webcam docs here.
=> RSDK-10583 - Add macos webcam permissions section

docs/tutorials/projects/make-a-plant-watering-robot.md
Still had a tab open containing this tutorial. Realized I missed a specific reference in a comment to a number that now uses a variable.
=> Fix minor issue with comment in plant watering tutorial

docs/operate/get-started/setup-micro/_index.md
To get AI to stop saying "For 32-bit systems, you can use viam-micro-server which is specifically built for microcontrollers."
=> DOCS-4042: Clarify Micro-RDK 32-bit support

.github/vale/styles/Vocab/main/accept.txt, .github/vale/styles/config/vocabularies/main/accept.txt, .github/workflows/vale-lint.yml
Per https://vale.sh/docs/keys/vocab:
>In versions of Vale prior to 3.0, vocabularies were stored in <StylesPath>/Vocab. When upgrading from an older version of Vale, you'll need to move your vocabularies to the new <StylesPath>/config/vocabularies location.
Tested: successfully ran Vale 3.11.2 (latest) locally using the Viam vale.ini located in this repo.
=> Move vale vocab `main` to dir that vale >=3.0.0 expects

docs/dev/tools/cli.md
Based on changes that began and iterated in https://github.com/viamrobotics/docs/pull/4394
But without miscellaneous changes unrelated to data pipelines.
Preserves `data` section move for alphabetical ordering because I think it makes it easier to find commands.
=> DOCS-3949: Data Pipelines CLI

docs/dev/tools/cli.md
Command now requires users to specify `ids` or `filter`
=> DOCS-4107: Document new positional args for viam data export binary

docs/dev/reference/apis/sessions.md
Noticed while looking at content related to [DOCS-4095: Remove "Establish a connection" sections from API pages](https://github.com/viamrobotics/docs/pull/4422/files#top)
=> Fix typos in sessions.md

docs/operate/get-started/_index.md
Currently 'Connect devices' shows up at a different font size, which looks wonky; this resolves the issue.
=> Make 'connect devices' sidebar entry consistent with other Operate categories

assets/js/base.js
It seems that the default `base.js` file in Docsy included tooltip initialization (see https://github.com/google/docsy/blob/a053131a4ebf6a59e4e8834a42368e248d98c01d/assets/js/base.js for an example of how they might have done this; unfortunately it's tricky to get the specific version of base.js used in our docsy version).
This adds a single line that initializes JQuery tooltips used in Docsy.
https://deploy-preview-4441--viam-docs.netlify.app/dev/reference/glossary/ provides proof that this approach works.
We could also try refactoring everything out of base.js and rely on the default behavior instead, but:
- that would take more time, and this works
- i'm not 100% comfortable with reliance on that default behavior -- what if we do want to use base.js in the future, and don't remember …
=> Fix tooltips

docs/dev/tools/cli.md
People keep asking about the shell service and using the term scp - which is understandable. This will connect the concepts better hopefully
=> DOCS-4138: Clarify shell service and scp

docs/data-ai/train/capture-annotate-images.md
- use fewer words
- tighten up language around annotate/tag/label
- answer 'why' quickly
=> Update annotate section based on Product feedback

docs/dev/tools/cli.md
waiting on https://viam.atlassian.net/browse/RSDK-10731
=> DOCS-3295: Add profiles

docs/dev/tools/cli.md
Thanks to Jad for identifying this
=> Fix machines list CLI info
